## <font color="greenblue">Processamento - uma única tabela</font>

In [ ]:
import pandas as pd
import numpy as np
# from statsmodels.stats.proportion import proportions_ztest
from collections import Counter
from utils import ordenar_labels, ordenar_labels_multipla, ordenar_valores, classificar_nps, funcao_agrupamento, classificar_satis

TipoTabela = 'MULTIPLA'
Colunas = 'MERC_PME, MERC_500, TIM_TOT, TIM_PME, TIM_500, TIM_PRIME, VIV_TOT, VIV_PME, VIV_500, CLA_TOT, CLA_PME, CLA_500'
Cabecalho = 'Mercado PME, Mercado 500+, TIM, TIM PME, TIM 500+, TIM Prime, VIVO, VIVO PME, VIVO 500+, CLARO, CLARO PME, CLARO 500+'
Var_linha = 'Q8' 
NS_NR = 'NAO'
valores_BTB = '1, 2'
valores_medium = '3'
valores_TTB = '4, 5'
Valores_Agrup = 'Q8_1, Q8_2, Q8_3'
Fecha_100 = 'NAO'
Var_ID = 'codigo_entrevistado' # codigo_entrevistado | ID_EMP
Var_Pond = 'POND'
Titulo = '8. (SATISFAÇÃO 2021) Por que deu esta nota de recomendação para a _______? (ESPONTÂNEA - RM)' # 8. (SATISFAÇÃO 2021) Por que deu esta nota de recomendação para a _______? (ESPONTÂNEA - RM)

In [ ]:
import pandas as pd
import numpy as np
# from statsmodels.stats.proportion import proportions_ztest
from collections import Counter
from utils import ordenar_labels, ordenar_labels_multipla, ordenar_valores, classificar_nps, funcao_agrupamento, classificar_satis

TipoTabela = 'IPA_10'
Colunas = 'ONDA, SEG_NOVO_BU'
Cabecalho = 'Ondas, Segmento BU'
Var_linha = 'C_26' 
NS_NR = 'NAO'
valores_BTB = '1, 2, 3, 4, 5'
valores_TTB = '8, 9, 10'
Valores_Agrup = 'Q8_1, Q8_2, Q8_3'
Fecha_100 = 'NAO'
Var_ID = 'ID_EMP' # codigo_entrevistado | ID_EMP
Var_Pond = 'POND'
Titulo = 'C26. Satisfação Geral Final com a CIELO' # 8. (SATISFAÇÃO 2021) Por que deu esta nota de recomendação para a _______? (ESPONTÂNEA - RM)

In [2]:
path = r'C:\Users\rayner.santos\Downloads\Consistencia e Processamento\BD_TIM_Imagem_Onda1_2025_v10.xlsx'
path = r"C:\Users\rayner.santos\Downloads\Consistencia e Processamento\Cielo\EMP_Cielo Satisfacao_3onda_NOV25_2025.12.26.xlsx"
data = pd.read_excel(path, sheet_name='BD_CODIGOS')
df = data.copy()
df

,ID_EMP,ID_ONDA,ONDA,COLETA,NU_SO_EC,POND,CIELO_CAMPO,PF_PJ,VCID,VUF,...,BCOSS_2,BCOSS_3,NUM_F,NUM_FX,FATC,VRAMO,SETOR_BIGDATA,TEMP_EX,TEMP_AC,SEXO
0,3000230,1634,59,2,2.901174e+09,0.999119,2,2,NaN,2,...,NaN,NaN,1,1,2.0,20,20.0,1,1,1
1,3001659,5090,59,2,NaN,1.497418,4,2,NaN,7,...,NaN,NaN,1,2,2.0,13,13.0,4,4,1
2,3000383,1986,59,2,NaN,0.317763,2,2,NaN,6,...,NaN,NaN,1,3,1.0,21,21.0,2,2,2
3,3000455,2153,59,2,NaN,0.263658,4,2,NaN,6,...,NaN,NaN,1,2,1.0,21,21.0,6,5,1
4,3000985,3488,59,2,NaN,1.982729,4,1,NaN,2,...,NaN,NaN,1,2,2.0,8,8.0,5,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15381,3004081,102279,59,1,NaN,0.263658,3,2,80.0,8,...,NaN,NaN,1,3,1.0,21,21.0,4,3,1
15382,3004082,102294,59,1,NaN,1.982729,3,1,80.0,6,...,NaN,NaN,3,19,2.0,13,13.0,6,3,1
15383,3004083,102343,59,1,NaN,1.497418,3,2,4.0,1,...,NaN,NaN,2,7,2.0,4,4.0,5,5,1
15384,3004084,102609,59,1,NaN,1.497418,3,2,3.0,5,...,NaN,NaN,2,5,2.0,20,20.0,2,2,1
15385,3004085,102632,59,1,NaN,0.263658,3,2,80.0,1,...,NaN,NaN,1,2,90.0,13,13.0,5,5,2

In [5]:
lista_labels = pd.read_excel(path, sheet_name='LISTA_LABELS')
lista_labels = lista_labels.iloc[1:, :].copy()
lista_labels.columns = ['Coluna', 'Codigo', 'Label']
lista_labels["Coluna"] = lista_labels["Coluna"].ffill().str.strip()
lista_labels

        Coluna  Codigo               Label
1         ONDA    28.0               Abr23
2         ONDA    29.0      Mai23 (mensal)
3         ONDA    30.0      Jun23 (mensal)
4         ONDA    31.0               Jul23
5         ONDA    32.0      Ago23 (mensal)
...        ...     ...                 ...
10221  TEMP_AC     5.0  Entre 5,1 a 8 anos
10222  TEMP_AC     6.0      8 anos ou mais
10223  TEMP_AC    90.0               NS/NR
10224     SEXO     1.0           Masculino
10225     SEXO     2.0            Feminino

[10225 rows x 3 columns]

In [9]:
# Variáveis para as colunas da tabela (bandeiras)
Colunas = Colunas.split(sep=', ')
print(Colunas)
dict_ord_labels = {}

for col in Colunas:
    if col not in df.columns:
        raise ValueError(f"Coluna '{col}' não encontrada no DataFrame.")        
    else:
        df[col], ord_labels = ordenar_labels(df=data, lista_labels=lista_labels, Variavel=col)
        dict_ord_labels[col] = ord_labels
        print(f"\nColuna ordenada (unique): {df[col].unique()}")

['ONDA', 'SEG_NOVO_BU']

#== VARIÁVEL SENDO PROCESSADA: ONDA ==#
ONDA
59    4074
55    3877
51    3826
47    3609
Name: count, dtype: Int64

ONDA
59    0.264786
55    0.251982
51    0.248668
47    0.234564
Name: proportion, dtype: Float64

Labels filtrados para a coluna alvo:
     Codigo           Label
1       28           Abr23
2       29  Mai23 (mensal)
3       30  Jun23 (mensal)
4       31           Jul23
5       32  Ago23 (mensal)
6       33  Set23 (mensal)
7       34  Out23 (mensal)
8       35           Nov23
9       36          Dez/23
10      37  Jan24 (mensal)
11      38  Fev24 (mensal)
12      39          Mar/24
13      40  Abr24 (mensal)
14      41  Mai24 (mensal)
15      42  Jun24 (mensal)
16      43          Jul/24
17      44  Ago24 (mensal)
18      45  Set24 (mensal)
19      46  Out24 (mensal)
20      47           Nov24
21      48   Dez24(Mensal)
22      49   Jan25(Mensal)
23      50   Fev25(Mensal)
24      51           Mar25
25      52  Abr25 (Mensal)
26      53  Mai25 (Mensal)
27      54  Jun25 (Mensal)
28      55           Jul25
29      56   Ago25(Mensal)
30      57   Set25(Mensal)
31      58   Out25(Mensal)
32      59           Nov25

df[Variavel] (antes de ordenar):
0    59
1    59
2    59
3    59
4    59
5    59
6    59
7    59
8    59
9    59
Name: ONDA, dtype: Int64

Ordem numérica encontrada: [47, 51, 55, 59]

Ordem mapeada com labels:
    Codigo  Label
0      47  Nov24
1      51  Mar25
2      55  Jul25
3      59  Nov25

Ordem final com labels: ['Nov24', 'Mar25', 'Jul25', 'Nov25']

Coluna categórica ordenada criada: ['Nov25', 'Nov25', 'Nov25', 'Nov25', 'Nov25', 'Nov25', 'Nov25', 'Nov25', 'Nov25', 'Nov25']
Categories (4, object): ['Nov24' < 'Mar25' < 'Jul25' < 'Nov25']
ONDA
Nov25    4074
Jul25    3877
Mar25    3826
Nov24    3609
Name: count, dtype: int64

ONDA
Nov25    0.264786
Jul25    0.251982
Mar25    0.248668
Nov24    0.234564
Name: proportion, dtype: float64

Coluna ordenada (unique): ['Nov25', 'Nov24', 'Mar25', 'Jul25']
Categories (4, object): ['Nov24' < 'Mar25' < 'Jul25' < 'Nov25']

#== VARIÁVEL SENDO PROCESSADA: SEG_NOVO_BU ==#
SEG_NOVO_BU
2    6995
1    6668
3    1723
Name: count, dtype: Int64

SEG_NOVO_BU
2    0.454634
1    0.433381
3    0.111985
Name: proportion, dtype: Float64

Labels filtrados para a coluna alvo:
      Codigo           Label
135       1  Empreendedores
136       2          Varejo
137       3              GC

df[Variavel] (antes de ordenar):
0    2
1    2
2    1
3    1
4    2
5    1
6    2
7    1
8    1
9    1
Name: SEG_NOVO_BU, dtype: Int64

Ordem numérica encontrada: [1, 2, 3]

Ordem mapeada com labels:
    Codigo           Label
0       1  Empreendedores
1       2          Varejo
2       3              GC

Ordem final com labels: ['Empreendedores', 'Varejo', 'GC']

Coluna categórica ordenada criada: ['Varejo', 'Varejo', 'Empreendedores', 'Empreendedores', 'Varejo', 'Empreendedores', 'Varejo', 'Empreendedores', 'Empreendedores', 'Empreendedores']
Categories (3, object): ['Empreendedores' < 'Varejo' < 'GC']
SEG_NOVO_BU
Varejo            6995
Empreendedores    6668
GC                1723
Name: count, dtype: int64

SEG_NOVO_BU
Varejo            0.454634
Empreendedores    0.433381
GC                0.111985
Name: proportion, dtype: float64

Coluna ordenada (unique): ['Varejo', 'Empreendedores', 'GC']
Categories (3, object): ['Empreendedores' < 'Varejo' < 'GC']

In [ ]:
# Etapas de ETL para as colunas principais a serem utilizadas
# Transformação na variável para a linha da tabela
if TipoTabela == 'SIMPLES':
    if NS_NR == 'NAO':
        df[Var_linha] = df[Var_linha].replace('NS/NR', np.nan)
        df[Var_linha], ord_labels = ordenar_labels(df=data, lista_labels=lista_labels, Variavel=Var_linha)
        # df[Var_linha] = pd.Categorical(df[Var_linha], categories=df[Var_linha][pd.notna(df[Var_linha])].unique(), ordered=True)
    else:
        df[Var_linha], ord_labels = ordenar_labels(df=data, lista_labels=lista_labels, Variavel=Var_linha)
        # df[Var_linha] = pd.Categorical(df[Var_linha], categories=df[Var_linha][pd.notna(df[Var_linha])].unique(), ordered=True)
    
elif (TipoTabela == 'NPS') | (TipoTabela == 'IPA_10'):
    if NS_NR == 'NAO':
        df[Var_linha] = df[Var_linha].replace('NS/NR', np.nan)
        df[Var_linha] = df[Var_linha].replace('ns/nr', np.nan)
        df[Var_linha] = df[Var_linha].replace('90', np.nan)
        df[Var_linha] = df[Var_linha].replace('99', np.nan)
        df[Var_linha] = df[Var_linha].replace('999', np.nan)
        df[Var_linha] = df[Var_linha].replace('9999', np.nan)
        df[Var_linha] = df[Var_linha].replace(90, np.nan)
        df[Var_linha] = df[Var_linha].replace(99, np.nan)
        df[Var_linha] = df[Var_linha].replace(999, np.nan)
        df[Var_linha] = df[Var_linha].replace(9999, np.nan)
        df[Var_linha] = pd.to_numeric(df[Var_linha], errors='coerce', downcast='integer')
        # df[Var_linha], ord_labels = ordenar_labels(df=df, lista_labels=lista_labels, Variavel=Var_linha)
        df[Var_linha] = pd.Categorical(df[Var_linha], categories=ordenar_valores(df[Var_linha]), ordered=True)

        if TipoTabela == 'NPS':
            df['var_agrupada'] = df[Var_linha].apply(classificar_nps)

        elif TipoTabela == 'IPA_10':
            valores_BTB = [int(v) for v in valores_BTB.split(sep=', ')]
            valores_TTB = [int(v) for v in valores_TTB.split(sep=', ')]
            df['var_agrupada'] = funcao_agrupamento(df[Var_linha], valores_BTB, valores_TTB)

    else:
        # df[Var_linha] = df[Var_linha].replace('90', np.nan)
        # df[Var_linha] = df[Var_linha].replace('99', np.nan)
        # df[Var_linha] = df[Var_linha].replace('999', np.nan)
        # df[Var_linha] = df[Var_linha].replace('9999', np.nan)
        # df[Var_linha], ord_labels = ordenar_labels(df=data, lista_labels=lista_labels, Variavel=Var_linha)
        df[Var_linha] = pd.Categorical(df[Var_linha], categories=ordenar_valores(df[Var_linha]), ordered=True)

        if TipoTabela == 'NPS':
            df['var_agrupada'] = df[Var_linha].apply(classificar_nps)

        elif TipoTabela == 'IPA_10':
            valores_BTB = [int(v) for v in valores_BTB.split(sep=', ')]
            valores_medium = [int(v) for v in valores_medium.split(sep=', ')]
            valores_TTB = [int(v) for v in valores_TTB.split(sep=', ')]
            df['var_agrupada'] = funcao_agrupamento(df[Var_linha], valores_BTB, valores_medium, valores_TTB)

elif TipoTabela == 'IPA_5':
    if NS_NR == 'NAO':
        df[Var_linha] = df[Var_linha].replace('NS/NR', np.nan)
        df[Var_linha] = df[Var_linha].replace('90', np.nan)
        df[Var_linha] = df[Var_linha].replace('99', np.nan)
        df[Var_linha] = df[Var_linha].replace('999', np.nan)
        df[Var_linha] = df[Var_linha].replace(90, np.nan)
        df[Var_linha] = df[Var_linha].replace(99, np.nan)
        df[Var_linha] = df[Var_linha].replace(999, np.nan)
        valores_BTB = [int(v) for v in valores_BTB.split(sep=', ')]
        valores_TTB = [int(v) for v in valores_TTB.split(sep=', ')]
        df['var_agrupada'] = funcao_agrupamento(df[Var_linha], valores_BTB, valores_TTB)
        df['var_agrupada'] = pd.Categorical(df['var_agrupada'], categories=['BTB', 'Neutro', 'TTB'], ordered=True)
        df[Var_linha], ord_labels = ordenar_labels(df=data, lista_labels=lista_labels, Variavel=Var_linha)
        # df[Var_linha] = pd.Categorical(df[Var_linha], categories=Valores_Agrup, ordered=True)
    else:
        valores_BTB = [int(v) for v in valores_BTB.split(sep=', ')]
        valores_TTB = [int(v) for v in valores_TTB.split(sep=', ')]
        df['var_agrupada'] = funcao_agrupamento(df[Var_linha], valores_BTB, valores_TTB)
        df['var_agrupada'] = pd.Categorical(df['var_agrupada'], categories=['BTB', 'Neutro', 'TTB'], ordered=True)
        df[Var_linha], ord_labels = ordenar_labels(df=data, lista_labels=lista_labels, Variavel=Var_linha)
        # df[Var_linha] = pd.Categorical(df[Var_linha], categories=Valores_Agrup, ordered=True)

elif TipoTabela == 'MULTIPLA':
    if NS_NR == 'NAO':
        df_NS_NR = df.copy()
        
        Valores_Agrup = Valores_Agrup.split(sep=', ')
        # Converte as colunas de motivos para string, preservando NaN
        # for c in Valores_Agrup:
        #     df[c] = df[c].astype("object").where(df[c].isna(), df[c].astype(str))
        #     df_NS_NR[c] = df_NS_NR[c].astype("object").where(df_NS_NR[c].isna(), df_NS_NR[c].astype(str))

        bd_motivo = pd.melt(df, 
                    id_vars=Colunas + [Var_Pond] + [Var_ID],
                    value_vars=Valores_Agrup, 
                    var_name='Valores', 
                    value_name=Var_linha)
        bd_motivo[Var_linha] = bd_motivo[Var_linha].replace('90', np.nan)
        bd_motivo[Var_linha] = bd_motivo[Var_linha].replace('99', np.nan)
        bd_motivo[Var_linha] = bd_motivo[Var_linha].replace('999', np.nan)
        bd_motivo[Var_linha] = bd_motivo[Var_linha].replace('9999', np.nan)
        bd_motivo[Var_linha] = bd_motivo[Var_linha].replace(90, np.nan)
        bd_motivo[Var_linha] = bd_motivo[Var_linha].replace(99, np.nan)
        bd_motivo[Var_linha] = bd_motivo[Var_linha].replace(999, np.nan)
        bd_motivo[Var_linha] = bd_motivo[Var_linha].replace(9999, np.nan)
        bd_motivo = bd_motivo.dropna(subset=[Var_linha])
        print(f'\nbd_motivo em formato de código:\n{bd_motivo}')
        bd_motivo = ordenar_labels_multipla(df=bd_motivo, lista_labels=lista_labels, Variavel=Var_linha, Var_Valores_Agrup=Valores_Agrup[0])
        bd_motivo[Var_linha] = bd_motivo[Var_linha].replace('NS/NR', np.nan)
        # bd_motivo[Var_linha] = pd.Categorical(bd_motivo[Var_linha], categories=ordenar_valores(bd_motivo[Var_linha]), ordered=True)  

        df_limpo = bd_motivo.dropna(subset=[Var_linha])
        print(f'bd_motivo finalizado:\n{df_limpo}')
        df_unico = df_limpo.drop_duplicates(subset=Var_ID, keep='first')
                
        # Bancos para realizar o cálculo do Índice de Multiplicidade (incluir NS/NR)
        bd_motivo_NS_NR = pd.melt(df_NS_NR, 
                    id_vars=Colunas + [Var_Pond] + [Var_ID],
                    value_vars=Valores_Agrup, 
                    var_name='Valores', 
                    value_name=Var_linha)
        bd_motivo_NS_NR = bd_motivo_NS_NR.dropna(subset=[Var_linha])
        bd_motivo_NS_NR = ordenar_labels_multipla(df=bd_motivo_NS_NR, lista_labels=lista_labels, Variavel=Var_linha, 
                                                  Var_Valores_Agrup=Valores_Agrup[0])
        # bd_motivo_NS_NR[Var_linha] = pd.Categorical(bd_motivo_NS_NR[Var_linha], 
        #                                     categories=ordenar_valores(bd_motivo_NS_NR[Var_linha]), ordered=True)
        
        df_NS_NR_limpo = bd_motivo_NS_NR.dropna(subset=[Var_linha])
        print(f'bd_motivo_NS_NR finalizado:\n{df_limpo}')
        df_NS_NR_unico = df_NS_NR_limpo.drop_duplicates(subset=Var_ID, keep='first')    
        
    else:
        Valores_Agrup = Valores_Agrup.split(sep=',')
        bd_motivo = pd.melt(df, 
                    id_vars=Colunas + [Var_Pond] + [Var_ID],
                    value_vars=Valores_Agrup, 
                    var_name='Valores', 
                    value_name=Var_linha)
        bd_motivo = bd_motivo.dropna(subset=[Var_linha])
        bd_motivo = ordenar_labels_multipla(df=bd_motivo, lista_labels=lista_labels, Variavel=Var_linha, Var_Valores_Agrup=Valores_Agrup[0])
        # bd_motivo[Var_linha] = pd.Categorical(bd_motivo[Var_linha], 
        #                                     categories=ordenar_valores(bd_motivo[Var_linha]), ordered=True)
        
        df_limpo = bd_motivo.dropna(subset=[Var_linha])
        df_unico = df_limpo.drop_duplicates(subset=Var_ID, keep='first')

In [22]:
#======= Criação da Tabela Geral =======#
tabela_geral = []
tabelas_pond = []
tabelas_pond_freq_abs = []
tabelas_sem_pond = []
aux_tabelas_pond = []
aux_tabelas_sem_pond = []

tbl_pond_freq_abs_respondentes = []
tbl_sem_pond_respondentes = []

tbl_pond_freq_abs_respostas_NS_NR = []
tbl_pond_freq_abs_respondentes_NS_NR = []

if TipoTabela == 'MULTIPLA':
    if NS_NR == 'NAO':
        banco = df_NS_NR_unico
    else:
        banco = df_unico

    if NS_NR == 'NAO':
        banco_pivotado = bd_motivo_NS_NR
    else:
        banco_pivotado = bd_motivo

    i = 0    
    for col in Colunas:

        # Gerar Tabelas Ponderadas de Frequência Absoluta com o banco empilhado
        tabela = pd.pivot_table(bd_motivo, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
        if Fecha_100 == 'SIM':
            tabela = tabela.div(tabela.sum())
            tabelas_pond.append(tabela)
        else:
            tabelas_pond.append(tabela)

        tabela = pd.pivot_table(banco_pivotado, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
        tbl_pond_freq_abs_respostas_NS_NR.append(tabela)

        tabela = pd.pivot_table(df_unico, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
        tbl_pond_freq_abs_respondentes.append(tabela)

        tabela = pd.pivot_table(banco, values=Var_Pond, index=Var_ID, columns=col, aggfunc='sum')
        tbl_pond_freq_abs_respondentes_NS_NR.append(tabela)

        tabela = pd.crosstab(df_unico[Var_linha], df_unico[col], dropna=False)
        tabela = tabela.fillna(0)
        if len(tabela) == 0:
            tabela = pd.DataFrame(0, index=df_unico[Var_linha][pd.notna(df_unico[Var_linha])].unique(), 
                                columns=df_unico[Colunas[i-1]][pd.notna(df_unico[Colunas[i-1]])].unique())
            print(f'{df_unico[Var_linha][pd.notna(df_unico[Var_linha])].unique()}\n')
            print(f'{df_unico[Colunas[i-1]][pd.notna(df_unico[Colunas[i-1]])].unique()}\n')
        print(f'tabela:\n{tabela}')
        tbl_sem_pond_respondentes.append(tabela)
        i += 1

    tabela_geral = pd.concat(tabelas_pond, axis=1)
    tbl_pond_freq_abs_respondentes = pd.concat(tbl_pond_freq_abs_respondentes, axis=1)
    tbl_sem_pond_respondentes = pd.concat(tbl_sem_pond_respondentes, axis=1)
    tbl_pond_freq_abs_respostas_NS_NR = pd.concat(tbl_pond_freq_abs_respostas_NS_NR, axis=1)
    tbl_pond_freq_abs_respondentes_NS_NR = pd.concat(tbl_pond_freq_abs_respondentes_NS_NR, axis=1)
    
    if Fecha_100 != 'SIM':
        soma_base_ponderada = tbl_pond_freq_abs_respondentes.sum()
        tabela_geral = tabela_geral.div(soma_base_ponderada)
    
    print(f'{tabela_geral}\n')


    # Trazendo a coluna de valores gerais
    soma_colunas = tbl_pond_freq_abs_respondentes.sum()
    soma_colunas = pd.Series(soma_colunas)
    base_ponderada = pd.pivot_table(df_unico, values=Var_Pond, index=Var_ID, aggfunc='sum')
    base_ponderada = pd.Series(base_ponderada.sum())
    base_ponderada = pd.concat([base_ponderada, soma_colunas])
    valores_gerais = pd.pivot_table(bd_motivo, values=Var_Pond, index=Var_linha, aggfunc='sum')
    if Fecha_100 == 'SIM':
        percentual_geral = valores_gerais.div(valores_gerais.sum()).sort_index()
        print(f'\npercentual_geral:\n{percentual_geral}')
        print(f'\nsoma de percentual_geral:\t{percentual_geral.sum()}')
    else:
        percentual_geral = valores_gerais.div(base_ponderada[0]).sort_index()
        print(f'\npercentual_geral:\n{percentual_geral}')
        print(f'\nsoma de percentual_geral:\t{percentual_geral.sum()}')

    # tabela_geral = tabela_geral.div(base_ponderada[1:])
    tabela_geral = pd.concat([percentual_geral, tabela_geral], axis=1)
    print(f'{tabela_geral}\n')

    # Valores para Base Ponderada
    soma_colunas = tbl_pond_freq_abs_respondentes.sum()
    soma_colunas = pd.Series(soma_colunas)
    base_ponderada = pd.pivot_table(df_unico, values=Var_Pond, index=Var_ID, aggfunc='sum')
    base_ponderada = pd.Series(base_ponderada.sum())
    base_ponderada = pd.concat([base_ponderada, soma_colunas])
    tabela_geral.loc['Base Ponderada'] = base_ponderada

    # Valores para Base Sem Ponderar
    valores_gerais_respondentes = df_unico[Var_ID].value_counts()
    soma_colunas = pd.Series(tbl_sem_pond_respondentes.sum())
    print(f'\n{soma_colunas}\n')
    base_sem_ponderar = pd.Series(valores_gerais_respondentes.sum())
    base_sem_ponderar = pd.concat([base_sem_ponderar, soma_colunas])
    print(f'base sem ponderar:\n{base_sem_ponderar.index}\n')
    print(f'{len(base_sem_ponderar.index)}\n')
    print(f'tabela geral:\n{tabela_geral.columns}\n')
    print(f'{len(tabela_geral.columns)}\n')
    base_sem_ponderar.index = tabela_geral.columns
    tabela_geral.loc['Base Sem Ponderar'] = base_sem_ponderar

    # Valores para Base Ponderada - Respostas
    soma_colunas_respostas = tbl_pond_freq_abs_respostas_NS_NR.sum()
    soma_colunas_respostas = pd.Series(soma_colunas_respostas)
    base_ponderada_respostas = pd.pivot_table(banco_pivotado, values=Var_Pond, index=Var_linha, aggfunc='sum')
    base_ponderada_respostas = pd.Series(base_ponderada_respostas.sum())
    base_ponderada_respostas = pd.concat([base_ponderada_respostas, soma_colunas_respostas])

    # Valores para Base Ponderada - Respondentes
    soma_colunas = tbl_pond_freq_abs_respondentes_NS_NR.sum()
    soma_colunas = pd.Series(soma_colunas)
    base_ponderada = pd.pivot_table(banco, values=Var_Pond, index=Var_ID, aggfunc='sum')
    base_ponderada = pd.Series(base_ponderada.sum())
    base_ponderada = pd.concat([base_ponderada, soma_colunas])

    # Índice de Multiplicidade (Total de respostas / Total de respondentes)
    indice_multiplicidade = base_ponderada_respostas / base_ponderada
    tabela_geral.loc['Índice de Multiplicidade'] = indice_multiplicidade

    tabela_geral.rename(columns={tabela_geral.columns[0]: 'Geral'}, inplace=True)
    print(f'{tabela_geral}\n')

else:
    if df[Var_linha].isna().all():
        # df[Var_linha] = df[Var_linha].astype('float').fillna(0)
        df[Var_linha] = df[Var_linha].cat.add_categories(['Não possui categoria']).fillna('Não possui categoria')
        print(f'Variável em branco\n{df[Var_linha]}\n')

    for col in Colunas:
        # Gerar Tabelas Ponderadas de frequência absoluta
        tabela = pd.crosstab(df[Var_linha], df[col], values=df[Var_Pond], aggfunc='sum')
        tabelas_pond_freq_abs.append(tabela)

        # Gerar Tabelas Ponderadas de frequência relativa 
        tabela = tabela.div(tabela.sum())
        tabela = tabela.fillna(0)
        tabelas_pond.append(tabela)
        print(f'Tabela Ponderada Freq Rel: \n{tabela}\n')

        # Gerar Tabelas Sem Ponderação
        tabela = pd.crosstab(df[Var_linha], df[col], dropna=False)
        tabela = tabela.fillna(0)
        print(f'Tabela Sem Ponderação: \n{tabela}\n')
        if len(tabela) == 0:
            tabela = pd.DataFrame(0, index=df[Var_linha][pd.notna(df[Var_linha])].unique(), 
                                columns=df[col][pd.notna(df[col])].unique())
            print(f'Tabela Sem Ponderação: \n{tabela}\n')
        tabelas_sem_pond.append(tabela)

        # Gerar Tabelas para valores agrupados
        if 'var_agrupada' in df.columns:
            tabela = pd.crosstab(df['var_agrupada'], df[col], values=df[Var_Pond], aggfunc='sum')
            tabela = tabela.div(tabela.sum())
            print(f'Tabela Valores Agrupados: \n{tabela}\n')
            aux_tabelas_pond.append(tabela)

            # Tabelas sem ponderação
            tabela = pd.crosstab(df['var_agrupada'], df[col], dropna=False)
            print(f'Tabela Valores Agrupados Sem Ponderação: \n{tabela}\n')
            aux_tabelas_sem_pond.append(tabela)

    tabela_geral = pd.concat(tabelas_pond, axis=1)
    tabelas_pond_freq_abs = pd.concat(tabelas_pond_freq_abs, axis=1)
    tabelas_sem_pond = pd.concat(tabelas_sem_pond, axis=1)

    # Trazendo a coluna de valores gerais
    valores_gerais_pond = pd.pivot_table(df, values=Var_Pond, index=Var_linha, aggfunc='sum', observed=False)
    print(f'\nValores GERAL:\n{valores_gerais_pond}')
    percentual_geral = valores_gerais_pond.div(valores_gerais_pond.sum()).sort_index()
    print(f'\PERCENTUAL GERAL:\n{percentual_geral}')

    if 'var_agrupada' in df.columns:
        aux_tabelas_pond = pd.concat(aux_tabelas_pond, axis=1)
        aux_tabelas_sem_pond = pd.concat(aux_tabelas_sem_pond, axis=1)

        # Percentual para os valores gerais da variável agrupada
        valores_gerais_aux = pd.pivot_table(df, values=Var_Pond, index='var_agrupada', aggfunc='sum')
        percentual_geral_aux = valores_gerais_aux.div(valores_gerais_aux.sum()).sort_index()
        tabela_geral = pd.concat([tabela_geral, aux_tabelas_pond], axis=0)
        percentual_geral = pd.concat([percentual_geral, percentual_geral_aux], axis=0)
        tabela_geral = pd.concat([percentual_geral, tabela_geral], axis=1)
    else:
        tabela_geral = pd.concat([percentual_geral, tabela_geral], axis=1)

    # Multiplicando cada linha pelo seu índice+1
    if TipoTabela == 'NPS':
        # Gerar o NPS
        nps = tabela_geral.loc['Promotor'] - tabela_geral.loc['Detrator']
        tabela_geral.loc['NPS'] = nps
        # Gerar as médias
        media_tabela = tabelas_pond_freq_abs.copy()
        for i in range(len(tabelas_pond_freq_abs)):
            media_tabela.iloc[i] = tabelas_pond_freq_abs.iloc[i] * (i + 1)
        media_tabela = media_tabela.sum().div(tabelas_pond_freq_abs.sum())

        # Cálculo da média geral
        df_limpo = df.dropna(subset=[Var_linha])
        media_geral = sum(np.array(df_limpo[Var_linha]) * np.array(df_limpo[Var_Pond])) / sum(np.array(df_limpo[Var_Pond]))
        media_geral = pd.Series(media_geral)
        media_tabela = pd.concat([media_geral, media_tabela], axis=0)
        media_tabela.index = tabela_geral.columns
        tabela_geral.loc['Media'] = media_tabela

    elif (TipoTabela == 'SATISFACAO') | (TipoTabela == 'IPA_10') :
        media_tabela = tabelas_pond_freq_abs.copy()
        for i in range(len(tabelas_pond_freq_abs)):
            media_tabela.iloc[i] = tabelas_pond_freq_abs.iloc[i] * (i + 1)
        media_tabela = media_tabela.sum().div(tabelas_pond_freq_abs.sum())

        # Cálculo da média geral
        df_limpo = df.dropna(subset=[Var_linha])
        media_geral = sum(np.array(df_limpo[Var_linha]) * np.array(df_limpo[Var_Pond])) / sum(np.array(df_limpo[Var_Pond]))
        media_geral = pd.Series(media_geral)
        media_tabela = pd.concat([media_geral, media_tabela], axis=0)

        media_tabela.index = tabela_geral.columns
        tabela_geral.loc['Media'] = media_tabela

    else:
        tabela_geral

    tabela_geral = tabela_geral.fillna(0)
    print(f"\n#=== TABELA GERAL - VERIFICAR RESULTADO ===#\n{tabela_geral}")

    # Valores para Base Ponderada
    tabelas_pond_freq_abs = tabelas_pond_freq_abs.fillna(0)
    soma_colunas = tabelas_pond_freq_abs.sum()
    soma_colunas = pd.Series(soma_colunas)
    base_ponderada = pd.pivot_table(df, values=Var_Pond, index=Var_linha, aggfunc='sum', observed=False)
    base_ponderada = pd.Series(base_ponderada.sum())
    base_ponderada = pd.concat([base_ponderada, soma_colunas])
    # base_ponderada.index = tabela_geral.columns
    tabela_geral.loc['Base Ponderada'] = base_ponderada

    # Valores para Base Sem Ponderar
    tabelas_sem_pond = tabelas_sem_pond.fillna(0)
    soma_colunas = pd.Series(tabelas_sem_pond.sum())
    print(f'{soma_colunas}\n')
    valores_gerais = df[Var_linha].value_counts().sort_index()
    base_sem_ponderar = pd.Series(valores_gerais.sum())
    base_sem_ponderar = pd.concat([base_sem_ponderar, soma_colunas])
    print(f'{base_sem_ponderar.index}\n')
    print(f'{tabela_geral.columns}\n')
    base_sem_ponderar.index = tabela_geral.columns
    tabela_geral.loc['Base Sem Ponderar'] = base_sem_ponderar

    tabela_geral.rename(columns={tabela_geral.columns[0]: 'Geral'}, inplace=True)
    print(f'TABELA GERAL:\n{tabela_geral.iloc[:, 0:10]}\n')

C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:30: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(bd_motivo, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:37: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(banco_pivotado, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:40: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(df_unico, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:43: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(banco, values=Var_Pond, index=Var_ID, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:30: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(bd_motivo, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:37: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(banco_pivotado, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:40: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(df_unico, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:43: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(banco, values=Var_Pond, index=Var_ID, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:30: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(bd_motivo, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:37: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(banco_pivotado, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:40: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(df_unico, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:43: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(banco, values=Var_Pond, index=Var_ID, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:30: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(bd_motivo, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:37: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(banco_pivotado, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:40: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(df_unico, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:43: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(banco, values=Var_Pond, index=Var_ID, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:30: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(bd_motivo, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:37: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(banco_pivotado, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:40: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(df_unico, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:43: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(banco, values=Var_Pond, index=Var_ID, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:30: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(bd_motivo, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:37: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(banco_pivotado, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:40: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(df_unico, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:43: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(banco, values=Var_Pond, index=Var_ID, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:30: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(bd_motivo, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:37: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(banco_pivotado, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:40: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(df_unico, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:43: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(banco, values=Var_Pond, index=Var_ID, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:30: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(bd_motivo, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:37: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(banco_pivotado, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:40: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(df_unico, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:43: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(banco, values=Var_Pond, index=Var_ID, columns=col, aggfunc='sum')

tabela:
MERC_PME                                            Mercado PME
Q8
não tem cobertura / falta cobertura/falta sinal             127
tem lugares que não funciona / pouco abrangente             101
maior abrangência de cobertura/melhor sinal                 289
qualidade das ligações é ruim / ligações têm fa...           10
falta sinal para as ligações / sinal para ligaç...            8
...                                                         ...
não cumpriu com o combinado no contrato                      18
experiência negativa com a operadora                         26
oferece atendimento através de canal digital                  0
facilidade para acessar/usar o site                           6
falta comunicação para avisar sobre manutenção ...            0

[101 rows x 1 columns]
tabela:
MERC_500                                            Mercado 500+
Q8
não tem cobertura / falta cobertura/falta sinal               13
tem lugares que não funciona / pouco abrangente                9
maior abrangência de cobertura/melhor sinal                   32
qualidade das ligações é ruim / ligações têm fa...             2
falta sinal para as ligações / sinal para ligaç...             2
...                                                          ...
não cumpriu com o combinado no contrato                        0
experiência negativa com a operadora                           1
oferece atendimento através de canal digital                   0
facilidade para acessar/usar o site                            0
falta comunicação para avisar sobre manutenção ...             0

[101 rows x 1 columns]
tabela:
TIM_TOT                                             TIM
Q8
não tem cobertura / falta cobertura/falta sinal      73
tem lugares que não funciona / pouco abrangente      57
maior abrangência de cobertura/melhor sinal         103
qualidade das ligações é ruim / ligações têm fa...    6
falta sinal para as ligações / sinal para ligaç...    8
...                                                 ...
não cumpriu com o combinado no contrato               4
experiência negativa com a operadora                 15
oferece atendimento através de canal digital          0
facilidade para acessar/usar o site                   3
falta comunicação para avisar sobre manutenção ...    0

[101 rows x 1 columns]
tabela:
TIM_PME                                             TIM PME
Q8
não tem cobertura / falta cobertura/falta sinal          66
tem lugares que não funciona / pouco abrangente          52
maior abrangência de cobertura/melhor sinal              91
qualidade das ligações é ruim / ligações têm fa...        5
falta sinal para as ligações / sinal para ligaç...        6
...                                                     ...
não cumpriu com o combinado no contrato                   4
experiência negativa com a operadora                     15
oferece atendimento através de canal digital              0
facilidade para acessar/usar o site                       3
falta comunicação para avisar sobre manutenção ...        0

[101 rows x 1 columns]
tabela:
TIM_500                                             TIM 500+
Q8
não tem cobertura / falta cobertura/falta sinal            7
tem lugares que não funciona / pouco abrangente            5
maior abrangência de cobertura/melhor sinal               12
qualidade das ligações é ruim / ligações têm fa...         1
falta sinal para as ligações / sinal para ligaç...         2
...                                                      ...
não cumpriu com o combinado no contrato                    0
experiência negativa com a operadora                       0
oferece atendimento através de canal digital               0
facilidade para acessar/usar o site                        0
falta comunicação para avisar sobre manutenção ...         0

[101 rows x 1 columns]
tabela:
TIM_PRIME                                           TIM Prime
Q8
não tem cobertura / falta cobertura/falta sinal             8
tem lugares que não funciona / pouco abrangente             6
maior abrangência de cobertura/melhor sinal                12
qualidade das ligações é ruim / ligações têm fa...          1
falta sinal para as ligações / sinal para ligaç...          0
...                                                       ...
não cumpriu com o combinado no contrato                     1
experiência negativa com a operadora                        1
oferece atendimento através de canal digital                0
facilidade para acessar/usar o site                         1
falta comunicação para avisar sobre manutenção ...          0

[101 rows x 1 columns]
tabela:
VIV_TOT                                             VIVO TOTAL
Q8
não tem cobertura / falta cobertura/falta sinal             27
tem lugares que não funciona / pouco abrangente             23
maior abrangência de cobertura/melhor sinal                142
qualidade das ligações é ruim / ligações têm fa...           5
falta sinal para as ligações / sinal para ligaç...           0
...                                                        ...
não cumpriu com o combinado no contrato                     10
experiência negativa com a operadora                         9
oferece atendimento através de canal digital                 0
facilidade para acessar/usar o site                          2
falta comunicação para avisar sobre manutenção ...           0

[101 rows x 1 columns]
tabela:
VIV_PME                                             VIVO PME
Q8
não tem cobertura / falta cobertura/falta sinal           27
tem lugares que não funciona / pouco abrangente           21
maior abrangência de cobertura/melhor sinal              125
qualidade das ligações é ruim / ligações têm fa...         4
falta sinal para as ligações / sinal para ligaç...         0
...                                                      ...
não cumpriu com o combinado no contrato                   10
experiência negativa com a operadora                       8
oferece atendimento através de canal digital               0
facilidade para acessar/usar o site                        2
falta comunicação para avisar sobre manutenção ...         0

[101 rows x 1 columns]
tabela:
VIV_500                                             VIVO 500+
Q8
não tem cobertura / falta cobertura/falta sinal             0
tem lugares que não funciona / pouco abrangente             2
maior abrangência de cobertura/melhor sinal                17
qualidade das ligações é ruim / ligações têm fa...          1
falta sinal para as ligações / sinal para ligaç...          0
...                                                       ...
não cumpriu com o combinado no contrato                     0
experiência negativa com a operadora                        1
oferece atendimento através de canal digital                0
facilidade para acessar/usar o site                         0
falta comunicação para avisar sobre manutenção ...          0

[101 rows x 1 columns]
tabela:
CLA_TOT                                             CLARO TOTAL
Q8
não tem cobertura / falta cobertura/falta sinal              40
tem lugares que não funciona / pouco abrangente              30
maior abrangência de cobertura/melhor sinal                  76
qualidade das ligações é ruim / ligações têm fa...            1
falta sinal para as ligações / sinal para ligaç...            2
...                                                         ...
não cumpriu com o combinado no contrato                       4
experiência negativa com a operadora                          3
oferece atendimento através de canal digital                  0
facilidade para acessar/usar o site                           1
falta comunicação para avisar sobre manutenção ...            0

[101 rows x 1 columns]
tabela:
CLA_PME                                             CLARO PME
Q8
não tem cobertura / falta cobertura/falta sinal            34
tem lugares que não funciona / pouco abrangente            28
maior abrangência de cobertura/melhor sinal                73
qualidade das ligações é ruim / ligações têm fa...          1
falta sinal para as ligações / sinal para ligaç...          2
...                                                       ...
não cumpriu com o combinado no contrato                     4
experiência negativa com a operadora                        3
oferece atendimento através de canal digital                0
facilidade para acessar/usar o site                         1
falta comunicação para avisar sobre manutenção ...          0

[101 rows x 1 columns]
tabela:
CLA_500                                             CLARO 500+
Q8
não tem cobertura / falta cobertura/falta sinal              6
tem lugares que não funciona / pouco abrangente              2
maior abrangência de cobertura/melhor sinal                  3
qualidade das ligações é ruim / ligações têm fa...           0
falta sinal para as ligações / sinal para ligaç...           0
...                                                        ...
não cumpriu com o combinado no contrato                      0
experiência negativa com a operadora                         0
oferece atendimento através de canal digital                 0
facilidade para acessar/usar o site                          0
falta comunicação para avisar sobre manutenção ...           0

[101 rows x 1 columns]
                                                    Mercado PME  Mercado 500+  \
Q8
não tem cobertura / falta cobertura/falta sinal        0.053262      0.056043
tem lugares que não funciona / pouco abrangente        0.045090      0.039248
maior abrangência de cobertura/melhor sinal            0.173497      0.208709
qualidade das ligações é ruim / ligações têm fa...     0.006799      0.005188
falta sinal para as ligações / sinal para ligaç...     0.004984      0.004853
...                                                         ...           ...
não cumpriu com o combinado no contrato                0.010329      0.005394
experiência negativa com a operadora                   0.015924      0.005394
oferece atendimento através de canal digital           0.000345      0.000000
facilidade para acessar/usar o site                    0.003967      0.000000
falta comunicação para avisar sobre manutenção ...     0.000367      0.000000

                                                         TIM   TIM PME  \
Q8
não tem cobertura / falta cobertura/falta sinal     0.094851  0.091047
tem lugares que não funciona / pouco abrangente     0.079062  0.077313
maior abrangência de cobertura/melhor sinal         0.148311  0.138311
qualidade das ligações é ruim / ligações têm fa...  0.009107  0.007735
falta sinal para as ligações / sinal para ligaç...  0.011594  0.009520
...                                                      ...       ...
não cumpriu com o combinado no contrato             0.004159  0.005249
experiência negativa com a operadora                0.017662  0.022294
oferece atendimento através de canal digital        0.000000  0.000000
facilidade para acessar/usar o site                 0.002900  0.003660
falta comunicação para avisar sobre manutenção ...  0.000000  0.000000

                                                    TIM 500+  TIM Prime  \
Q8
não tem cobertura / falta cobertura/falta sinal     0.109358   0.112192
tem lugares que não funciona / pouco abrangente     0.085734   0.080080
maior abrangência de cobertura/melhor sinal         0.186442   0.158775
qualidade das ligações é ruim / ligações têm fa...  0.014340   0.011483
falta sinal para as ligações / sinal para ligaç...  0.019500   0.011483
...                                                      ...        ...
não cumpriu com o combinado no contrato             0.000000   0.002565
experiência negativa com a operadora                0.000000   0.021430
oferece atendimento através de canal digital        0.000000   0.000000
facilidade para acessar/usar o site                 0.000000   0.006386
falta comunicação para avisar sobre manutenção ...  0.000000   0.000000

                                                    VIVO TOTAL  VIVO PME  \
Q8
não tem cobertura / falta cobertura/falta sinal       0.033804  0.038115
tem lugares que não funciona / pouco abrangente       0.027974  0.028934
maior abrangência de cobertura/melhor sinal           0.209379  0.199699
qualidade das ligações é ruim / ligações têm fa...    0.006241  0.006779
falta sinal para as ligações / sinal para ligaç...    0.001991  0.002376
...                                                        ...       ...
não cumpriu com o combinado no contrato               0.014333  0.014879
experiência negativa com a operadora                  0.014758  0.015385
oferece atendimento através de canal digital          0.000000  0.000000
facilidade para acessar/usar o site                   0.004539  0.005417
falta comunicação para avisar sobre manutenção ...    0.000574  0.000684

                                                    VIVO 500+  CLARO TOTAL  \
Q8
não tem cobertura / falta cobertura/falta sinal      0.011512     0.059708
tem lugares que não funciona / pouco abrangente      0.023013     0.047150
maior abrangência de cobertura/melhor sinal          0.259435     0.146664
qualidade das ligações é ruim / ligações têm fa...   0.003455     0.004868
falta sinal para as ligações / sinal para ligaç...   0.000000     0.005406
...                                                       ...          ...
não cumpriu com o combinado no contrato              0.011512     0.003949
experiência negativa com a operadora                 0.011512     0.009459
oferece atendimento através de canal digital         0.000000     0.001089
facilidade para acessar/usar o site                  0.000000     0.000931
falta comunicação para avisar sobre manutenção ...   0.000000     0.000000

                                                    CLARO PME  CLARO 500+
Q8
não tem cobertura / falta cobertura/falta sinal      0.053990    0.082917
tem lugares que não funciona / pouco abrangente      0.052552    0.025224
maior abrangência de cobertura/melhor sinal          0.147266    0.144218
qualidade das ligações é ruim / ligações têm fa...   0.006067    0.000000
falta sinal para as ligações / sinal para ligaç...   0.006738    0.000000
...                                                       ...         ...
não cumpriu com o combinado no contrato              0.004922    0.000000
experiência negativa com a operadora                 0.011790    0.000000
oferece atendimento através de canal digital         0.001357    0.000000
facilidade para acessar/usar o site                  0.001160    0.000000
falta comunicação para avisar sobre manutenção ...   0.000000    0.000000

[101 rows x 12 columns]


percentual_geral:
                                                        POND
Q8
não tem cobertura / falta cobertura/falta sinal     0.053766
tem lugares que não funciona / pouco abrangente     0.044031
maior abrangência de cobertura/melhor sinal         0.179877
qualidade das ligações é ruim / ligações têm fa...  0.006507
falta sinal para as ligações / sinal para ligaç...  0.004960
...                                                      ...
não cumpriu com o combinado no contrato             0.009435
experiência negativa com a operadora                0.014016
oferece atendimento através de canal digital        0.000282
facilidade para acessar/usar o site                 0.003248
falta comunicação para avisar sobre manutenção ...  0.000300

[101 rows x 1 columns]

soma de percentual_geral:	POND    1.645686
dtype: float64
                                                        POND  Mercado PME  \
Q8
não tem cobertura / falta cobertura/falta sinal     0.053766     0.053262
tem lugares que não funciona / pouco abrangente     0.044031     0.045090
maior abrangência de cobertura/melhor sinal         0.179877     0.173497
qualidade das ligações é ruim / ligações têm fa...  0.006507     0.006799
falta sinal para as ligações / sinal para ligaç...  0.004960     0.004984
...                                                      ...          ...
não cumpriu com o combinado no contrato             0.009435     0.010329
experiência negativa com a operadora                0.014016     0.015924
oferece atendimento através de canal digital        0.000282     0.000345
facilidade para acessar/usar o site                 0.003248     0.003967
falta comunicação para avisar sobre manutenção ...  0.000300     0.000367

                                                    Mercado 500+       TIM  \
Q8
não tem cobertura / falta cobertura/falta sinal         0.056043  0.094851
tem lugares que não funciona / pouco abrangente         0.039248  0.079062
maior abrangência de cobertura/melhor sinal             0.208709  0.148311
qualidade das ligações é ruim / ligações têm fa...      0.005188  0.009107
falta sinal para as ligações / sinal para ligaç...      0.004853  0.011594
...                                                          ...       ...
não cumpriu com o combinado no contrato                 0.005394  0.004159
experiência negativa com a operadora                    0.005394  0.017662
oferece atendimento através de canal digital            0.000000  0.000000
facilidade para acessar/usar o site                     0.000000  0.002900
falta comunicação para avisar sobre manutenção ...      0.000000  0.000000

                                                     TIM PME  TIM 500+  \
Q8
não tem cobertura / falta cobertura/falta sinal     0.091047  0.109358
tem lugares que não funciona / pouco abrangente     0.077313  0.085734
maior abrangência de cobertura/melhor sinal         0.138311  0.186442
qualidade das ligações é ruim / ligações têm fa...  0.007735  0.014340
falta sinal para as ligações / sinal para ligaç...  0.009520  0.019500
...                                                      ...       ...
não cumpriu com o combinado no contrato             0.005249  0.000000
experiência negativa com a operadora                0.022294  0.000000
oferece atendimento através de canal digital        0.000000  0.000000
facilidade para acessar/usar o site                 0.003660  0.000000
falta comunicação para avisar sobre manutenção ...  0.000000  0.000000

                                                    TIM Prime  VIVO TOTAL  \
Q8
não tem cobertura / falta cobertura/falta sinal      0.112192    0.033804
tem lugares que não funciona / pouco abrangente      0.080080    0.027974
maior abrangência de cobertura/melhor sinal          0.158775    0.209379
qualidade das ligações é ruim / ligações têm fa...   0.011483    0.006241
falta sinal para as ligações / sinal para ligaç...   0.011483    0.001991
...                                                       ...         ...
não cumpriu com o combinado no contrato              0.002565    0.014333
experiência negativa com a operadora                 0.021430    0.014758
oferece atendimento através de canal digital         0.000000    0.000000
facilidade para acessar/usar o site                  0.006386    0.004539
falta comunicação para avisar sobre manutenção ...   0.000000    0.000574

                                                    VIVO PME  VIVO 500+  \
Q8
não tem cobertura / falta cobertura/falta sinal     0.038115   0.011512
tem lugares que não funciona / pouco abrangente     0.028934   0.023013
maior abrangência de cobertura/melhor sinal         0.199699   0.259435
qualidade das ligações é ruim / ligações têm fa...  0.006779   0.003455
falta sinal para as ligações / sinal para ligaç...  0.002376   0.000000
...                                                      ...        ...
não cumpriu com o combinado no contrato             0.014879   0.011512
experiência negativa com a operadora                0.015385   0.011512
oferece atendimento através de canal digital        0.000000   0.000000
facilidade para acessar/usar o site                 0.005417   0.000000
falta comunicação para avisar sobre manutenção ...  0.000684   0.000000


C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:30: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(bd_motivo, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:37: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(banco_pivotado, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:40: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(df_unico, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:43: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(banco, values=Var_Pond, index=Var_ID, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:30: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(bd_motivo, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:37: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(banco_pivotado, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:40: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(df_unico, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:43: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(banco, values=Var_Pond, index=Var_ID, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:30: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(bd_motivo, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:37: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(banco_pivotado, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:40: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(df_unico, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:43: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(banco, values=Var_Pond, index=Var_ID, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:30: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(bd_motivo, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:37: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(banco_pivotado, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:40: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(df_unico, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:43: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  tabela = pd.pivot_table(banco, values=Var_Pond, index=Var_ID, columns=col, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:76: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  valores_gerais = pd.pivot_table(bd_motivo, values=Var_Pond, index=Var_linha, aggfunc='sum')
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:82: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  percentual_geral = valores_gerais.div(base_ponderada[0]).sort_index()
C:\Users\rayner.santos\AppData\Local\Temp\ipykernel_38212\1496861293.py:114: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  base_ponderada_respostas = pd.pivot_table(banco_pivotado, values=Var_Pond, index=Var_linha, aggfunc='sum')

In [23]:
Cabecalho = Cabecalho.split(sep=',')
print(f'Cabeçalho:\n{Cabecalho}')
header_above = []
print(f'\ntabela_geral.columns:\n{tabela_geral.columns}')
for col in tabela_geral.columns:
    valor = col.split(sep=' - ')[0]
    print(f'valor: {valor}')
    header_above.append(valor)
print(f'\nheader_above:\n{header_above}')

col_series = []
for i, valor in enumerate(Cabecalho):
    # col_names = df[Colunas[i]][pd.notna(df[Colunas[i]])].unique()
    col_names = dict_ord_labels[Colunas[i]]
    print(f'\ncol_names:\n{col_names}')
    for col in col_names:
        col_series.append((Titulo, valor, col))

header = [(Titulo, '', 'GERAL')]
print(f'\ncol_series:\n{col_series}')
header = header + col_series
print(f'\nheader:\n{header}')
print(f'\ntamanho header:\t{len(header)}')
    
header = pd.MultiIndex.from_tuples(header)
print(f'\ntabela_geral.columns:\n{tabela_geral.columns}')
print(f'\ntamanho tabela_geral.columns:\t{len(tabela_geral.columns)}')
tabela_geral.columns = header
tabela_geral
print(f'\n\n #===== TABELA GERAL FINAL =====#\n{tabela_geral}\n')
print(f'#===================================================================================#\n')

Cabeçalho:
['Mercado PME', ' Mercado 500+', ' TIM', ' TIM PME', ' TIM 500+', ' TIM Prime', ' VIVO', ' VIVO PME', ' VIVO 500+', ' CLARO', ' CLARO PME', ' CLARO 500+']

tabela_geral.columns:
Index(['Geral', 'Mercado PME', 'Mercado 500+', 'TIM', 'TIM PME', 'TIM 500+',
       'TIM Prime', 'VIVO TOTAL', 'VIVO PME', 'VIVO 500+', 'CLARO TOTAL',
       'CLARO PME', 'CLARO 500+'],
      dtype='object')
valor: Geral
valor: Mercado PME
valor: Mercado 500+
valor: TIM
valor: TIM PME
valor: TIM 500+
valor: TIM Prime
valor: VIVO TOTAL
valor: VIVO PME
valor: VIVO 500+
valor: CLARO TOTAL
valor: CLARO PME
valor: CLARO 500+

header_above:
['Geral', 'Mercado PME', 'Mercado 500+', 'TIM', 'TIM PME', 'TIM 500+', 'TIM Prime', 'VIVO TOTAL', 'VIVO PME', 'VIVO 500+', 'CLARO TOTAL', 'CLARO PME', 'CLARO 500+']

col_names:
['Mercado PME']

col_names:
['Mercado 500+']

col_names:
['TIM']

col_names:
['TIM PME']

col_names:
['TIM 500+']

col_names:
['TIM Prime']

col_names:
['VIVO TOTAL']

col_names:
['VIVO PME']

col_names:
['VIVO 500+']

col_names:
['CLARO TOTAL']

col_names:
['CLARO PME']

col_names:
['CLARO 500+']

col_series:
[('8. (SATISFAÇÃO 2021) Por que deu esta nota de recomendação para a _______? (ESPONTÂNEA - RM)', 'Mercado PME', 'Mercado PME'), ('8. (SATISFAÇÃO 2021) Por que deu esta nota de recomendação para a _______? (ESPONTÂNEA - RM)', ' Mercado 500+', 'Mercado 500+'), ('8. (SATISFAÇÃO 2021) Por que deu esta nota de recomendação para a _______? (ESPONTÂNEA - RM)', ' TIM', 'TIM'), ('8. (SATISFAÇÃO 2021) Por que deu esta nota de recomendação para a _______? (ESPONTÂNEA - RM)', ' TIM PME', 'TIM PME'), ('8. (SATISFAÇÃO 2021) Por que deu esta nota de recomendação para a _______? (ESPONTÂNEA - RM)', ' TIM 500+', 'TIM 500+'), ('8. (SATISFAÇÃO 2021) Por que deu esta nota de recomendação para a _______? (ESPONTÂNEA - RM)', ' TIM Prime', 'TIM Prime'), ('8. (SATISFAÇÃO 2021) Por que deu esta nota de recomendação para a _______? (ESPONTÂNEA - RM)', ' VIVO', 'VIVO TOTAL'), ('8. (SATISFAÇÃO 2021) Por que deu esta nota de recomendação para a _______? (ESPONTÂNEA - RM)', ' VIVO PME', 'VIVO PME'), ('8. (SATISFAÇÃO 2021) Por que deu esta nota de recomendação para a _______? (ESPONTÂNEA - RM)', ' VIVO 500+', 'VIVO 500+'), ('8. (SATISFAÇÃO 2021) Por que deu esta nota de recomendação para a _______? (ESPONTÂNEA - RM)', ' CLARO', 'CLARO TOTAL'), ('8. (SATISFAÇÃO 2021) Por que deu esta nota de recomendação para a _______? (ESPONTÂNEA - RM)', ' CLARO PME', 'CLARO PME'), ('8. (SATISFAÇÃO 2021) Por que deu esta nota de recomendação para a _______? (ESPONTÂNEA - RM)', ' CLARO 500+', 'CLARO 500+')]

header:
[('8. (SATISFAÇÃO 2021) Por que deu esta nota de recomendação para a _______? (ESPONTÂNEA - RM)', '', 'GERAL'), ('8. (SATISFAÇÃO 2021) Por que deu esta nota de recomendação para a _______? (ESPONTÂNEA - RM)', 'Mercado PME', 'Mercado PME'), ('8. (SATISFAÇÃO 2021) Por que deu esta nota de recomendação para a _______? (ESPONTÂNEA - RM)', ' Mercado 500+', 'Mercado 500+'), ('8. (SATISFAÇÃO 2021) Por que deu esta nota de recomendação para a _______? (ESPONTÂNEA - RM)', ' TIM', 'TIM'), ('8. (SATISFAÇÃO 2021) Por que deu esta nota de recomendação para a _______? (ESPONTÂNEA - RM)', ' TIM PME', 'TIM PME'), ('8. (SATISFAÇÃO 2021) Por que deu esta nota de recomendação para a _______? (ESPONTÂNEA - RM)', ' TIM 500+', 'TIM 500+'), ('8. (SATISFAÇÃO 2021) Por que deu esta nota de recomendação para a _______? (ESPONTÂNEA - RM)', ' TIM Prime', 'TIM Prime'), ('8. (SATISFAÇÃO 2021) Por que deu esta nota de recomendação para a _______? (ESPONTÂNEA - RM)', ' VIVO', 'VIVO TOTAL'), ('8. (SATISFAÇÃO 2021) Por que deu esta nota de recomendação para a _______? (ESPONTÂNEA - RM)', ' VIVO PME', 'VIVO PME'), ('8. (SATISFAÇÃO 2021) Por que deu esta nota de recomendação para a _______? (ESPONTÂNEA - RM)', ' VIVO 500+', 'VIVO 500+'), ('8. (SATISFAÇÃO 2021) Por que deu esta nota de recomendação para a _______? (ESPONTÂNEA - RM)', ' CLARO', 'CLARO TOTAL'), ('8. (SATISFAÇÃO 2021) Por que deu esta nota de recomendação para a _______? (ESPONTÂNEA - RM)', ' CLARO PME', 'CLARO PME'), ('8. (SATISFAÇÃO 2021) Por que deu esta nota de recomendação para a _______? (ESPONTÂNEA - RM)', ' CLARO 500+', 'CLARO 500+')]

tamanho header:	13

tabela_geral.columns:
Index(['Geral', 'Mercado PME', 'Mercado 500+', 'TIM', 'TIM PME', 'TIM 500+',
       'TIM Prime', 'VIVO TOTAL', 'VIVO PME', 'VIVO 500+', 'CLARO TOTAL',
       'CLARO PME', 'CLARO 500+'],
      dtype='object')

tamanho tabela_geral.columns:	13


 #===== TABELA GERAL FINAL =====#
                                                   8. (SATISFAÇÃO 2021) Por que deu esta nota de recomendação para a _______? (ESPONTÂNEA - RM)  \

                                                                                                                                          GERAL
Q8
não tem cobertura / falta cobertura/falta sinal                                              0.053766
tem lugares que não funciona / pouco abrangente                                              0.044031
maior abrangência de cobertura/melhor sinal                                                  0.179877
qualidade das ligações é ruim / ligações têm fa...                                           0.006507
falta sinal para as ligações / sinal para ligaç...                                           0.004960
...                                                                                               ...
facilidade para acessar/usar o site                                                          0.003248
falta comunicação para avisar sobre manutenção ...                                           0.000300
Base Ponderada                                                                            2892.356468
Base Sem Ponderar                                                                         2886.000000
Índice de Multiplicidade                                                                     1.657685

                                                                               \
                                                    Mercado PME  Mercado 500+
                                                    Mercado PME  Mercado 500+
Q8
não tem cobertura / falta cobertura/falta sinal        0.053262      0.056043
tem lugares que não funciona / pouco abrangente        0.045090      0.039248
maior abrangência de cobertura/melhor sinal            0.173497      0.208709
qualidade das ligações é ruim / ligações têm fa...     0.006799      0.005188
falta sinal para as ligações / sinal para ligaç...     0.004984      0.004853
...                                                         ...           ...
facilidade para acessar/usar o site                    0.003967      0.000000
falta comunicação para avisar sobre manutenção ...     0.000367      0.000000
Base Ponderada                                      2368.257562    524.098906
Base Sem Ponderar                                   2608.000000    278.000000
Índice de Multiplicidade                               1.649909      1.692931

                                                                             \
                                                            TIM     TIM PME
                                                            TIM     TIM PME
Q8
não tem cobertura / falta cobertura/falta sinal        0.094851    0.091047
tem lugares que não funciona / pouco abrangente        0.079062    0.077313
maior abrangência de cobertura/melhor sinal            0.148311    0.138311
qualidade das ligações é ruim / ligações têm fa...     0.009107    0.007735
falta sinal para as ligações / sinal para ligaç...     0.011594    0.009520
...                                                         ...         ...
facilidade para acessar/usar o site                    0.002900    0.003660
falta comunicação para avisar sobre manutenção ...     0.000000    0.000000
Base Ponderada                                       627.851630  497.412360
Base Sem Ponderar                                   1099.000000  995.000000
Índice de Multiplicidade                               1.702688    1.696037

                                                                            \
                                                      TIM 500+   TIM Prime
                                                      TIM 500+   TIM Prime
Q8
não tem cobertura / falta cobertura/falta sinal       0.109358    0.112192
tem lugares que não funciona / pouco abrangente       0.085734    0.080080
maior abrangência de cobertura/melhor sinal           0.186442    0.158775
qualidade das ligações é ruim / ligações têm fa...    0.014340    0.011483
falta sinal para as ligações / sinal para ligaç...    0.019500    0.011483
...                                                        ...         ...
facilidade para acessar/usar o site                   0.000000    0.006386
falta comunicação para avisar sobre manutenção ...    0.000000    0.000000
Base Ponderada                                      130.439270   76.205629
Base Sem Ponderar                                   104.000000  114.000000
Índice de Multiplicidade                              1.728023    1.716327

                                                                              \
                                                           VIVO     VIVO PME
                                                     VIVO TOTAL     VIVO PME
Q8
não tem cobertura / falta cobertura/falta sinal        0.033804     0.038115
tem lugares que não funciona / pouco abrangente        0.027974     0.028934
maior abrangência de cobertura/melhor sinal            0.209379     0.199699
qualidade das ligações é ruim / ligações têm fa...     0.006241     0.006779
falta sinal para as ligações / sinal para ligaç...     0.001991     0.002376
...                                                         ...          ...
facilidade para acessar/usar o site                    0.004539     0.005417
falta comunicação para avisar sobre manutenção ...     0.000574     0.000684
Base Ponderada                                      1515.275266  1269.723724
Base Sem Ponderar                                    955.000000   868.000000
Índice de Multiplicidade                               1.638997     1.649589

                                                                            \
                                                     VIVO 500+       CLARO
                                                     VIVO 500+ CLARO TOTAL
Q8
não tem cobertura / falta cobertura/falta sinal       0.011512    0.059708
tem lugares que não funciona / pouco abrangente       0.023013    0.047150
maior abrangência de cobertura/melhor sinal           0.259435    0.146664
qualidade das ligações é ruim / ligações têm fa...    0.003455    0.004868
falta sinal para as ligações / sinal para ligaç...    0.000000    0.005406
...                                                        ...         ...
facilidade para acessar/usar o site                   0.000000    0.000931
falta comunicação para avisar sobre manutenção ...    0.000000    0.000000
Base Ponderada                                      245.551542  749.229572
Base Sem Ponderar                                    87.000000  832.000000
Índice de Multiplicidade                              1.585504    1.657455


                                                     CLARO PME  CLARO 500+
                                                     CLARO PME  CLARO 500+
Q8
não tem cobertura / falta cobertura/falta sinal       0.053990    0.082917
tem lugares que não funciona / pouco abrangente       0.052552    0.025224
maior abrangência de cobertura/melhor sinal           0.147266    0.144218
qualidade das ligações é ruim / ligações têm fa...    0.006067    0.000000
falta sinal para as ligações / sinal para ligaç...    0.006738    0.000000
...                                                        ...         ...
facilidade para acessar/usar o site                   0.001160    0.000000
falta comunicação para avisar sobre manutenção ...    0.000000    0.000000
Base Ponderada                                      601.121478  148.108094
Base Sem Ponderar                                   745.000000   87.000000
Índice de Multiplicidade                              1.613641    1.845637

[104 rows x 13 columns]

#===================================================================================#

In [24]:
display(tabela_geral)

                                                   8. (SATISFAÇÃO 2021) Por que deu esta nota de recomendação para a _______? (ESPONTÂNEA - RM)  \

                                                                                                                                          GERAL
Q8
não tem cobertura / falta cobertura/falta sinal                                              0.053766
tem lugares que não funciona / pouco abrangente                                              0.044031
maior abrangência de cobertura/melhor sinal                                                  0.179877
qualidade das ligações é ruim / ligações têm fa...                                           0.006507
falta sinal para as ligações / sinal para ligaç...                                           0.004960
...                                                                                               ...
facilidade para acessar/usar o site                                                          0.003248
falta comunicação para avisar sobre manutenção ...                                           0.000300
Base Ponderada                                                                            2892.356468
Base Sem Ponderar                                                                         2886.000000
Índice de Multiplicidade                                                                     1.657685

                                                                               \
                                                    Mercado PME  Mercado 500+
                                                    Mercado PME  Mercado 500+
Q8
não tem cobertura / falta cobertura/falta sinal        0.053262      0.056043
tem lugares que não funciona / pouco abrangente        0.045090      0.039248
maior abrangência de cobertura/melhor sinal            0.173497      0.208709
qualidade das ligações é ruim / ligações têm fa...     0.006799      0.005188
falta sinal para as ligações / sinal para ligaç...     0.004984      0.004853
...                                                         ...           ...
facilidade para acessar/usar o site                    0.003967      0.000000
falta comunicação para avisar sobre manutenção ...     0.000367      0.000000
Base Ponderada                                      2368.257562    524.098906
Base Sem Ponderar                                   2608.000000    278.000000
Índice de Multiplicidade                               1.649909      1.692931

                                                                             \
                                                            TIM     TIM PME
                                                            TIM     TIM PME
Q8
não tem cobertura / falta cobertura/falta sinal        0.094851    0.091047
tem lugares que não funciona / pouco abrangente        0.079062    0.077313
maior abrangência de cobertura/melhor sinal            0.148311    0.138311
qualidade das ligações é ruim / ligações têm fa...     0.009107    0.007735
falta sinal para as ligações / sinal para ligaç...     0.011594    0.009520
...                                                         ...         ...
facilidade para acessar/usar o site                    0.002900    0.003660
falta comunicação para avisar sobre manutenção ...     0.000000    0.000000
Base Ponderada                                       627.851630  497.412360
Base Sem Ponderar                                   1099.000000  995.000000
Índice de Multiplicidade                               1.702688    1.696037

                                                                            \
                                                      TIM 500+   TIM Prime
                                                      TIM 500+   TIM Prime
Q8
não tem cobertura / falta cobertura/falta sinal       0.109358    0.112192
tem lugares que não funciona / pouco abrangente       0.085734    0.080080
maior abrangência de cobertura/melhor sinal           0.186442    0.158775
qualidade das ligações é ruim / ligações têm fa...    0.014340    0.011483
falta sinal para as ligações / sinal para ligaç...    0.019500    0.011483
...                                                        ...         ...
facilidade para acessar/usar o site                   0.000000    0.006386
falta comunicação para avisar sobre manutenção ...    0.000000    0.000000
Base Ponderada                                      130.439270   76.205629
Base Sem Ponderar                                   104.000000  114.000000
Índice de Multiplicidade                              1.728023    1.716327

                                                                              \
                                                           VIVO     VIVO PME
                                                     VIVO TOTAL     VIVO PME
Q8
não tem cobertura / falta cobertura/falta sinal        0.033804     0.038115
tem lugares que não funciona / pouco abrangente        0.027974     0.028934
maior abrangência de cobertura/melhor sinal            0.209379     0.199699
qualidade das ligações é ruim / ligações têm fa...     0.006241     0.006779
falta sinal para as ligações / sinal para ligaç...     0.001991     0.002376
...                                                         ...          ...
facilidade para acessar/usar o site                    0.004539     0.005417
falta comunicação para avisar sobre manutenção ...     0.000574     0.000684
Base Ponderada                                      1515.275266  1269.723724
Base Sem Ponderar                                    955.000000   868.000000
Índice de Multiplicidade                               1.638997     1.649589

                                                                            \
                                                     VIVO 500+       CLARO
                                                     VIVO 500+ CLARO TOTAL
Q8
não tem cobertura / falta cobertura/falta sinal       0.011512    0.059708
tem lugares que não funciona / pouco abrangente       0.023013    0.047150
maior abrangência de cobertura/melhor sinal           0.259435    0.146664
qualidade das ligações é ruim / ligações têm fa...    0.003455    0.004868
falta sinal para as ligações / sinal para ligaç...    0.000000    0.005406
...                                                        ...         ...
facilidade para acessar/usar o site                   0.000000    0.000931
falta comunicação para avisar sobre manutenção ...    0.000000    0.000000
Base Ponderada                                      245.551542  749.229572
Base Sem Ponderar                                    87.000000  832.000000
Índice de Multiplicidade                              1.585504    1.657455


                                                     CLARO PME  CLARO 500+
                                                     CLARO PME  CLARO 500+
Q8
não tem cobertura / falta cobertura/falta sinal       0.053990    0.082917
tem lugares que não funciona / pouco abrangente       0.052552    0.025224
maior abrangência de cobertura/melhor sinal           0.147266    0.144218
qualidade das ligações é ruim / ligações têm fa...    0.006067    0.000000
falta sinal para as ligações / sinal para ligaç...    0.006738    0.000000
...                                                        ...         ...
facilidade para acessar/usar o site                   0.001160    0.000000
falta comunicação para avisar sobre manutenção ...    0.000000    0.000000
Base Ponderada                                      601.121478  148.108094
Base Sem Ponderar                                   745.000000   87.000000
Índice de Multiplicidade                              1.613641    1.845637

[104 rows x 13 columns]

### <font color="greenblue">Criar a função modular</font>

In [ ]:
class processar_tabela:
    """Processamento de dados Estatístico
    Será informado os parâmetros necessários para a criação da tabela processada e assim,
    iniciaremos cada método necessário dentro da classe 'processar_tabela'
    """
    def __init__(self, bd_dados: pd.DataFrame, lista_labels: pd.DataFrame, 
                 TipoTabela: str, Var_linha: str, Colunas: list, Cabecalho: str, NS_NR: str, Var_ID: str, Var_Pond: str, Titulo: str,
                 valores_BTB: str = '1, 2, 3', valores_TTB: str = '8, 9, 10', Valores_Agrup: str = 'Q8_1, Q8_2, Q8_3', Fecha_100: str = 'SIM'):
        self.bd_dados = bd_dados
        self.lista_labels = lista_labels
        self.TipoTabela = TipoTabela
        self.Var_linha = Var_linha
        self.Colunas = Colunas
        self.Cabecalho = Cabecalho
        self.NS_NR = NS_NR
        self.Var_ID = Var_ID
        self.Var_Pond = Var_Pond
        self.Titulo = Titulo
        self.valores_BTB = valores_BTB
        self.valores_TTB = valores_TTB
        self.Valores_Agrup = Valores_Agrup
        self.Fecha_100 = Fecha_100

        df = self.bd_dados.copy()
        dict_ord_labels = {}

        for col in Colunas:
            if col not in df.columns:
                raise ValueError(f"Coluna '{col}' não encontrada no DataFrame.")        
            else:
                df[col], ord_labels = ordenar_labels(df=bd_dados, lista_labels=lista_labels, Variavel=col)
                dict_ord_labels[col] = ord_labels
        
        return df
    

    def tratamento_var_linha(self, df):
        # Etapas de ETL para as colunas principais (nível das linhas) a serem utilizadas
        # Transformação na variável para a linha da tabela
        if TipoTabela == 'SIMPLES':
            if NS_NR == 'NAO':
                df[Var_linha] = df[Var_linha].replace('NS/NR', np.nan)
                df[Var_linha], ord_labels = ordenar_labels(df=self.bd_dados, lista_labels=lista_labels, Variavel=Var_linha)
            else:
                df[Var_linha], ord_labels = ordenar_labels(df=self.bd_dados, lista_labels=lista_labels, Variavel=Var_linha)

            return df
            
        elif (TipoTabela == 'NPS') | (TipoTabela == 'IPA_10'):
            if NS_NR == 'NAO':
                df[Var_linha] = df[Var_linha].replace('NS/NR', np.nan)
                df[Var_linha] = df[Var_linha].replace('ns/nr', np.nan)
                df[Var_linha] = df[Var_linha].replace('90', np.nan)
                df[Var_linha] = df[Var_linha].replace('99', np.nan)
                df[Var_linha] = df[Var_linha].replace('999', np.nan)
                df[Var_linha] = df[Var_linha].replace('9999', np.nan)
                df[Var_linha] = df[Var_linha].replace(90, np.nan)
                df[Var_linha] = df[Var_linha].replace(99, np.nan)
                df[Var_linha] = df[Var_linha].replace(999, np.nan)
                df[Var_linha] = df[Var_linha].replace(9999, np.nan)
                df[Var_linha] = pd.to_numeric(df[Var_linha], errors='coerce', downcast='integer')
                df[Var_linha] = pd.Categorical(df[Var_linha], categories=ordenar_valores(df[Var_linha]), ordered=True)

                if TipoTabela == 'NPS':
                    df['var_agrupada'] = df[Var_linha].apply(classificar_nps)

                elif TipoTabela == 'IPA_10':
                    valores_BTB = [int(v) for v in valores_BTB.split(sep=', ')]
                    valores_TTB = [int(v) for v in valores_TTB.split(sep=', ')]
                    df['var_agrupada'] = funcao_agrupamento(df[Var_linha], valores_BTB, valores_TTB)

            else:
                df[Var_linha] = pd.Categorical(df[Var_linha], categories=ordenar_valores(df[Var_linha]), ordered=True)

                if TipoTabela == 'NPS':
                    df['var_agrupada'] = df[Var_linha].apply(classificar_nps)

                elif TipoTabela == 'IPA_10':
                    valores_BTB = [int(v) for v in valores_BTB.split(sep=', ')]
                    valores_TTB = [int(v) for v in valores_TTB.split(sep=', ')]
                    df['var_agrupada'] = funcao_agrupamento(df[Var_linha], valores_BTB, valores_TTB)

            return df

        elif TipoTabela == 'IPA_5':
            if NS_NR == 'NAO':
                df[Var_linha] = df[Var_linha].replace('NS/NR', np.nan)
                df[Var_linha] = df[Var_linha].replace('90', np.nan)
                df[Var_linha] = df[Var_linha].replace('99', np.nan)
                df[Var_linha] = df[Var_linha].replace('999', np.nan)
                df[Var_linha] = df[Var_linha].replace(90, np.nan)
                df[Var_linha] = df[Var_linha].replace(99, np.nan)
                df[Var_linha] = df[Var_linha].replace(999, np.nan)
                valores_BTB = [int(v) for v in valores_BTB.split(sep=', ')]
                valores_TTB = [int(v) for v in valores_TTB.split(sep=', ')]
                df['var_agrupada'] = funcao_agrupamento(df[Var_linha], valores_BTB, valores_TTB)
                df['var_agrupada'] = pd.Categorical(df['var_agrupada'], categories=['BTB', 'Neutro', 'TTB'], ordered=True)
                df[Var_linha], ord_labels = ordenar_labels(df=self.bd_dados, lista_labels=lista_labels, Variavel=Var_linha)
            else:
                valores_BTB = [int(v) for v in valores_BTB.split(sep=', ')]
                valores_TTB = [int(v) for v in valores_TTB.split(sep=', ')]
                df['var_agrupada'] = funcao_agrupamento(df[Var_linha], valores_BTB, valores_TTB)
                df['var_agrupada'] = pd.Categorical(df['var_agrupada'], categories=['BTB', 'Neutro', 'TTB'], ordered=True)
                df[Var_linha], ord_labels = ordenar_labels(df=self.bd_dados, lista_labels=lista_labels, Variavel=Var_linha)

            return df

        elif TipoTabela == 'MULTIPLA':
            if NS_NR == 'NAO':
                df_NS_NR = df.copy()
                
                Valores_Agrup = Valores_Agrup.split(sep=', ')

                bd_motivo = pd.melt(df, 
                            id_vars=Colunas + [Var_Pond] + [Var_ID],
                            value_vars=Valores_Agrup, 
                            var_name='Valores', 
                            value_name=Var_linha)
                bd_motivo[Var_linha] = bd_motivo[Var_linha].replace('90', np.nan)
                bd_motivo[Var_linha] = bd_motivo[Var_linha].replace('99', np.nan)
                bd_motivo[Var_linha] = bd_motivo[Var_linha].replace('999', np.nan)
                bd_motivo[Var_linha] = bd_motivo[Var_linha].replace('9999', np.nan)
                bd_motivo[Var_linha] = bd_motivo[Var_linha].replace(90, np.nan)
                bd_motivo[Var_linha] = bd_motivo[Var_linha].replace(99, np.nan)
                bd_motivo[Var_linha] = bd_motivo[Var_linha].replace(999, np.nan)
                bd_motivo[Var_linha] = bd_motivo[Var_linha].replace(9999, np.nan)
                bd_motivo = bd_motivo.dropna(subset=[Var_linha])
                print(f'\nbd_motivo em formato de código:\n{bd_motivo}')
                bd_motivo = ordenar_labels_multipla(df=bd_motivo, lista_labels=lista_labels, Variavel=Var_linha, Var_Valores_Agrup=Valores_Agrup[0])
                bd_motivo[Var_linha] = bd_motivo[Var_linha].replace('NS/NR', np.nan)

                df_limpo = bd_motivo.dropna(subset=[Var_linha])
                print(f'bd_motivo finalizado:\n{df_limpo}')
                df_unico = df_limpo.drop_duplicates(subset=Var_ID, keep='first')
                        
                # Bancos para realizar o cálculo do Índice de Multiplicidade (incluir NS/NR)
                bd_motivo_NS_NR = pd.melt(df_NS_NR, 
                            id_vars=Colunas + [Var_Pond] + [Var_ID],
                            value_vars=Valores_Agrup, 
                            var_name='Valores', 
                            value_name=Var_linha)
                bd_motivo_NS_NR = bd_motivo_NS_NR.dropna(subset=[Var_linha])
                bd_motivo_NS_NR = ordenar_labels_multipla(df=bd_motivo_NS_NR, lista_labels=lista_labels, Variavel=Var_linha, 
                                                        Var_Valores_Agrup=Valores_Agrup[0])
                
                df_NS_NR_limpo = bd_motivo_NS_NR.dropna(subset=[Var_linha])
                print(f'bd_motivo_NS_NR finalizado:\n{df_limpo}')
                df_NS_NR_unico = df_NS_NR_limpo.drop_duplicates(subset=Var_ID, keep='first')  

                return df_unico, df_NS_NR_unico  
                
            else:
                Valores_Agrup = Valores_Agrup.split(sep=', ')
                bd_motivo = pd.melt(df, 
                            id_vars=Colunas + [Var_Pond] + [Var_ID],
                            value_vars=Valores_Agrup, 
                            var_name='Valores', 
                            value_name=Var_linha)
                bd_motivo = bd_motivo.dropna(subset=[Var_linha])
                bd_motivo = ordenar_labels_multipla(df=bd_motivo, lista_labels=lista_labels, Variavel=Var_linha, Var_Valores_Agrup=Valores_Agrup[0])
                
                df_limpo = bd_motivo.dropna(subset=[Var_linha])
                df_unico = df_limpo.drop_duplicates(subset=Var_ID, keep='first')    

                return bd_motivo, df_unico

In [ ]:
# FUNÇÃO PARA PROCESSAR UMA ÚNICA TABELA
def processar_tabela(bd_dados: pd.DataFrame, lista_labels: pd.DataFrame, 
                     TipoTabela: str, Var_linha: str, Colunas: list, Cabecalho: str, NS_NR: str, Var_ID: str, Var_Pond: str, Titulo: str,
                     valores_BTB: str = '1, 2, 3', valores_TTB: str = '8, 9, 10', Valores_Agrup: str = 'Q8_1, Q8_2, Q8_3', Fecha_100: str = 'SIM'):
    
    df = bd_dados.copy()
    dict_ord_labels = {}

    for col in Colunas:
        if col not in df.columns:
            raise ValueError(f"Coluna '{col}' não encontrada no DataFrame.")        
        else:
            df[col], ord_labels = ordenar_labels(df=bd_dados, lista_labels=lista_labels, Variavel=col)
            dict_ord_labels[col] = ord_labels
            print(f"\nColuna ordenada (unique): {df[col].unique()}")

    # Etapas de ETL para as colunas principais (nível das linhas) a serem utilizadas
    # Transformação na variável para a linha da tabela
    if TipoTabela == 'SIMPLES':
        if NS_NR == 'NAO':
            df[Var_linha] = df[Var_linha].replace('NS/NR', np.nan)
            df[Var_linha], ord_labels = ordenar_labels(df=bd_dados, lista_labels=lista_labels, Variavel=Var_linha)
            # df[Var_linha] = pd.Categorical(df[Var_linha], categories=df[Var_linha][pd.notna(df[Var_linha])].unique(), ordered=True)
        else:
            df[Var_linha], ord_labels = ordenar_labels(df=bd_dados, lista_labels=lista_labels, Variavel=Var_linha)
            # df[Var_linha] = pd.Categorical(df[Var_linha], categories=df[Var_linha][pd.notna(df[Var_linha])].unique(), ordered=True)
        
    elif (TipoTabela == 'NPS') | (TipoTabela == 'IPA_10'):
        if NS_NR == 'NAO':
            df[Var_linha] = df[Var_linha].replace('NS/NR', np.nan)
            df[Var_linha] = df[Var_linha].replace('ns/nr', np.nan)
            df[Var_linha] = df[Var_linha].replace('90', np.nan)
            df[Var_linha] = df[Var_linha].replace('99', np.nan)
            df[Var_linha] = df[Var_linha].replace('999', np.nan)
            df[Var_linha] = df[Var_linha].replace('9999', np.nan)
            df[Var_linha] = df[Var_linha].replace(90, np.nan)
            df[Var_linha] = df[Var_linha].replace(99, np.nan)
            df[Var_linha] = df[Var_linha].replace(999, np.nan)
            df[Var_linha] = df[Var_linha].replace(9999, np.nan)
            df[Var_linha] = pd.to_numeric(df[Var_linha], errors='coerce', downcast='integer')
            # df[Var_linha], ord_labels = ordenar_labels(df=df, lista_labels=lista_labels, Variavel=Var_linha)
            df[Var_linha] = pd.Categorical(df[Var_linha], categories=ordenar_valores(df[Var_linha]), ordered=True)

            if TipoTabela == 'NPS':
                df['var_agrupada'] = df[Var_linha].apply(classificar_nps)

            elif TipoTabela == 'IPA_10':
                valores_BTB = [int(v) for v in valores_BTB.split(sep=', ')]
                valores_TTB = [int(v) for v in valores_TTB.split(sep=', ')]
                df['var_agrupada'] = funcao_agrupamento(df[Var_linha], valores_BTB, valores_TTB)

        else:
            # df[Var_linha] = df[Var_linha].replace('90', np.nan)
            # df[Var_linha] = df[Var_linha].replace('99', np.nan)
            # df[Var_linha] = df[Var_linha].replace('999', np.nan)
            # df[Var_linha] = df[Var_linha].replace('9999', np.nan)
            # df[Var_linha], ord_labels = ordenar_labels(df=data, lista_labels=lista_labels, Variavel=Var_linha)
            df[Var_linha] = pd.Categorical(df[Var_linha], categories=ordenar_valores(df[Var_linha]), ordered=True)

            if TipoTabela == 'NPS':
                df['var_agrupada'] = df[Var_linha].apply(classificar_nps)

            elif TipoTabela == 'IPA_10':
                valores_BTB = [int(v) for v in valores_BTB.split(sep=', ')]
                valores_TTB = [int(v) for v in valores_TTB.split(sep=', ')]
                df['var_agrupada'] = funcao_agrupamento(df[Var_linha], valores_BTB, valores_TTB)

    elif TipoTabela == 'IPA_5':
        if NS_NR == 'NAO':
            df[Var_linha] = df[Var_linha].replace('NS/NR', np.nan)
            df[Var_linha] = df[Var_linha].replace('90', np.nan)
            df[Var_linha] = df[Var_linha].replace('99', np.nan)
            df[Var_linha] = df[Var_linha].replace('999', np.nan)
            df[Var_linha] = df[Var_linha].replace(90, np.nan)
            df[Var_linha] = df[Var_linha].replace(99, np.nan)
            df[Var_linha] = df[Var_linha].replace(999, np.nan)
            valores_BTB = [int(v) for v in valores_BTB.split(sep=', ')]
            valores_TTB = [int(v) for v in valores_TTB.split(sep=', ')]
            df['var_agrupada'] = funcao_agrupamento(df[Var_linha], valores_BTB, valores_TTB)
            df['var_agrupada'] = pd.Categorical(df['var_agrupada'], categories=['BTB', 'Neutro', 'TTB'], ordered=True)
            df[Var_linha], ord_labels = ordenar_labels(df=bd_dados, lista_labels=lista_labels, Variavel=Var_linha)
            # df[Var_linha] = pd.Categorical(df[Var_linha], categories=Valores_Agrup, ordered=True)
        else:
            valores_BTB = [int(v) for v in valores_BTB.split(sep=', ')]
            valores_TTB = [int(v) for v in valores_TTB.split(sep=', ')]
            df['var_agrupada'] = funcao_agrupamento(df[Var_linha], valores_BTB, valores_TTB)
            df['var_agrupada'] = pd.Categorical(df['var_agrupada'], categories=['BTB', 'Neutro', 'TTB'], ordered=True)
            df[Var_linha], ord_labels = ordenar_labels(df=bd_dados, lista_labels=lista_labels, Variavel=Var_linha)
            # df[Var_linha] = pd.Categorical(df[Var_linha], categories=Valores_Agrup, ordered=True)

    elif TipoTabela == 'MULTIPLA':
        if NS_NR == 'NAO':
            df_NS_NR = df.copy()
            
            Valores_Agrup = Valores_Agrup.split(sep=', ')
            # Converte as colunas de motivos para string, preservando NaN
            # for c in Valores_Agrup:
            #     df[c] = df[c].astype("object").where(df[c].isna(), df[c].astype(str))
            #     df_NS_NR[c] = df_NS_NR[c].astype("object").where(df_NS_NR[c].isna(), df_NS_NR[c].astype(str))

            bd_motivo = pd.melt(df, 
                        id_vars=Colunas + [Var_Pond] + [Var_ID],
                        value_vars=Valores_Agrup, 
                        var_name='Valores', 
                        value_name=Var_linha)
            bd_motivo[Var_linha] = bd_motivo[Var_linha].replace('90', np.nan)
            bd_motivo[Var_linha] = bd_motivo[Var_linha].replace('99', np.nan)
            bd_motivo[Var_linha] = bd_motivo[Var_linha].replace('999', np.nan)
            bd_motivo[Var_linha] = bd_motivo[Var_linha].replace('9999', np.nan)
            bd_motivo[Var_linha] = bd_motivo[Var_linha].replace(90, np.nan)
            bd_motivo[Var_linha] = bd_motivo[Var_linha].replace(99, np.nan)
            bd_motivo[Var_linha] = bd_motivo[Var_linha].replace(999, np.nan)
            bd_motivo[Var_linha] = bd_motivo[Var_linha].replace(9999, np.nan)
            bd_motivo = bd_motivo.dropna(subset=[Var_linha])
            print(f'\nbd_motivo em formato de código:\n{bd_motivo}')
            bd_motivo = ordenar_labels_multipla(df=bd_motivo, lista_labels=lista_labels, Variavel=Var_linha, Var_Valores_Agrup=Valores_Agrup[0])
            bd_motivo[Var_linha] = bd_motivo[Var_linha].replace('NS/NR', np.nan)
            # bd_motivo[Var_linha] = pd.Categorical(bd_motivo[Var_linha], categories=ordenar_valores(bd_motivo[Var_linha]), ordered=True)  

            df_limpo = bd_motivo.dropna(subset=[Var_linha])
            print(f'bd_motivo finalizado:\n{df_limpo}')
            df_unico = df_limpo.drop_duplicates(subset=Var_ID, keep='first')
                    
            # Bancos para realizar o cálculo do Índice de Multiplicidade (incluir NS/NR)
            bd_motivo_NS_NR = pd.melt(df_NS_NR, 
                        id_vars=Colunas + [Var_Pond] + [Var_ID],
                        value_vars=Valores_Agrup, 
                        var_name='Valores', 
                        value_name=Var_linha)
            bd_motivo_NS_NR = bd_motivo_NS_NR.dropna(subset=[Var_linha])
            bd_motivo_NS_NR = ordenar_labels_multipla(df=bd_motivo_NS_NR, lista_labels=lista_labels, Variavel=Var_linha, 
                                                    Var_Valores_Agrup=Valores_Agrup[0])
            # bd_motivo_NS_NR[Var_linha] = pd.Categorical(bd_motivo_NS_NR[Var_linha], 
            #                                     categories=ordenar_valores(bd_motivo_NS_NR[Var_linha]), ordered=True)
            
            df_NS_NR_limpo = bd_motivo_NS_NR.dropna(subset=[Var_linha])
            print(f'bd_motivo_NS_NR finalizado:\n{df_limpo}')
            df_NS_NR_unico = df_NS_NR_limpo.drop_duplicates(subset=Var_ID, keep='first')    
            
        else:
            Valores_Agrup = Valores_Agrup.split(sep=', ')
            bd_motivo = pd.melt(df, 
                        id_vars=Colunas + [Var_Pond] + [Var_ID],
                        value_vars=Valores_Agrup, 
                        var_name='Valores', 
                        value_name=Var_linha)
            bd_motivo = bd_motivo.dropna(subset=[Var_linha])
            bd_motivo = ordenar_labels_multipla(df=bd_motivo, lista_labels=lista_labels, Variavel=Var_linha, Var_Valores_Agrup=Valores_Agrup[0])
            # bd_motivo[Var_linha] = pd.Categorical(bd_motivo[Var_linha], 
            #                                     categories=ordenar_valores(bd_motivo[Var_linha]), ordered=True)
            
            df_limpo = bd_motivo.dropna(subset=[Var_linha])
            df_unico = df_limpo.drop_duplicates(subset=Var_ID, keep='first')


    #======= Criação da Tabela Geral =======#
    tabela_geral = []
    tabelas_pond = []
    tabelas_pond_freq_abs = []
    tabelas_sem_pond = []
    aux_tabelas_pond = []
    aux_tabelas_sem_pond = []

    tbl_pond_freq_abs_respondentes = []
    tbl_sem_pond_respondentes = []

    tbl_pond_freq_abs_respostas_NS_NR = []
    tbl_pond_freq_abs_respondentes_NS_NR = []

    if TipoTabela == 'MULTIPLA':
        if NS_NR == 'NAO':
            banco = df_NS_NR_unico
            banco_pivotado = bd_motivo_NS_NR
        else:
            banco = df_unico
            banco_pivotado = bd_motivo

        i = 0    
        for col in Colunas:

            # Gerar Tabelas Ponderadas de Frequência Absoluta com o banco empilhado
            tabela = pd.pivot_table(bd_motivo, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
            if Fecha_100 == 'SIM':
                tabela = tabela.div(tabela.sum())
                tabelas_pond.append(tabela)
            else:
                tabelas_pond.append(tabela)

            tabela = pd.pivot_table(banco_pivotado, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
            tbl_pond_freq_abs_respostas_NS_NR.append(tabela)

            tabela = pd.pivot_table(df_unico, values=Var_Pond, index=Var_linha, columns=col, aggfunc='sum')
            tbl_pond_freq_abs_respondentes.append(tabela)

            tabela = pd.pivot_table(banco, values=Var_Pond, index=Var_ID, columns=col, aggfunc='sum')
            tbl_pond_freq_abs_respondentes_NS_NR.append(tabela)

            tabela = pd.crosstab(df_unico[Var_linha], df_unico[col], dropna=False)
            tabela = tabela.fillna(0)
            if len(tabela) == 0:
                tabela = pd.DataFrame(0, index=df_unico[Var_linha][pd.notna(df_unico[Var_linha])].unique(), 
                                    columns=df_unico[Colunas[i-1]][pd.notna(df_unico[Colunas[i-1]])].unique())
                print(f'{df_unico[Var_linha][pd.notna(df_unico[Var_linha])].unique()}\n')
                print(f'{df_unico[Colunas[i-1]][pd.notna(df_unico[Colunas[i-1]])].unique()}\n')
            print(f'tabela:\n{tabela}')
            tbl_sem_pond_respondentes.append(tabela)
            i += 1

        tabela_geral = pd.concat(tabelas_pond, axis=1)
        tbl_pond_freq_abs_respondentes = pd.concat(tbl_pond_freq_abs_respondentes, axis=1)
        tbl_sem_pond_respondentes = pd.concat(tbl_sem_pond_respondentes, axis=1)
        tbl_pond_freq_abs_respostas_NS_NR = pd.concat(tbl_pond_freq_abs_respostas_NS_NR, axis=1)
        tbl_pond_freq_abs_respondentes_NS_NR = pd.concat(tbl_pond_freq_abs_respondentes_NS_NR, axis=1)
        
        if Fecha_100 != 'SIM':
            soma_base_ponderada = tbl_pond_freq_abs_respondentes.sum()
            tabela_geral = tabela_geral.div(soma_base_ponderada)
        
        print(f'{tabela_geral}\n')


        # Trazendo a coluna de valores gerais
        soma_colunas = tbl_pond_freq_abs_respondentes.sum()
        soma_colunas = pd.Series(soma_colunas)
        base_ponderada = pd.pivot_table(df_unico, values=Var_Pond, index=Var_ID, aggfunc='sum')
        base_ponderada = pd.Series(base_ponderada.sum())
        base_ponderada = pd.concat([base_ponderada, soma_colunas])
        valores_gerais = pd.pivot_table(bd_motivo, values=Var_Pond, index=Var_linha, aggfunc='sum')
        if Fecha_100 == 'SIM':
            percentual_geral = valores_gerais.div(valores_gerais.sum()).sort_index()
            print(f'\npercentual_geral:\n{percentual_geral}')
            print(f'\nsoma de percentual_geral:\t{percentual_geral.sum()}')
        else:
            percentual_geral = valores_gerais.div(base_ponderada[0]).sort_index()
            print(f'\npercentual_geral:\n{percentual_geral}')
            print(f'\nsoma de percentual_geral:\t{percentual_geral.sum()}')

        # tabela_geral = tabela_geral.div(base_ponderada[1:])
        tabela_geral = pd.concat([percentual_geral, tabela_geral], axis=1)
        print(f'{tabela_geral}\n')

        tabela_geral_front = tabela_geral.multiply(100)
        tabela_geral_front = tabela_geral_front.applymap(lambda x: f"{x:.1f}%".replace(".", ","))

        # Valores para Base Ponderada
        soma_colunas = tbl_pond_freq_abs_respondentes.sum()
        soma_colunas = pd.Series(soma_colunas)
        base_ponderada = pd.pivot_table(df_unico, values=Var_Pond, index=Var_ID, aggfunc='sum')
        base_ponderada = pd.Series(base_ponderada.sum())
        base_ponderada = pd.concat([base_ponderada, soma_colunas])
        tabela_geral.loc['Base Ponderada'] = base_ponderada
        tabela_geral_front.loc['Base Ponderada'] = base_ponderada.round().astype(int)

        # Valores para Base Sem Ponderar
        valores_gerais_respondentes = df_unico[Var_ID].value_counts()
        soma_colunas = pd.Series(tbl_sem_pond_respondentes.sum())
        print(f'\n{soma_colunas}\n')
        base_sem_ponderar = pd.Series(valores_gerais_respondentes.sum())
        base_sem_ponderar = pd.concat([base_sem_ponderar, soma_colunas])
        print(f'base sem ponderar:\n{base_sem_ponderar.index}\n')
        print(f'{len(base_sem_ponderar.index)}\n')
        print(f'tabela geral:\n{tabela_geral.columns}\n')
        print(f'{len(tabela_geral.columns)}\n')
        base_sem_ponderar.index = tabela_geral.columns
        tabela_geral.loc['Base Sem Ponderar'] = base_sem_ponderar
        tabela_geral_front.loc['Base Sem Ponderar'] = base_sem_ponderar

        # Valores para Base Ponderada - Respostas
        soma_colunas_respostas = tbl_pond_freq_abs_respostas_NS_NR.sum()
        soma_colunas_respostas = pd.Series(soma_colunas_respostas)
        base_ponderada_respostas = pd.pivot_table(banco_pivotado, values=Var_Pond, index=Var_linha, aggfunc='sum')
        base_ponderada_respostas = pd.Series(base_ponderada_respostas.sum())
        base_ponderada_respostas = pd.concat([base_ponderada_respostas, soma_colunas_respostas])

        # Valores para Base Ponderada - Respondentes
        soma_colunas = tbl_pond_freq_abs_respondentes_NS_NR.sum()
        soma_colunas = pd.Series(soma_colunas)
        base_ponderada = pd.pivot_table(banco, values=Var_Pond, index=Var_ID, aggfunc='sum')
        base_ponderada = pd.Series(base_ponderada.sum())
        base_ponderada = pd.concat([base_ponderada, soma_colunas])

        # Índice de Multiplicidade (Total de respostas / Total de respondentes)
        indice_multiplicidade = base_ponderada_respostas / base_ponderada
        tabela_geral.loc['Índice de Multiplicidade'] = indice_multiplicidade
        tabela_geral_front.loc['Índice de Multiplicidade'] = indice_multiplicidade

        tabela_geral.rename(columns={tabela_geral.columns[0]: 'Geral'}, inplace=True)
        print(f'{tabela_geral}\n')
        tabela_geral_front.rename(columns={tabela_geral.columns[0]: 'Geral'}, inplace=True)

    else:
        if df[Var_linha].isna().all():
            # df[Var_linha] = df[Var_linha].astype('float').fillna(0)
            df[Var_linha] = df[Var_linha].cat.add_categories(['Não possui categoria']).fillna('Não possui categoria')
            print(f'Variável em branco\n{df[Var_linha]}\n')

        for col in Colunas:
            # Gerar Tabelas Ponderadas de frequência absoluta
            tabela = pd.crosstab(df[Var_linha], df[col], values=df[Var_Pond], aggfunc='sum')
            tabelas_pond_freq_abs.append(tabela)

            # Gerar Tabelas Ponderadas de frequência relativa 
            tabela = tabela.div(tabela.sum())
            tabela = tabela.fillna(0)
            tabelas_pond.append(tabela)
            print(f'Tabela Ponderada Freq Rel: \n{tabela}\n')

            # Gerar Tabelas Sem Ponderação
            tabela = pd.crosstab(df[Var_linha], df[col], dropna=False)
            tabela = tabela.fillna(0)
            print(f'Tabela Sem Ponderação: \n{tabela}\n')
            if len(tabela) == 0:
                tabela = pd.DataFrame(0, index=df[Var_linha][pd.notna(df[Var_linha])].unique(), 
                                    columns=df[col][pd.notna(df[col])].unique())
                print(f'Tabela Sem Ponderação: \n{tabela}\n')
            tabelas_sem_pond.append(tabela)

            # Gerar Tabelas para valores agrupados
            if 'var_agrupada' in df.columns:
                tabela = pd.crosstab(df['var_agrupada'], df[col], values=df[Var_Pond], aggfunc='sum')
                tabela = tabela.div(tabela.sum())
                print(f'Tabela Valores Agrupados: \n{tabela}\n')
                aux_tabelas_pond.append(tabela)

                # Tabelas sem ponderação
                tabela = pd.crosstab(df['var_agrupada'], df[col], dropna=False)
                print(f'Tabela Valores Agrupados Sem Ponderação: \n{tabela}\n')
                aux_tabelas_sem_pond.append(tabela)

        tabela_geral = pd.concat(tabelas_pond, axis=1)
        tabelas_pond_freq_abs = pd.concat(tabelas_pond_freq_abs, axis=1)
        tabelas_sem_pond = pd.concat(tabelas_sem_pond, axis=1)

        # Trazendo a coluna de valores gerais
        valores_gerais_pond = pd.pivot_table(df, values=Var_Pond, index=Var_linha, aggfunc='sum', observed=False)
        print(f'\nValores GERAL:\n{valores_gerais_pond}')
        percentual_geral = valores_gerais_pond.div(valores_gerais_pond.sum()).sort_index()
        print(f'\PERCENTUAL GERAL:\n{percentual_geral}')

        if 'var_agrupada' in df.columns:
            aux_tabelas_pond = pd.concat(aux_tabelas_pond, axis=1)
            aux_tabelas_sem_pond = pd.concat(aux_tabelas_sem_pond, axis=1)

            # Percentual para os valores gerais da variável agrupada
            valores_gerais_aux = pd.pivot_table(df, values=Var_Pond, index='var_agrupada', aggfunc='sum')
            percentual_geral_aux = valores_gerais_aux.div(valores_gerais_aux.sum()).sort_index()
            tabela_geral = pd.concat([tabela_geral, aux_tabelas_pond], axis=0)
            percentual_geral = pd.concat([percentual_geral, percentual_geral_aux], axis=0)
            tabela_geral = pd.concat([percentual_geral, tabela_geral], axis=1)

            tabela_geral_front = tabela_geral.multiply(100)
            tabela_geral_front = tabela_geral_front.applymap(lambda x: f"{x:.1f}%".replace(".", ","))

        else:
            tabela_geral = pd.concat([percentual_geral, tabela_geral], axis=1)

            tabela_geral_front = tabela_geral.multiply(100)
            tabela_geral_front = tabela_geral_front.applymap(lambda x: f"{x:.1f}%".replace(".", ","))

        # Multiplicando cada linha pelo seu índice+1
        if TipoTabela == 'NPS':
            # Gerar o NPS
            nps = tabela_geral.loc['Promotor'] - tabela_geral.loc['Detrator']
            tabela_geral.loc['NPS'] = nps
            # Gerar as médias
            media_tabela = tabelas_pond_freq_abs.copy()
            for i in range(len(tabelas_pond_freq_abs)):
                media_tabela.iloc[i] = tabelas_pond_freq_abs.iloc[i] * (i + 1)
            media_tabela = media_tabela.sum().div(tabelas_pond_freq_abs.sum())

            # Cálculo da média geral
            df_limpo = df.dropna(subset=[Var_linha])
            media_geral = sum(np.array(df_limpo[Var_linha]) * np.array(df_limpo[Var_Pond])) / sum(np.array(df_limpo[Var_Pond]))
            media_geral = pd.Series(media_geral)
            media_tabela = pd.concat([media_geral, media_tabela], axis=0)
            media_tabela.index = tabela_geral.columns

            tabela_geral_front = tabela_geral.multiply(100)
            tabela_geral_front = tabela_geral_front.applymap(lambda x: f"{x:.1f}%".replace(".", ","))
            tabela_geral_front.loc['Media'] = media_tabela

            tabela_geral.loc['Media'] = media_tabela

        elif (TipoTabela == 'SATISFACAO') | (TipoTabela == 'IPA_10') :
            media_tabela = tabelas_pond_freq_abs.copy()
            for i in range(len(tabelas_pond_freq_abs)):
                media_tabela.iloc[i] = tabelas_pond_freq_abs.iloc[i] * (i + 1)
            media_tabela = media_tabela.sum().div(tabelas_pond_freq_abs.sum())

            # Cálculo da média geral
            df_limpo = df.dropna(subset=[Var_linha])
            media_geral = sum(np.array(df_limpo[Var_linha]) * np.array(df_limpo[Var_Pond])) / sum(np.array(df_limpo[Var_Pond]))
            media_geral = pd.Series(media_geral)
            media_tabela = pd.concat([media_geral, media_tabela], axis=0)

            media_tabela.index = tabela_geral.columns

            tabela_geral_front = tabela_geral.multiply(100)
            tabela_geral_front = tabela_geral_front.applymap(lambda x: f"{x:.1f}%".replace(".", ","))
            tabela_geral_front.loc['Media'] = media_tabela

            tabela_geral.loc['Media'] = media_tabela

        else:
            tabela_geral

        tabela_geral = tabela_geral.fillna(0)

        # Valores para Base Ponderada
        tabelas_pond_freq_abs = tabelas_pond_freq_abs.fillna(0)
        soma_colunas = tabelas_pond_freq_abs.sum()
        soma_colunas = pd.Series(soma_colunas)
        base_ponderada = pd.pivot_table(df, values=Var_Pond, index=Var_linha, aggfunc='sum', observed=False)
        base_ponderada = pd.Series(base_ponderada.sum())
        base_ponderada = pd.concat([base_ponderada, soma_colunas])
        # base_ponderada.index = tabela_geral.columns
        tabela_geral.loc['Base Ponderada'] = base_ponderada
        tabela_geral_front.loc['Base Ponderada'] = base_ponderada.round().astype(int)

        # Valores para Base Sem Ponderar
        tabelas_sem_pond = tabelas_sem_pond.fillna(0)
        soma_colunas = pd.Series(tabelas_sem_pond.sum())
        print(f'{soma_colunas}\n')
        valores_gerais = df[Var_linha].value_counts().sort_index()
        base_sem_ponderar = pd.Series(valores_gerais.sum())
        base_sem_ponderar = pd.concat([base_sem_ponderar, soma_colunas])
        print(f'{base_sem_ponderar.index}\n')
        print(f'{tabela_geral.columns}\n')
        base_sem_ponderar.index = tabela_geral.columns
        tabela_geral.loc['Base Sem Ponderar'] = base_sem_ponderar
        tabela_geral_front.loc['Base Sem Ponderar'] = base_sem_ponderar

        tabela_geral.rename(columns={tabela_geral.columns[0]: 'Geral'}, inplace=True)
        tabela_geral_front.rename(columns={tabela_geral.columns[0]: 'Geral'}, inplace=True)
        print(f'TABELA GERAL:\n{tabela_geral.iloc[:, 0:10]}\n')


    Cabecalho = Cabecalho.split(sep=', ')
    print(f'Cabeçalho:\n{Cabecalho}')
    header_above = []
    print(f'\ntabela_geral.columns:\n{tabela_geral.columns}')
    for col in tabela_geral.columns:
        valor = col.split(sep=' - ')[0]
        print(f'valor: {valor}')
        header_above.append(valor)
    print(f'\nheader_above:\n{header_above}')

    col_series = []
    for i, valor in enumerate(Cabecalho):
        # col_names = df[Colunas[i]][pd.notna(df[Colunas[i]])].unique()
        col_names = dict_ord_labels[Colunas[i]]
        print(f'\ncol_names:\n{col_names}')
        for col in col_names:
            col_series.append((Titulo, valor, col))

    header = [(Titulo, '', 'GERAL')]
    print(f'\ncol_series:\n{col_series}')
    header = header + col_series
    print(f'\nheader:\n{header}')
    print(f'\ntamanho header:\t{len(header)}')
        
    header = pd.MultiIndex.from_tuples(header)
    print(f'\ntabela_geral.columns:\n{tabela_geral.columns}')
    print(f'\ntamanho tabela_geral.columns:\t{len(tabela_geral.columns)}')
    tabela_geral.columns = header
    tabela_geral_front.columns = header
    print(f"Tabela processada:\n{tabela_geral}")
    
    return tabela_geral, tabela_geral_front

In [ ]:
df = pd.DataFrame({
    "Label": ["Empresa 1", "Empresa 1", "Empresa 2", "Empresa 2"],
    "Codigo": [1, 2, 2, 2]
})
df

:

In [25]:
import pandas as pd
import numpy as np
from collections import Counter
from utils import ordenar_labels, ordenar_labels_multipla, ordenar_valores, classificar_nps, funcao_agrupamento, classificar_satis
path = r"C:\Users\rayner.santos\Downloads\Consistencia e Processamento\Cielo"
data = pd.read_excel(path + "\EMP_Cielo Satisfacao_3onda_NOV25_2025.12.26.xlsx", sheet_name="BD_CODIGOS")
lista_labels = pd.read_excel(path + "\EMP_Cielo Satisfacao_3onda_NOV25_2025.12.26.xlsx", sheet_name="LISTA_LABELS", header=1)
lista_labels.columns = ['Coluna', 'Codigo', 'Label']
lista_labels["Coluna"] = lista_labels["Coluna"].ffill().str.strip()
lista_labels

                 Coluna  Codigo           Label
0                  ONDA    28.0           Abr23
1                  ONDA    29.0  Mai23 (mensal)
2                  ONDA    30.0  Jun23 (mensal)
3                  ONDA    31.0           Jul23
4                  ONDA    32.0  Ago23 (mensal)
...                 ...     ...             ...
10221           TEMP_AC     6.0  8 anos ou mais
10222           TEMP_AC    90.0           NS/NR
10223              SEXO     1.0       Masculino
10224              SEXO     2.0        Feminino
10225  a. Missing value     NaN             NaN

[10226 rows x 3 columns]

In [59]:
sintaxe = pd.read_excel(path + "\Sintaxe_Cielo_Satisfacao_Nov25.xlsx", sheet_name="Teste2")

In [ ]:
def verif_TipoTabela(TipoTabela):
        if TipoTabela not in ["SIMPLES", "IPA_5", "IPA_10", "NPS", "MULTIPLA"]:
            return 1
        return 0

def verif_bandeiras_cabecalho(Bandeiras, Cabecalho):
     Bandeiras = Bandeiras.split(", ")
     Cabecalho = Cabecalho.split(", ")
     qtd_bandeiras = len(Bandeiras)
     qtd_cabecalho = len(Cabecalho)
     if qtd_bandeiras != qtd_cabecalho:
          return 1
     return 0

def verif_bandeiras(df, Bandeiras):
     Bandeiras = Bandeiras.split(", ")
     for col in Bandeiras:
          if col not in df.columns:
            # raise ValueError(f"⚠️ Coluna '{col}' não encontrada no DataFrame.")
            return 1, col
     return 0, col
      
def verif_Var_linha(df, Var_linha, TipoTabela):
     if TipoTabela != "MULTIPLA":
          if Var_linha not in df.columns:
               return 1
     return 0

def verif_NS_NR(NS_NR):
        if NS_NR not in ["NAO", "SIM"]:
            return 1
        return 0

def verif_Fecha_100(TipoTabela, Fecha_100):
     if TipoTabela == "MULTIPLA":
          if Fecha_100 not in ["NAO", "SIM"]:
               return 1
     return 0

def verif_coluna_existe(df, coluna):
    if coluna not in df.columns:
        return 1
    return 0


class verificar_incosistencias_iniciais:
    def __init__(self, data, sintaxe, lista_labels):
        self.data = data
        self.sintaxe = sintaxe
        self.lista_labels = lista_labels
    
    def verificar_incosistencia(self):
        df = self.data.copy()
        for line in range(len(self.sintaxe)):
            i = 0
            TipoTabela = self.sintaxe.iloc[line, i]
            i+=1
            Bandeiras = self.sintaxe.iloc[line, i]
            i+=1
            Cabecalho = self.sintaxe.iloc[line, i]
            i+=1
            Var_linha = self.sintaxe.iloc[line, i]
            i+=1
            NS_NR = self.sintaxe.iloc[line, i]
            i+=1
            valores_BTB = self.sintaxe.iloc[line, i]
            i+=1
            valores_TTB = self.sintaxe.iloc[line, i]
            i+=1
            Valores_Agrup = self.sintaxe.iloc[line, i]
            i+=1
            Fecha_100 = self.sintaxe.iloc[line, i]
            i+=1
            Var_ID = self.sintaxe.iloc[line, i]
            i+=1
            Var_Pond = self.sintaxe.iloc[line, i]
            i+=1
            Titulo = self.sintaxe.iloc[line, i]

            res_TipoTabela = verif_TipoTabela(TipoTabela)
            if res_TipoTabela == 1:
                 return f"⚠️ Verificar incosistência: o **Tipo de Tabela** informado na linha {line+2} não corresponde com as opções válidas: [SIMPLES, IPA_5, IPA_10, NPS, MULTIPLA]"
            
            res_bandeiras_cabecalho = verif_bandeiras_cabecalho(Bandeiras, Cabecalho)
            if res_bandeiras_cabecalho == 1:
                 return f"⚠️ Verificar incosistência: na linha {line+2}, **o nº de Bandeiras não é compatível com o nº de inputs do Cabeçalho**."
            
            res_bandeira, col = verif_bandeiras(df, Bandeiras)
            if res_bandeira == 1:
                 return f"⚠️ Coluna **{col}** que se encontra na coluna **Bandeiras** não foi encontrada no Banco de dados."
            
            res_Var_linha = verif_Var_linha(df, Var_linha, TipoTabela)
            if res_Var_linha == 1:
                 return f"⚠️ Verificar incosistência: na linha {line+2}, a variável/coluna informada que representa o **nível da linha** da tabela não consta no Banco de dados."
            
            res_NS_NR = verif_NS_NR(NS_NR)
            if res_NS_NR == 1:
                 return f"⚠️ Verificar incosistência: o valor informado na linha {line+2} da coluna **Contabiliza_NS/NR** não corresponde com as opções válidas: [NAO, SIM]"
            
            res_Fecha_100 = verif_Fecha_100(TipoTabela, Fecha_100)
            if res_Fecha_100 == 1:
                 return(f"⚠️ Verificar incosistência: o valor informado na linha {line+2} da coluna **Fecha_100** não corresponde com as opções válidas: [NAO, SIM]")
            
            res_Var_ID = verif_coluna_existe(df, Var_ID)
            if res_Var_ID == 1:
                 return f"⚠️ Verificar incosistência: na linha {line+2}, a variável/coluna informada que representa o **Código de identificação da entrevista** não consta no Banco de dados."
            
            res_Var_Pond = verif_coluna_existe(df, Var_Pond)
            if res_Var_Pond == 1:
                 return f"⚠️ Verificar incosistência: na linha {line+2}, a variável/coluna informada que representa a **Ponderação** não consta no Banco de dados."
        return 0

In [61]:
processamento_sintaxe = verificar_incosistencias_iniciais(data=data, sintaxe=sintaxe, lista_labels=lista_labels)
processamento_sintaxe.verificar_incosistencia()

'⚠️ Verificar incosistência: o valor informado na linha 2 da coluna **Contabiliza_NS/NR** não corresponde com as opções válidas: [NAO, SIM]'

In [1]:
def add_item(item, lst=[]):
    lst.append(item)
    return lst

add_item(1)
add_item(2)
print(add_item(3))

[1, 2, 3]

In [11]:
lista = [['SEG_ONDA', 'PESSOA_ONDA']] * 9
print(lista)

lista_final = []
for valor in lista:
    lista_final.append(valor[0] + ", " + valor[1])
    print(valor[0] + ", " + valor[1])

print(lista_final)

[['SEG_ONDA', 'PESSOA_ONDA'], ['SEG_ONDA', 'PESSOA_ONDA'], ['SEG_ONDA', 'PESSOA_ONDA'], ['SEG_ONDA', 'PESSOA_ONDA'], ['SEG_ONDA', 'PESSOA_ONDA'], ['SEG_ONDA', 'PESSOA_ONDA'], ['SEG_ONDA', 'PESSOA_ONDA'], ['SEG_ONDA', 'PESSOA_ONDA'], ['SEG_ONDA', 'PESSOA_ONDA']]
SEG_ONDA, PESSOA_ONDA
SEG_ONDA, PESSOA_ONDA
SEG_ONDA, PESSOA_ONDA
SEG_ONDA, PESSOA_ONDA
SEG_ONDA, PESSOA_ONDA
SEG_ONDA, PESSOA_ONDA
SEG_ONDA, PESSOA_ONDA
SEG_ONDA, PESSOA_ONDA
SEG_ONDA, PESSOA_ONDA
['SEG_ONDA, PESSOA_ONDA', 'SEG_ONDA, PESSOA_ONDA', 'SEG_ONDA, PESSOA_ONDA', 'SEG_ONDA, PESSOA_ONDA', 'SEG_ONDA, PESSOA_ONDA', 'SEG_ONDA, PESSOA_ONDA', 'SEG_ONDA, PESSOA_ONDA', 'SEG_ONDA, PESSOA_ONDA', 'SEG_ONDA, PESSOA_ONDA']

In [13]:
lista = [['ONDA', 'SEG_ONDA', 'PESSOA_ONDA']] * 9
lista_final = [", ".join(valor) for valor in lista]

for item in lista_final:
    print(item)

ONDA, SEG_ONDA, PESSOA_ONDA
ONDA, SEG_ONDA, PESSOA_ONDA
ONDA, SEG_ONDA, PESSOA_ONDA
ONDA, SEG_ONDA, PESSOA_ONDA
ONDA, SEG_ONDA, PESSOA_ONDA
ONDA, SEG_ONDA, PESSOA_ONDA
ONDA, SEG_ONDA, PESSOA_ONDA
ONDA, SEG_ONDA, PESSOA_ONDA
ONDA, SEG_ONDA, PESSOA_ONDA

In [1]:
import pandas as pd
df = pd.DataFrame({
    "ColA": [1, 1, 2],
    "ColB": ["Jan", "Jan", "Fev"]
})
mapping_de_para = dict(zip(df['ColA'], df['ColB']))
mapping_de_para

{1: 'Jan', 2: 'Fev'}