## <font color="greenblue">Cálculo para a ponderação</font>

In [212]:
import pandas as pd
import numpy as np
path = r"C:\Users\rayner.santos\Downloads\Consistencia e Processamento\Ponderacao_Img_Experiencia_2025_Onda1_v1.xlsx"
# Lê as duas primeiras linhas como cabeçalho (ajuste para [1,2] se no seu arquivo começa uma linha abaixo)
df_universo = pd.read_excel(path, sheet_name="FONTE", header=[0, 1])
df_universo.index = df_universo.iloc[:, 0]
df_universo = df_universo.iloc[:, 1:].copy()
display(df_universo)

                                                           TIM             \
                                                       SP1/SP2   RJ/ES/MG
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                                90.306894  68.044059
10 a 99                                             175.531027  62.955540
100 a 499                                            55.052337  28.381500
500 ou mais                                         175.547746  80.424852

                                                                            \
                                                      PR/SC/RS    NE/BA/SE
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                               312.419013   68.791615
10 a 99                                             296.377265  176.192369
100 a 499                                           123.991540   72.497047
500 ou mais                                          57.473158   94.171813

                                                                      VIVO  \
                                                         CO/NO     SP1/SP2
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                                39.548693  414.638203
10 a 99                                             109.891856  619.605938
100 a 499                                            55.485877  248.032549
500 ou mais                                          47.998039  274.102474

                                                                            \
                                                      RJ/ES/MG    PR/SC/RS
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                               294.494855  180.994268
10 a 99                                             606.991000  553.111742
100 a 499                                           222.214362  168.487060
500 ou mais                                         281.314550  103.254354

                                                                            \
                                                      NE/BA/SE       CO/NO
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                               180.820710  193.223766
10 a 99                                             259.498316  299.122315
100 a 499                                            57.310482   77.958241
500 ou mais                                          53.531459  154.393853

                                                         CLARO              \
                                                       SP1/SP2    RJ/ES/MG
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                               162.380065   58.732162
10 a 99                                             288.876311  256.020674
100 a 499                                            85.974487   60.722221
500 ou mais                                          79.804630  185.142547

                                                                            \
                                                      PR/SC/RS    NE/BA/SE
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                               130.626748   77.183855
10 a 99                                             226.009311  250.654734
100 a 499                                            74.972674   63.023831
500 ou mais                                          49.998555  148.391930


                                                         CO/NO
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                               140.884698
10 a 99                                             190.837279
100 a 499                                           101.867652
500 ou mais                                          41.597818

In [213]:
# pega os 2 níveis
lvl0 = pd.Index(df_universo.columns.get_level_values(0))
lvl1 = pd.Index(df_universo.columns.get_level_values(1))

# transforma "Unnamed: ..." em NaN e faz ffill no nível 0 (operadora)
lvl0 = (pd.Series(lvl0)
        .replace(r"^Unnamed:.*$", np.nan, regex=True)
        .ffill()
        .to_numpy())

# limpa quebras de linha e espaços (nos dois níveis)
def clean(arr):
    s = pd.Series(arr, dtype="string")
    return (s
            .str.replace(r"\s+", " ", regex=True)
            .str.strip()
            .to_numpy())

lvl0 = clean(lvl0)
lvl1 = clean(lvl1)

# recria MultiIndex
df_universo.columns = pd.MultiIndex.from_arrays([lvl0, lvl1])
df_universo

                                                           TIM             \
                                                       SP1/SP2   RJ/ES/MG
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                                90.306894  68.044059
10 a 99                                             175.531027  62.955540
100 a 499                                            55.052337  28.381500
500 ou mais                                         175.547746  80.424852

                                                                            \
                                                      PR/SC/RS    NE/BA/SE
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                               312.419013   68.791615
10 a 99                                             296.377265  176.192369
100 a 499                                           123.991540   72.497047
500 ou mais                                          57.473158   94.171813

                                                                      VIVO  \
                                                         CO/NO     SP1/SP2
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                                39.548693  414.638203
10 a 99                                             109.891856  619.605938
100 a 499                                            55.485877  248.032549
500 ou mais                                          47.998039  274.102474

                                                                            \
                                                      RJ/ES/MG    PR/SC/RS
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                               294.494855  180.994268
10 a 99                                             606.991000  553.111742
100 a 499                                           222.214362  168.487060
500 ou mais                                         281.314550  103.254354

                                                                            \
                                                      NE/BA/SE       CO/NO
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                               180.820710  193.223766
10 a 99                                             259.498316  299.122315
100 a 499                                            57.310482   77.958241
500 ou mais                                          53.531459  154.393853

                                                         CLARO              \
                                                       SP1/SP2    RJ/ES/MG
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                               162.380065   58.732162
10 a 99                                             288.876311  256.020674
100 a 499                                            85.974487   60.722221
500 ou mais                                          79.804630  185.142547

                                                                            \
                                                      PR/SC/RS    NE/BA/SE
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                               130.626748   77.183855
10 a 99                                             226.009311  250.654734
100 a 499                                            74.972674   63.023831
500 ou mais                                          49.998555  148.391930


                                                         CO/NO
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                               140.884698
10 a 99                                             190.837279
100 a 499                                           101.867652
500 ou mais                                          41.597818

In [215]:
# Soma do universo
total = int(df_universo.sum().sum().round())
total

10108

In [216]:
df_universo_perc = df_universo.divide(total)
df_universo_perc

                                                         TIM            \
                                                     SP1/SP2  RJ/ES/MG
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                               0.008934  0.006732
10 a 99                                             0.017366  0.006228
100 a 499                                           0.005446  0.002808
500 ou mais                                         0.017367  0.007957

                                                                        \
                                                    PR/SC/RS  NE/BA/SE
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                               0.030908  0.006806
10 a 99                                             0.029321  0.017431
100 a 499                                           0.012267  0.007172
500 ou mais                                         0.005686  0.009317

                                                                  VIVO  \
                                                       CO/NO   SP1/SP2
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                               0.003913  0.041021
10 a 99                                             0.010872  0.061299
100 a 499                                           0.005489  0.024538
500 ou mais                                         0.004749  0.027117

                                                                        \
                                                    RJ/ES/MG  PR/SC/RS
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                               0.029135  0.017906
10 a 99                                             0.060051  0.054720
100 a 499                                           0.021984  0.016669
500 ou mais                                         0.027831  0.010215

                                                                        \
                                                    NE/BA/SE     CO/NO
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                               0.017889  0.019116
10 a 99                                             0.025673  0.029593
100 a 499                                           0.005670  0.007713
500 ou mais                                         0.005296  0.015274

                                                       CLARO            \
                                                     SP1/SP2  RJ/ES/MG
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                               0.016065  0.005810
10 a 99                                             0.028579  0.025329
100 a 499                                           0.008506  0.006007
500 ou mais                                         0.007895  0.018316

                                                                        \
                                                    PR/SC/RS  NE/BA/SE
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                               0.012923  0.007636
10 a 99                                             0.022359  0.024798
100 a 499                                           0.007417  0.006235
500 ou mais                                         0.004946  0.014681


                                                       CO/NO
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                               0.013938
10 a 99                                             0.018880
100 a 499                                           0.010078
500 ou mais                                         0.004115

In [217]:
qtd_total_entrevistas = 2272
qtd_total_entrevistas

2272

In [218]:
df_ideal = df_universo_perc.multiply(qtd_total_entrevistas)
df_ideal

                                                          TIM             \
                                                      SP1/SP2   RJ/ES/MG
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                               20.298503  15.294430
10 a 99                                             39.454540  14.150671
100 a 499                                           12.374249   6.379379
500 ou mais                                         39.458298  18.077292

                                                                          \
                                                     PR/SC/RS   NE/BA/SE
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                               70.223189  15.462460
10 a 99                                             66.617446  39.603192
100 a 499                                           27.869883  16.295339
500 ou mais                                         12.918383  21.167230

                                                                     VIVO  \
                                                        CO/NO     SP1/SP2
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                                8.889457   93.199248
10 a 99                                             24.700663  139.270349
100 a 499                                           12.471697   55.750886
500 ou mais                                         10.788637   61.610687

                                                                            \
                                                      RJ/ES/MG    PR/SC/RS
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                                66.194332   40.682527
10 a 99                                             136.434859  124.324285
100 a 499                                            49.947668   37.871251
500 ou mais                                          63.231763   23.208735

                                                                          \
                                                     NE/BA/SE      CO/NO
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                               40.643515  43.431381
10 a 99                                             58.328074  67.234458
100 a 499                                           12.881818  17.522865
500 ou mais                                         12.032398  34.703486

                                                        CLARO             \
                                                      SP1/SP2   RJ/ES/MG
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                               36.498566  13.201372
10 a 99                                             64.931438  57.546396
100 a 499                                           19.324697  13.648683
500 ou mais                                         17.937883  41.614945

                                                                          \
                                                     PR/SC/RS   NE/BA/SE
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                               29.361295  17.348805
10 a 99                                             50.800668  56.340280
100 a 499                                           16.851792  14.166021
500 ou mais                                         11.238298  33.354419


                                                        CO/NO
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                               31.667000
10 a 99                                             42.894964
100 a 499                                           22.897042
500 ou mais                                          9.350044

In [219]:
path = r"C:\Users\rayner.santos\Downloads\Consistencia e Processamento\Ponderacao_Img_Experiencia_2025_Onda1_v1.xlsx"
# Lê as duas primeiras linhas como cabeçalho (ajuste para [1,2] se no seu arquivo começa uma linha abaixo)
df_coletado = pd.read_excel(path, sheet_name="COLETADO", header=[0, 1])
df_coletado.index = df_coletado.iloc[:, 0]
df_coletado = df_coletado.iloc[:, 1:].copy()
display(df_coletado)

                         1  TIM                                            \
                   1    SP1/SP2 2    RJ/ES/MG 3    PR/SC/RS 4    NE/BA/SE
( , PORTE)
1      1 A 9                 73            86            68            61
2      10 A 99               65            65            91            61
3      100 A 499             41            33            48            31
4      500 ou mais           30            16            21            10

                                    3 VIVO                              \
                   5    CO/NO 1    SP1/SP2 2    RJ/ES/MG 3    PR/SC/RS
( , PORTE)
1      1 A 9               56           68            62            27
2      10 A 99             57           67            69            55
3      100 A 499           28           52            44            28
4      500 ou mais         12           26            27            12

                                                 2 CLARO                \
                   4    NE/BA/SE 5    CO/NO 1    SP1/SP2 2    RJ/ES/MG
( , PORTE)
1      1 A 9                  25         23           43            23
2      10 A 99                38         39           64            43
3      100 A 499              18         17           40            39
4      500 ou mais            16          7           19            19


                   3    PR/SC/RS 4    NE/BA/SE 5    CO/NO
( , PORTE)
1      1 A 9                  22            22         28
2      10 A 99                33            33         31
3      100 A 499              34            34         31
4      500 ou mais            12            17         12

In [220]:
df_pond = pd.DataFrame(
    df_ideal.to_numpy() / df_coletado.astype(float).to_numpy(),
    index=df_ideal.index,
    columns=df_ideal.columns
)
df_pond

                                                         TIM            \
                                                     SP1/SP2  RJ/ES/MG
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                               0.278062  0.177842
10 a 99                                             0.606993  0.217703
100 a 499                                           0.301811  0.193315
500 ou mais                                         1.315277  1.129831

                                                                        \
                                                    PR/SC/RS  NE/BA/SE
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                               1.032694  0.253483
10 a 99                                             0.732060  0.649233
100 a 499                                           0.580623  0.525656
500 ou mais                                         0.615161  2.116723

                                                                  VIVO  \
                                                       CO/NO   SP1/SP2
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                               0.158740  1.370577
10 a 99                                             0.433345  2.078662
100 a 499                                           0.445418  1.072132
500 ou mais                                         0.899053  2.369642

                                                                        \
                                                    RJ/ES/MG  PR/SC/RS
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                               1.067651  1.506760
10 a 99                                             1.977317  2.260442
100 a 499                                           1.135174  1.352545
500 ou mais                                         2.341917  1.934061

                                                                        \
                                                    NE/BA/SE     CO/NO
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                               1.625741  1.888321
10 a 99                                             1.534949  1.723960
100 a 499                                           0.715657  1.030757
500 ou mais                                         0.752025  4.957641

                                                       CLARO            \
                                                     SP1/SP2  RJ/ES/MG
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                               0.848804  0.573973
10 a 99                                             1.014554  1.338288
100 a 499                                           0.483117  0.349966
500 ou mais                                         0.944099  2.190260

                                                                        \
                                                    PR/SC/RS  NE/BA/SE
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                               1.334604  0.788582
10 a 99                                             1.539414  1.707281
100 a 499                                           0.495641  0.416648
500 ou mais                                         0.936525  1.962025


                                                       CO/NO
(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponde...
1 a 9                                               1.130964
10 a 99                                             1.383709
100 a 499                                           0.738614
500 ou mais                                         0.779170

## <font color="greenblue">Coluna de ponderação</font>

In [221]:
path = r"C:\Users\rayner.santos\Downloads\Consistencia e Processamento\BD_TIM_Imagem_Onda1_2025_v10.xlsx"
data = pd.read_excel(path, sheet_name="Códigos", header=1)
display(data)

,codigo_entrevistado,F_1,F_2,F3,F4,Q1,Q2,Q2_FX,Q2A,Q2A_OU,...,SEG_VIV3,SEG_VIV4,SEG_VIV5,SEG_CLA1,SEG_CLA2,SEG_CLA3,SEG_CLA4,SEG_CLA5,PME_500,xxx
0,10011,2,2,2,1,5,1,3,2,NaN,...,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,1,NaN
1,10058,2,2,2,1,4,6,100,2,NaN,...,NaN,4.0,NaN,NaN,NaN,NaN,NaN,5.0,1,NaN
2,10073,2,2,2,1,9,1,3,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,1,NaN
3,10125,2,2,2,1,3,1,1,2,NaN,...,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,1,NaN
4,10206,2,2,2,1,1,1,3,2,NaN,...,3.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3039,390846,2,2,2,1,8,6,100,2,NaN,...,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,1,NaN
3040,390847,2,2,2,1,10,6,180,2,NaN,...,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,1,NaN
3041,390850,2,2,2,1,8,6,140,2,NaN,...,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,1,NaN
3042,390851,2,2,2,1,10,6,140,2,NaN,...,NaN,4.0,NaN,NaN,NaN,NaN,NaN,5.0,1,NaN
3043,390853,2,2,2,1,2,6,100,2,NaN,...,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,1,NaN

In [222]:
lista_labels = pd.DataFrame({
    "Coluna": ['OP_S', 'OP_S', 'OP_S', 'REG', 'REG', 'REG', 'REG', 'REG', 'PORTE', 'PORTE', 'PORTE', 'PORTE'],
    "Codigo": [1, 2, 3, 1, 2, 3, 4, 5, 1, 2, 3, 4],
    "Label": ["TIM", "CLARO", "VIVO", "SP1/SP2", "RJ/ES/MG", "PR/SC/RS", "NE/BA/SE", "CO/NO", "1 a 9", "10 a 99", "100 a 499", "500 ou mais"]
})
lista_labels

   Coluna  Codigo        Label
0    OP_S       1          TIM
1    OP_S       2        CLARO
2    OP_S       3         VIVO
3     REG       1      SP1/SP2
4     REG       2     RJ/ES/MG
5     REG       3     PR/SC/RS
6     REG       4     NE/BA/SE
7     REG       5        CO/NO
8   PORTE       1        1 a 9
9   PORTE       2      10 a 99
10  PORTE       3    100 a 499
11  PORTE       4  500 ou mais

In [223]:
CABECALHO = 'OP_S'
COLUNA = 'REG'
LINHA = 'PORTE'

lista_labels_cabecalho = lista_labels[lista_labels["Coluna"] == CABECALHO]
lista_labels_cabecalho_mapping = dict(zip(lista_labels_cabecalho['Codigo'], lista_labels_cabecalho['Label']))
print(lista_labels_cabecalho_mapping)

lista_labels_coluna = lista_labels[lista_labels["Coluna"] == COLUNA]
lista_labels_coluna_mapping = dict(zip(lista_labels_coluna['Codigo'], lista_labels_coluna['Label']))
print(lista_labels_coluna_mapping)

lista_labels_linha = lista_labels[lista_labels["Coluna"] == LINHA]
lista_labels_linha_mapping = dict(zip(lista_labels_linha['Codigo'], lista_labels_linha['Label']))
print(lista_labels_linha_mapping)

{1: 'TIM', 2: 'CLARO', 3: 'VIVO'}
{1: 'SP1/SP2', 2: 'RJ/ES/MG', 3: 'PR/SC/RS', 4: 'NE/BA/SE', 5: 'CO/NO'}
{1: '1 a 9', 2: '10 a 99', 3: '100 a 499', 4: '500 ou mais'}

In [224]:
# print(lista_labels[(lista_labels["Coluna"] == CABECALHO) and (lista_labels["Label"] == "TIM")]["Codigo"])
print(lista_labels[(lista_labels["Label"] == "TIM")]["Codigo"])

0    1
Name: Codigo, dtype: int64

In [226]:
display(df_pond["TIM"]["SP1/SP2"])
print(df_pond["TIM"]["SP1/SP2"]["10 a 99"])

(Fonte:, Dados Mapeamento 2024\nACESSOS\n(ponderados))
1 a 9          0.278062
10 a 99        0.606993
100 a 499      0.301811
500 ou mais    1.315277
Name: SP1/SP2, dtype: float64

0.606992928459355

In [ ]:
print(codigo_cabecalho)
print(codigo_coluna)
print(codigo)

3
5
4

In [242]:
data.loc[((data[CABECALHO] == codigo_cabecalho) & (data[COLUNA] == codigo_coluna) & (data[LINHA] == codigo_linha)), "POND"]

1771    9.299174
1827    9.299174
2433    9.299174
2668    9.299174
2689    9.299174
Name: POND, dtype: float64

In [259]:
data["Perc_esperado"] = np.nan
label_to_codigo = lista_labels.set_index("Label")["Codigo"].astype(int).to_dict()

for label_cabecalho in pd.Series(sorted(data[CABECALHO].astype(int).unique())).map(lista_labels_cabecalho_mapping):
    s = lista_labels.loc[lista_labels["Label"] == label_cabecalho, "Codigo"]
    if s.empty:
        raise KeyError(f"Label não encontrado: {label_cabecalho}")
    codigo_cabecalho = label_to_codigo[label_cabecalho]

    for label_coluna in pd.Series(sorted(data[COLUNA].astype(int).unique())).map(lista_labels_coluna_mapping):
        s = lista_labels.loc[lista_labels["Label"] == label_coluna, "Codigo"]
        if s.empty:
            raise KeyError(f"Label não encontrado: {label_coluna}")
        codigo_coluna = label_to_codigo[label_coluna]

        for label_linha in pd.Series(sorted(data[LINHA].astype(int).unique())).map(lista_labels_linha_mapping):
            s = lista_labels.loc[lista_labels["Label"] == label_linha, "Codigo"]
            if s.empty:
                raise KeyError(f"Label não encontrado: {label_linha}")
            codigo_linha = label_to_codigo[label_linha]

            print(f"cabeçalho: {label_cabecalho} - coluna: {label_coluna} - linha: {label_linha}")
            print(df_pond[label_cabecalho][label_coluna][label_linha])

            pond = df_pond[label_cabecalho][label_coluna][label_linha]
            data.loc[((data[CABECALHO] == codigo_cabecalho) & (data[COLUNA] == codigo_coluna) & (data[LINHA] == codigo_linha)), "Perc_esperado"] = pond

cabeçalho: TIM - coluna: SP1/SP2 - linha: 1 a 9
0.27806167838183143
cabeçalho: TIM - coluna: SP1/SP2 - linha: 10 a 99
0.606992928459355
cabeçalho: TIM - coluna: SP1/SP2 - linha: 100 a 499
0.3018109542369212
cabeçalho: TIM - coluna: SP1/SP2 - linha: 500 ou mais
1.3152766053353007
cabeçalho: TIM - coluna: RJ/ES/MG - linha: 1 a 9
0.17784221371707146
cabeçalho: TIM - coluna: RJ/ES/MG - linha: 10 a 99
0.21770263729441852
cabeçalho: TIM - coluna: RJ/ES/MG - linha: 100 a 499
0.1933145288110067
cabeçalho: TIM - coluna: RJ/ES/MG - linha: 500 ou mais
1.1298307218142025
cabeçalho: TIM - coluna: PR/SC/RS - linha: 1 a 9
1.0326939607037806
cabeçalho: TIM - coluna: PR/SC/RS - linha: 10 a 99
0.7320598476486585
cabeçalho: TIM - coluna: PR/SC/RS - linha: 100 a 499
0.580622567240346
cabeçalho: TIM - coluna: PR/SC/RS - linha: 500 ou mais
0.6151610918149977
cabeçalho: TIM - coluna: NE/BA/SE - linha: 1 a 9
0.2534829563957185
cabeçalho: TIM - coluna: NE/BA/SE - linha: 10 a 99
0.6492326516173643
cabeçalho: TIM - coluna: NE/BA/SE - linha: 100 a 499
0.525656107508507
cabeçalho: TIM - coluna: NE/BA/SE - linha: 500 ou mais
2.11672298860336
cabeçalho: TIM - coluna: CO/NO - linha: 1 a 9
0.15874030096621147
cabeçalho: TIM - coluna: CO/NO - linha: 10 a 99
0.43334495754685426
cabeçalho: TIM - coluna: CO/NO - linha: 100 a 499
0.44541774341939583
cabeçalho: TIM - coluna: CO/NO - linha: 500 ou mais
0.8990531000599651
cabeçalho: CLARO - coluna: SP1/SP2 - linha: 1 a 9
0.8488038657779181
cabeçalho: CLARO - coluna: SP1/SP2 - linha: 10 a 99
1.014553725249658
cabeçalho: CLARO - coluna: SP1/SP2 - linha: 100 a 499
0.48311742001288016
cabeçalho: CLARO - coluna: SP1/SP2 - linha: 500 ou mais
0.9440990927217192
cabeçalho: CLARO - coluna: RJ/ES/MG - linha: 1 a 9
0.57397271370161
cabeçalho: CLARO - coluna: RJ/ES/MG - linha: 10 a 99
1.3382882828735714
cabeçalho: CLARO - coluna: RJ/ES/MG - linha: 100 a 499
0.34996622545245853
cabeçalho: CLARO - coluna: RJ/ES/MG - linha: 500 ou mais
2.1902602783484477
cabeçalho: CLARO - coluna: PR/SC/RS - linha: 1 a 9
1.334604321222851
cabeçalho: CLARO - coluna: PR/SC/RS - linha: 10 a 99
1.53941418657929
cabeçalho: CLARO - coluna: PR/SC/RS - linha: 100 a 499
0.4956409444729959
cabeçalho: CLARO - coluna: PR/SC/RS - linha: 500 ou mais
0.9365248464729938
cabeçalho: CLARO - coluna: NE/BA/SE - linha: 1 a 9
0.7885820325665704
cabeçalho: CLARO - coluna: NE/BA/SE - linha: 10 a 99
1.7072812250249187
cabeçalho: CLARO - coluna: NE/BA/SE - linha: 100 a 499
0.416647685841131
cabeçalho: CLARO - coluna: NE/BA/SE - linha: 500 ou mais
1.9620246303012872
cabeçalho: CLARO - coluna: CO/NO - linha: 1 a 9
1.1309642775810735
cabeçalho: CLARO - coluna: CO/NO - linha: 10 a 99
1.383708520800055
cabeçalho: CLARO - coluna: CO/NO - linha: 100 a 499
0.7386142720467433
cabeçalho: CLARO - coluna: CO/NO - linha: 500 ou mais
0.7791703067652579
cabeçalho: VIVO - coluna: SP1/SP2 - linha: 1 a 9
1.3705771734875296
cabeçalho: VIVO - coluna: SP1/SP2 - linha: 10 a 99
2.078661930043963
cabeçalho: VIVO - coluna: SP1/SP2 - linha: 100 a 499
1.0721324159149517
cabeçalho: VIVO - coluna: SP1/SP2 - linha: 500 ou mais
2.369641792311083
cabeçalho: VIVO - coluna: RJ/ES/MG - linha: 1 a 9
1.0676505189786258
cabeçalho: VIVO - coluna: RJ/ES/MG - linha: 10 a 99
1.9773167943992123
cabeçalho: VIVO - coluna: RJ/ES/MG - linha: 100 a 499
1.1351742800421118
cabeçalho: VIVO - coluna: RJ/ES/MG - linha: 500 ou mais
2.34191713933026
cabeçalho: VIVO - coluna: PR/SC/RS - linha: 1 a 9
1.5067602407777416
cabeçalho: VIVO - coluna: PR/SC/RS - linha: 10 a 99
2.260441552657086
cabeçalho: VIVO - coluna: PR/SC/RS - linha: 100 a 499
1.3525446625452198
cabeçalho: VIVO - coluna: PR/SC/RS - linha: 500 ou mais
1.934061232946078
cabeçalho: VIVO - coluna: NE/BA/SE - linha: 1 a 9
1.6257406110710881
cabeçalho: VIVO - coluna: NE/BA/SE - linha: 10 a 99
1.5349493219040282
cabeçalho: VIVO - coluna: NE/BA/SE - linha: 100 a 499
0.7156565495513254
cabeçalho: VIVO - coluna: NE/BA/SE - linha: 500 ou mais
0.752024846342025
cabeçalho: VIVO - coluna: CO/NO - linha: 1 a 9
1.8883209052806664
cabeçalho: VIVO - coluna: CO/NO - linha: 10 a 99
1.723960454217284
cabeçalho: VIVO - coluna: CO/NO - linha: 100 a 499
1.0307567848726387
cabeçalho: VIVO - coluna: CO/NO - linha: 500 ou mais
4.957640835542117

In [247]:
display(data[["OP_S", "REG", "PORTE", "POND", "POND_nova"]])

      OP_S  REG  PORTE      POND  POND_nova
0        2    3      1  1.063199   1.334604
1        2    2      3  0.365731   0.349966
2        1    4      1  0.313889   0.253483
3        1    2      1  0.220339   0.177842
4        3    1      1  1.687415   1.370577
...    ...  ...    ...       ...        ...
3039     2    5      3  0.697217   0.738614
3040     2    4      3  0.431357   0.416648
3041     2    5      3  0.697217   0.738614
3042     2    4      3  0.431357   0.416648
3043     2    1      3  0.417602   0.483117

[3044 rows x 5 columns]

In [278]:
df_pond["CLARO"]["PR/SC/RS"]["1 a 9"]
df_pond["TIM"]["SP1/SP2"]["1 a 9"]

np.float64(0.27806167838183143)

### <font color="greenblue">Função para a ponderação - 3 dimensões</font>

In [256]:
import pandas as pd
import numpy as np
# === Função para criar a ponderação - 3 dimensões === #
def criar_pond_3dim(df_universo: pd.DataFrame, df_coletado: pd.DataFrame, 
               bd_codigo: pd.DataFrame, lista_labels: pd.DataFrame, cabecalho: str, coluna: str, linha: str):
    """
    Função para calcular a coluna de ponderação (3 categorias: Cabeçalho, coluna e linha - MultiIndex):
    1) A partir do universo e o coletado é criado o valor da ponderação
       - Ponderação é o valor IDEAL - percentual do universo vezes o total coletado, divido pelo COLETADO em cada categoria
    2) Com o banco de dados e a lista de labels cria-se a coluna POND no banco de dados
    """

    # Soma do universo
    total = int(df_universo.sum().sum().round())

    if total > 1:
        # df_universo em percentual
        df_universo_perc = df_universo.divide(total)
    else:
        # df_universo em percentual
        df_universo_perc = df_universo.copy()

    # Calcular a quantidade total de entrevistas
    qtd_total_entrevistas = int(df_coletado.sum().sum())

    # Valor ideal que deve ter de entrevistas para cada categoria
    df_ideal = df_universo_perc.multiply(qtd_total_entrevistas)

    # DataFrame com a ponderação criada de acordo com a combinação de categorias
    df_pond = pd.DataFrame(
        df_ideal.to_numpy() / df_coletado.astype(float).replace(0, 0.00001).to_numpy(),
        index=df_ideal.index,
        columns=df_ideal.columns
    )
    # df_pond = pd.DataFrame(
    #     df_ideal.div(df_coletado.astype(float).replace(0, 0.00001)),
    #     index=df_ideal.index,
    #     columns=df_ideal.columns
    # )
    # opcional: garantir que inf não fique:
    # df_pond = df_pond.replace([np.inf, -np.inf], np.nan)

    # Criar um mapeamento para cada label das categorias necessárias
    lista_labels_cabecalho = lista_labels[lista_labels["Coluna"] == cabecalho]
    lista_labels_cabecalho_mapping = dict(zip(lista_labels_cabecalho['Codigo'], lista_labels_cabecalho['Label']))

    lista_labels_coluna = lista_labels[lista_labels["Coluna"] == coluna]
    lista_labels_coluna_mapping = dict(zip(lista_labels_coluna['Codigo'], lista_labels_coluna['Label']))

    lista_labels_linha = lista_labels[lista_labels["Coluna"] == linha]
    lista_labels_linha_mapping = dict(zip(lista_labels_linha['Codigo'], lista_labels_linha['Label']))

    # Criar a nova coluna de PONDERAÇÃO de acordo com o df_pond
    if "POND_nova" not in bd_codigo.columns:
        bd_codigo["POND_nova"] = np.nan
    label_to_codigo = lista_labels.set_index("Label")["Codigo"].astype(int).to_dict()

    for label_cabecalho in pd.Series(sorted(bd_codigo[cabecalho].astype(int).unique())).map(lista_labels_cabecalho_mapping):
        if label_cabecalho in [v[0] for v in df_pond.columns]:
            s = lista_labels.loc[lista_labels["Label"] == label_cabecalho, "Codigo"]
            if s.empty:
                raise KeyError(f"Label não encontrado: {label_cabecalho}")
            codigo_cabecalho = label_to_codigo[label_cabecalho]

            for label_coluna in pd.Series(sorted(bd_codigo[coluna].astype(int).unique())).map(lista_labels_coluna_mapping):
                if label_coluna in [v[1] for v in df_pond.columns]:
                    s = lista_labels.loc[lista_labels["Label"] == label_coluna, "Codigo"]
                    if s.empty:
                        raise KeyError(f"Label não encontrado: {label_coluna}")
                    codigo_coluna = label_to_codigo[label_coluna]

                    for label_linha in pd.Series(sorted(bd_codigo[linha].astype(int).unique())).map(lista_labels_linha_mapping):
                        if label_linha in df_pond.index:
                            s = lista_labels.loc[lista_labels["Label"] == label_linha, "Codigo"]
                            if s.empty:
                                raise KeyError(f"Label não encontrado: {label_linha}")
                            codigo_linha = label_to_codigo[label_linha]

                            pond = df_pond[label_cabecalho][label_coluna][label_linha]
                            bd_codigo.loc[((bd_codigo[cabecalho] == codigo_cabecalho) & (bd_codigo[coluna] == codigo_coluna) & (bd_codigo[linha] == codigo_linha)), "POND_nova"] = pond
    
    return bd_codigo

In [124]:
# === Ponderação para o caso da TIM === #
path = r"C:\Users\rayner.santos\Downloads\Consistencia e Processamento\TIM\Ponderacao_Img_Experiencia_2025_Onda1_v1.xlsx"
# Lê as duas primeiras linhas como cabeçalho (ajuste para [1,2] se no seu arquivo começa uma linha abaixo)
df_universo = pd.read_excel(path, sheet_name="FONTE", header=[0, 1])
df_universo.index = df_universo.iloc[:, 0]
df_universo = df_universo.iloc[:, 1:].copy()

# Lê as duas primeiras linhas como cabeçalho (ajuste para [1,2] se no seu arquivo começa uma linha abaixo)
df_coletado = pd.read_excel(path, sheet_name="COLETADO", header=[0, 1])
df_coletado.index = df_coletado.iloc[:, 0]
df_coletado = df_coletado.iloc[:, 1:].copy()

path = r"C:\Users\rayner.santos\Downloads\Consistencia e Processamento\TIM\BD_TIM_Imagem_Onda1_2025_v10.xlsx"
data = pd.read_excel(path, sheet_name="Códigos", header=1)

lista_labels = pd.DataFrame({
    "Coluna": ['OP_S', 'OP_S', 'OP_S', 'REG', 'REG', 'REG', 'REG', 'REG', 'PORTE', 'PORTE', 'PORTE', 'PORTE'],
    "Codigo": [1, 2, 3, 1, 2, 3, 4, 5, 1, 2, 3, 4],
    "Label": ["TIM", "CLARO", "VIVO", "SP1/SP2", "RJ/ES/MG", "PR/SC/RS", "NE/BA/SE", "CO/NO", "1 a 9", "10 a 99", "100 a 499", "500 ou mais"]
})

CABECALHO = 'OP_S'
COLUNA = 'REG'
LINHA = 'PORTE'

df_atualizado = criar_pond_3dim(df_universo, df_coletado, data, lista_labels, CABECALHO, COLUNA, LINHA)
df_atualizado[["OP_S", "REG", "PORTE", "POND", "POND_nova"]]

      OP_S  REG  PORTE      POND  POND_nova
0        2    3      1  1.063199   1.063187
1        2    2      3  0.365731   0.365727
2        1    4      1  0.313889   0.313885
3        1    2      1  0.220339   0.220337
4        3    1      1  1.687415   1.687396
...    ...  ...    ...       ...        ...
3039     2    5      3  0.697217   0.697209
3040     2    4      3  0.431357   0.431352
3041     2    5      3  0.697217   0.697209
3042     2    4      3  0.431357   0.431352
3043     2    1      3  0.417602   0.417597

[3044 rows x 5 columns]

In [258]:
# === Ponderação para o caso da CIELO === #
path = r"C:\Users\rayner.santos\Downloads\Consistencia e Processamento\Cielo\POND_FINAL_Satisfacao_NOV25_v02.xlsx"
df_universo = pd.read_excel(path, sheet_name="FONTE_D3", header=[0, 1])
df_universo.index = df_universo.iloc[:, 0]
df_universo = df_universo.iloc[:, 1:].copy()

# Lê as duas primeiras linhas como cabeçalho (ajuste para [1,2] se no seu arquivo começa uma linha abaixo)
df_coletado = pd.read_excel(path, sheet_name="COLETADO_D3", header=[0, 1])
df_coletado.index = df_coletado.iloc[:, 0]
df_coletado = df_coletado.iloc[:, 1:].copy()

path = r"C:\Users\rayner.santos\Downloads\Consistencia e Processamento\Cielo\EMP_Cielo Satisfacao_3onda_NOV25_2025.12.26.xlsx"
data = pd.read_excel(path, sheet_name="BD_CODIGOS")

lista_labels = pd.read_excel(path, sheet_name="LISTA_LABELS", header=1)
lista_labels.columns = ['Coluna', 'Codigo', 'Label']
lista_labels["Coluna"] = lista_labels["Coluna"].ffill().str.strip()

CABECALHO = 'TRAB_C'
COLUNA = 'SEG_NOVO_BU'
LINHA = 'PF_PJ'

df_atualizado = criar_pond_3dim(df_universo, df_coletado, df_atualizado, lista_labels, CABECALHO, COLUNA, LINHA)
df_atualizado[[CABECALHO, COLUNA, LINHA, "POND", "POND_nova"]]

       TRAB_C  SEG_NOVO_BU  PF_PJ      POND  POND_nova
0           1            2      2  0.999119   0.999119
1           2            2      2  1.497418   1.497418
2           1            1      2  0.317763   0.317763
3           2            1      2  0.263658   0.263658
4           2            2      1  1.982729   1.982729
...       ...          ...    ...       ...        ...
15381       2            1      2  0.263658   0.263658
15382       2            2      1  1.982729   1.982729
15383       2            2      2  1.497418   1.497418
15384       2            2      2  1.497418   1.497418
15385       2            1      2  0.263658   0.263658

[15386 rows x 5 columns]

In [122]:
# Calcular a quantidade total de entrevistas
qtd_total_entrevistas = int(df_coletado.sum().sum())

# Valor ideal que deve ter de entrevistas para cada categoria
df_ideal = df_universo.multiply(qtd_total_entrevistas)

# DataFrame com a ponderação criada de acordo com a combinação de categorias
# df_pond = pd.DataFrame(
#     df_ideal.to_numpy() / df_coletado.astype(float).to_numpy(),
#     index=df_ideal.index,
#     columns=df_ideal.columns
# )
df_pond = pd.DataFrame(
        df_ideal.div(df_coletado.astype(float).replace(0, 0.00001)),
        index=df_ideal.index,
        columns=df_ideal.columns
    )
df_pond

                                                     PF                 \
                                         Empreendedores    Varejo   GC
(Unnamed: 0_level_0, Unnamed: 0_level_1)
São Paulo                                      1.601690  2.804340  0.0
Sudeste (Sem São Paulo)                        0.470412  1.339179  0.0
Sul                                            0.984188  2.190605  0.0
Centro-Oeste                                   0.982183  3.756057  0.0
Norte                                          1.067385  6.878397  0.0
Nordeste                                       0.372601  1.655086  0.0

                                                     PJ
                                         Empreendedores    Varejo        GC
(Unnamed: 0_level_0, Unnamed: 0_level_1)
São Paulo                                      0.452687  1.340074  1.000669
Sudeste (Sem São Paulo)                        0.317763  0.999119  1.183012
Sul                                            0.453288  0.994190  1.167923
Centro-Oeste                                   0.323871  0.658696  0.811759
Norte                                          0.991396  1.008466  1.153750
Nordeste                                       0.911252  2.489846  1.279217

In [24]:
df_universo_perc.sum().sum()

np.float64(0.9999678189278338)

### <font color="greenblue">Função para a ponderação - 2 dimensões</font>

In [ ]:
# Função para criar a ponderação - 2 dimensões
def criar_pond_2dim(df_universo: pd.DataFrame, df_coletado: pd.DataFrame, 
               bd_codigo: pd.DataFrame, lista_labels: pd.DataFrame, coluna: str, linha: str):
    """
    Função para calcular a coluna de ponderação (2 categorias: Coluna e linha):
    1) A partir do universo e o coletado é criado o valor da ponderação
       - Ponderação é o valor IDEAL - percentual do universo vezes o total coletado, divido pelo COLETADO em cada categoria
    2) Com o banco de dados e a lista de labels cria-se a coluna POND no banco de dados
    """

    # Soma do universo
    total = int(df_universo.sum().sum().round())

    if total > 1:
        # df_universo em percentual
        df_universo_perc = df_universo.divide(total)
    else:
        # df_universo em percentual
        df_universo_perc = df_universo.copy()

    # Calcular a quantidade total de entrevistas
    qtd_total_entrevistas = int(df_coletado.sum().sum())

    # Valor ideal que deve ter de entrevistas para cada categoria
    df_ideal = df_universo_perc.multiply(qtd_total_entrevistas)

    # DataFrame com a ponderação criada de acordo com a combinação de categorias
    df_pond = pd.DataFrame(
        df_ideal.to_numpy() / df_coletado.astype(float).replace(0, 0.00001).to_numpy(),
        index=df_ideal.index,
        columns=df_ideal.columns
    )
    # df_pond = pd.DataFrame(
    #     df_ideal.div(df_coletado.astype(float).replace(0, 0.00001)),
    #     index=df_ideal.index,
    #     columns=df_ideal.columns
    # )
    # opcional: garantir que inf não fique:
    # df_pond = df_pond.replace([np.inf, -np.inf], np.nan)

    # Criar um mapeamento para cada label das categorias necessárias
    lista_labels_coluna = lista_labels[lista_labels["Coluna"] == coluna]
    lista_labels_coluna_mapping = dict(zip(lista_labels_coluna['Codigo'], lista_labels_coluna['Label']))

    lista_labels_linha = lista_labels[lista_labels["Coluna"] == linha]
    lista_labels_linha_mapping = dict(zip(lista_labels_linha['Codigo'], lista_labels_linha['Label']))

    # Criar a nova coluna de PONDERAÇÃO de acordo com o df_pond
    if "POND_nova" not in bd_codigo.columns:
        bd_codigo["POND_nova"] = np.nan
    label_to_codigo = lista_labels.set_index("Label")["Codigo"].astype(int).to_dict()

    for label_coluna in pd.Series(sorted(bd_codigo[coluna].astype(int).unique())).map(lista_labels_coluna_mapping):
        if label_coluna in df_pond.columns:
            s = lista_labels.loc[lista_labels["Label"] == label_coluna, "Codigo"]
            if s.empty:
                raise KeyError(f"Label não encontrado: {label_coluna}")
            codigo_coluna = label_to_codigo[label_coluna]

            for label_linha in pd.Series(sorted(bd_codigo[linha].astype(int).unique())).map(lista_labels_linha_mapping):
                if label_linha in df_pond.index:
                    s = lista_labels.loc[lista_labels["Label"] == label_linha, "Codigo"]
                    if s.empty:
                        raise KeyError(f"Label não encontrado: {label_linha}")
                    codigo_linha = label_to_codigo[label_linha]

                    pond = df_pond.loc[label_linha, label_coluna]
                    bd_codigo.loc[((bd_codigo[coluna] == codigo_coluna) & (bd_codigo[linha] == codigo_linha)), "POND_nova"] = pond
    
    return bd_codigo

In [ ]:
# === Ponderação para o caso da CIELO === #
path = r"C:\Users\rayner.santos\Downloads\Consistencia e Processamento\Cielo\POND_FINAL_Satisfacao_NOV25_v02.xlsx"
df_universo = pd.read_excel(path, sheet_name="FONTE_D2")
df_universo.index = df_universo.iloc[:, 0]
df_universo = df_universo.iloc[:, 1:].copy()

# Lê as duas primeiras linhas como cabeçalho (ajuste para [1,2] se no seu arquivo começa uma linha abaixo)
df_coletado = pd.read_excel(path, sheet_name="COLETADO_D2")
df_coletado.index = df_coletado.iloc[:, 0]
df_coletado = df_coletado.iloc[:, 1:].copy()

path = r"C:\Users\rayner.santos\Downloads\Consistencia e Processamento\Cielo\EMP_Cielo Satisfacao_3onda_NOV25_2025.12.26.xlsx"
data = pd.read_excel(path, sheet_name="BD_CODIGOS")

lista_labels = pd.read_excel(path, sheet_name="LISTA_LABELS", header=1)
lista_labels.columns = ['Coluna', 'Codigo', 'Label']
lista_labels["Coluna"] = lista_labels["Coluna"].ffill().str.strip()

CABECALHO = 'PF_PJ'
COLUNA = 'SEG_NOVO_BU'
LINHA = 'PF_PJ'

df_atualizado = criar_pond_2dim(df_universo, df_coletado, data, lista_labels, COLUNA, LINHA)
df_atualizado[[COLUNA, LINHA, "POND", "POND_nova"]]

       SEG_NOVO_BU  VREG      POND  POND_nova
0                2     2  0.999119   1.024946
1                2     4  1.497418   0.718839
2                1     2  0.317763   0.366020
3                1     2  0.263658   0.366020
4                2     2  1.982729   1.024946
...            ...   ...       ...        ...
15381            1     4  0.263658   0.437018
15382            2     2  1.982729   1.024946
15383            2     1  1.497418   1.410359
15384            2     3  1.497418   1.031774
15385            1     1  0.263658   0.649363

[15386 rows x 4 columns]

In [250]:
import pandas as pd
import numpy as np
# === Função para criar a ponderação - 4 dimensões === #
def criar_pond_4dim(df_universo: pd.DataFrame, df_coletado: pd.DataFrame, 
               bd_codigo: pd.DataFrame, lista_labels: pd.DataFrame, cabecalho_greater: str, cabecalho: str, coluna: str, linha: str):
    """
    Função para calcular a coluna de ponderação (4 categorias: Cabeçalho Superior, Cabeçalho, Coluna e Linha - MultiIndex):
    1) A partir do universo e o coletado é criado o valor da ponderação
       - Ponderação é o valor IDEAL - percentual do universo vezes o total coletado, divido pelo COLETADO em cada categoria
    2) Com o banco de dados e a lista de labels cria-se a coluna POND no banco de dados
    """

    # Soma do universo
    total = int(df_universo.sum().sum().round())

    if total > 1:
        # df_universo em percentual
        df_universo_perc = df_universo.divide(total)
    else:
        # df_universo em percentual
        df_universo_perc = df_universo.copy()

    # Calcular a quantidade total de entrevistas
    qtd_total_entrevistas = int(df_coletado.sum().sum())

    # Valor ideal que deve ter de entrevistas para cada categoria
    df_ideal = df_universo_perc.multiply(qtd_total_entrevistas)

    # DataFrame com a ponderação criada de acordo com a combinação de categorias
    df_pond = pd.DataFrame(
        df_ideal.to_numpy() / df_coletado.astype(float).replace(0, 0.00001).to_numpy(),
        index=df_ideal.index,
        columns=df_ideal.columns
    )
    # df_pond = pd.DataFrame(
    #     df_ideal.div(df_coletado.astype(float).replace(0, 0.00001)),
    #     index=df_ideal.index,
    #     columns=df_ideal.columns
    # )
    # opcional: garantir que inf não fique:
    # df_pond = df_pond.replace([np.inf, -np.inf], np.nan)

    # Criar um mapeamento para cada label das categorias necessárias
    lista_labels_cabecalho_greater = lista_labels[lista_labels["Coluna"] == cabecalho_greater]
    lista_labels_cabecalho_greater_mapping = dict(zip(lista_labels_cabecalho_greater['Codigo'], lista_labels_cabecalho_greater['Label']))

    lista_labels_cabecalho = lista_labels[lista_labels["Coluna"] == cabecalho]
    lista_labels_cabecalho_mapping = dict(zip(lista_labels_cabecalho['Codigo'], lista_labels_cabecalho['Label']))

    lista_labels_coluna = lista_labels[lista_labels["Coluna"] == coluna]
    lista_labels_coluna_mapping = dict(zip(lista_labels_coluna['Codigo'], lista_labels_coluna['Label']))

    lista_labels_linha = lista_labels[lista_labels["Coluna"] == linha]
    lista_labels_linha_mapping = dict(zip(lista_labels_linha['Codigo'], lista_labels_linha['Label']))

    # Criar a nova coluna de PONDERAÇÃO de acordo com o df_pond
    if "POND_nova" not in bd_codigo.columns:
        bd_codigo["POND_nova"] = np.nan
    label_to_codigo = lista_labels.set_index("Label")["Codigo"].astype(int).to_dict()

    for label_cabecalho_greater in pd.Series(sorted(bd_codigo[cabecalho_greater].astype(int).unique())).map(lista_labels_cabecalho_greater_mapping):
        if label_cabecalho_greater in [v[0] for v in df_pond.columns]:
            s = lista_labels.loc[lista_labels["Label"] == label_cabecalho_greater, "Codigo"]
            if s.empty:
                raise KeyError(f"Label não encontrado: {label_cabecalho_greater}")
            codigo_cabecalho_greater = label_to_codigo[label_cabecalho_greater]

            for label_cabecalho in pd.Series(sorted(bd_codigo[cabecalho].astype(int).unique())).map(lista_labels_cabecalho_mapping):
                if label_cabecalho in [v[1] for v in df_pond.columns]:
                    s = lista_labels.loc[lista_labels["Label"] == label_cabecalho, "Codigo"]
                    if s.empty:
                        raise KeyError(f"Label não encontrado: {label_cabecalho}")
                    codigo_cabecalho = label_to_codigo[label_cabecalho]

                    for label_coluna in pd.Series(sorted(bd_codigo[coluna].astype(int).unique())).map(lista_labels_coluna_mapping):
                        if label_coluna in [v[2] for v in df_pond.columns]:
                            s = lista_labels.loc[lista_labels["Label"] == label_coluna, "Codigo"]
                            if s.empty:
                                raise KeyError(f"Label não encontrado: {label_coluna}")
                            codigo_coluna = label_to_codigo[label_coluna]

                            for label_linha in pd.Series(sorted(bd_codigo[linha].astype(int).unique())).map(lista_labels_linha_mapping):
                                if label_linha in df_pond.index:
                                    s = lista_labels.loc[lista_labels["Label"] == label_linha, "Codigo"]
                                    if s.empty:
                                        raise KeyError(f"Label não encontrado: {label_linha}")
                                    codigo_linha = label_to_codigo[label_linha]

                                pond = df_pond.loc[label_linha, (label_cabecalho_greater, label_cabecalho, label_coluna)]
                                bd_codigo.loc[((bd_codigo[cabecalho_greater] == codigo_cabecalho_greater) & (bd_codigo[cabecalho] == codigo_cabecalho) & (bd_codigo[coluna] == codigo_coluna) & (bd_codigo[linha] == codigo_linha)), "POND_nova"] = pond
    
    return bd_codigo

In [251]:
# === Ponderação para o caso da CIELO === #
CABECALHO_GREATER = "TRAB_C"
CABECALHO = 'PF_PJ'
COLUNA = 'SEG_NOVO_BU'
LINHA = 'VREG'

path = r"C:\Users\rayner.santos\Downloads\Consistencia e Processamento\Cielo\POND_FINAL_Satisfacao_NOV25_v02.xlsx"
df_universo = pd.read_excel(path, sheet_name="FONTE", 
                            header=[0, 1, 2], # <- pega TRAB_C, PÚBLICO e SEGMENTO
                            index_col=0 # <- REGIÃO (VREG) vira índice (Dimensão 4)
                            )

# Lê as duas primeiras linhas como cabeçalho (ajuste para [1,2] se no seu arquivo começa uma linha abaixo)
df_coletado = pd.read_excel(path, sheet_name="COLETADO", 
                            header=[0, 1, 2], # <- pega SEXO, PÚBLICO e SEGMENTO
                            index_col=0 # <- REGIÃO (VREG) vira índice (Dimensão 4)
                            )

path = r"C:\Users\rayner.santos\Downloads\Consistencia e Processamento\Cielo\EMP_Cielo Satisfacao_3onda_NOV25_2025.12.26.xlsx"
data = pd.read_excel(path, sheet_name="BD_CODIGOS")

lista_labels = pd.read_excel(path, sheet_name="LISTA_LABELS", header=1)
lista_labels.columns = ['Coluna', 'Codigo', 'Label']
lista_labels["Coluna"] = lista_labels["Coluna"].ffill().str.strip()

df_atualizado = criar_pond_4dim(df_universo, df_coletado, data, lista_labels, CABECALHO_GREATER, CABECALHO, COLUNA, LINHA)
df_atualizado[[CABECALHO_GREATER, CABECALHO, COLUNA, LINHA, "POND", "POND_nova"]]

       TRAB_C  PF_PJ  SEG_NOVO_BU  VREG      POND  POND_nova
0           1      2            2     2  0.999119   0.999119
1           2      2            2     4  1.497418        NaN
2           1      2            1     2  0.317763   0.317763
3           2      2            1     2  0.263658        NaN
4           2      1            2     2  1.982729        NaN
...       ...    ...          ...   ...       ...        ...
15381       2      2            1     4  0.263658        NaN
15382       2      1            2     2  1.982729        NaN
15383       2      2            2     1  1.497418        NaN
15384       2      2            2     3  1.497418        NaN
15385       2      2            1     1  0.263658        NaN

[15386 rows x 6 columns]

In [255]:
df_atualizado.loc[(df_atualizado["TRAB_C"] == 1) & (df_atualizado["PF_PJ"] == 2), "POND_nova"].isna().sum()

np.int64(0)

In [ ]:
df_universo.loc[:, "Sim"]

                                   Sim                                        \
                                    PF                          PJ
                        Empreendedores    Varejo GC Empreendedores    Varejo
São Paulo                     0.015883  0.017564  0       0.021737  0.166460
Sudeste (Sem São Paulo)       0.012030  0.012581  0       0.017580  0.114200
Sul                           0.008219  0.006860  0       0.013722  0.095994
Centro-Oeste                  0.005639  0.007841  0       0.008959  0.069445
Norte                         0.002785  0.003590  0       0.006209  0.042107
Nordeste                      0.008557  0.010366  0       0.023304  0.118255



                               GC
São Paulo                0.054838
Sudeste (Sem São Paulo)  0.038281
Sul                      0.036574
Centro-Oeste             0.017371
Norte                    0.009635
Nordeste                 0.033382

In [243]:
UNIVERSOS_2 = "SIM"
# if UNIVERSOS_2 == "SIM":
#     df_universo_

# Soma do universo
total = int(df_universo.sum().sum().round())

if total > 15:
    # df_universo em percentual
    df_universo_perc = df_universo.divide(total)
else:
    # df_universo em percentual
    df_universo_perc = df_universo.copy()

# Calcular a quantidade total de entrevistas
qtd_total_entrevistas = int(df_coletado.sum().sum())

# Valor ideal que deve ter de entrevistas para cada categoria
df_ideal = df_universo_perc.multiply(qtd_total_entrevistas)

# DataFrame com a ponderação criada de acordo com a combinação de categorias
df_pond = pd.DataFrame(
    df_ideal.to_numpy() / df_coletado.astype(float).replace(0, 0.00001).to_numpy(),
    index=df_ideal.index,
    columns=df_ideal.columns
)
df_pond

                                   Sim                                \
                                    PF                            PJ
                        Empreendedores    Varejo   GC Empreendedores
São Paulo                     1.601690  2.804340  0.0       0.452687
Sudeste (Sem São Paulo)       0.470412  1.339179  0.0       0.317763
Sul                           0.984188  2.190605  0.0       0.453288
Centro-Oeste                  0.982183  3.756057  0.0       0.323871
Norte                         1.067385  6.878397  0.0       0.991396
Nordeste                      0.372601  1.655086  0.0       0.911252



                           Varejo        GC
São Paulo                1.340074  1.000669
Sudeste (Sem São Paulo)  0.999119  1.183012
Sul                      0.994190  1.167923
Centro-Oeste             0.658696  0.811759
Norte                    1.008466  1.153750
Nordeste                 2.489846  1.279217

In [244]:
df_pond.loc["São Paulo", ("Sim", "PF", "Varejo")]

np.float64(2.80433967717617)

In [245]:
# Criar um mapeamento para cada label das categorias necessárias
lista_labels_cabecalho_greater = lista_labels[lista_labels["Coluna"] == CABECALHO_GREATER]
lista_labels_cabecalho_greater_mapping = dict(zip(lista_labels_cabecalho_greater['Codigo'], lista_labels_cabecalho_greater['Label']))
print(lista_labels_cabecalho_greater_mapping)

lista_labels_cabecalho = lista_labels[lista_labels["Coluna"] == CABECALHO]
lista_labels_cabecalho_mapping = dict(zip(lista_labels_cabecalho['Codigo'], lista_labels_cabecalho['Label']))
print(lista_labels_cabecalho_mapping)

lista_labels_coluna = lista_labels[lista_labels["Coluna"] == COLUNA]
lista_labels_coluna_mapping = dict(zip(lista_labels_coluna['Codigo'], lista_labels_coluna['Label']))
print(lista_labels_coluna_mapping)

lista_labels_linha = lista_labels[lista_labels["Coluna"] == LINHA]
lista_labels_linha_mapping = dict(zip(lista_labels_linha['Codigo'], lista_labels_linha['Label']))
print(lista_labels_linha_mapping)

{1: 'Sim', 2: 'Não'}
{1: 'PF', 2: 'PJ'}
{1: 'Empreendedores', 2: 'Varejo', 3: 'GC'}
{1: 'São Paulo', 2: 'Sudeste (Sem São Paulo)', 3: 'Sul', 4: 'Centro-Oeste', 5: 'Norte', 6: 'Nordeste'}

In [248]:
[v[0] for v in df_pond.columns]
lista_labels.loc[lista_labels["Label"] == "PJ", "Codigo"]
label_to_codigo["PJ"]
[v[1] for v in df_pond.columns]

['PF', 'PF', 'PF', 'PJ', 'PJ', 'PJ']

In [249]:
label_to_codigo = lista_labels.set_index("Label")["Codigo"].astype(int).to_dict()

lista_labels_multiindex_cabecalho_greater = [v[0] for v in df_pond.columns]
print(lista_labels_multiindex_cabecalho_greater)
for label_cabecalho_greater in pd.Series(sorted(data[CABECALHO_GREATER].astype(int).unique())).map(lista_labels_cabecalho_greater_mapping):
    print("Label cabecalho_greater: ", label_cabecalho_greater)
    if label_cabecalho_greater in lista_labels_multiindex_cabecalho_greater:
        s = lista_labels.loc[lista_labels["Label"] == label_cabecalho_greater, "Codigo"]
        if s.empty:
            raise KeyError(f"Label não encontrado: {label_cabecalho_greater}")
        codigo_cabecalho_greater = label_to_codigo[label_cabecalho_greater]
        # print("Codigo", codigo_cabecalho_greater)

        lista_labels_multiindex_cabecalho = [v[1] for v in df_pond.columns]
        print(lista_labels_multiindex_cabecalho)
        for label_cabecalho in pd.Series(sorted(data[CABECALHO].astype(int).unique())).map(lista_labels_cabecalho_mapping):
            print("Label cabecalho: ", label_cabecalho)
            if label_cabecalho in lista_labels_multiindex_cabecalho:
                s = lista_labels.loc[lista_labels["Label"] == label_cabecalho, "Codigo"]
                if s.empty:
                    raise KeyError(f"Label não encontrado: {label_cabecalho}")
                codigo_cabecalho = label_to_codigo[label_cabecalho]
                # print("Codigo", codigo_cabecalho)

                lista_labels_multiindex_coluna = [v[2] for v in df_pond.columns]
                print(lista_labels_multiindex_coluna)
                for label_coluna in pd.Series(sorted(data[COLUNA].astype(int).unique())).map(lista_labels_coluna_mapping):
                    print("Label coluna: ", label_coluna)
                    if label_coluna in lista_labels_multiindex_coluna:
                        s = lista_labels.loc[lista_labels["Label"] == label_coluna, "Codigo"]
                        if s.empty:
                            raise KeyError(f"Label não encontrado: {label_coluna}")
                        codigo_coluna = label_to_codigo[label_coluna]
                        # print("Codigo", codigo_coluna)

                        print(df_pond.index)
                        for label_linha in pd.Series(sorted(data[LINHA].astype(int).unique())).map(lista_labels_linha_mapping):
                            print("Label Linha: ", label_linha)
                            if label_linha in df_pond.index:
                                s = lista_labels.loc[lista_labels["Label"] == label_linha, "Codigo"]
                                if s.empty:
                                    raise KeyError(f"Label não encontrado: {label_linha}")
                                codigo_linha = label_to_codigo[label_linha]
                                # print("Codigo", codigo_linha)
                                print(label_cabecalho_greater, label_cabecalho, label_coluna, label_linha, sep=" - ")

                                pond = df_pond.loc[label_linha, (label_cabecalho_greater, label_cabecalho, label_coluna)]
                                data.loc[((data[CABECALHO_GREATER] == codigo_cabecalho_greater) & (data[CABECALHO] == codigo_cabecalho) & (data[COLUNA] == codigo_coluna) & (data[LINHA] == codigo_linha)), "POND_nova"] = pond

['Sim', 'Sim', 'Sim', 'Sim', 'Sim', 'Sim']
Label cabecalho_greater:  Sim
['PF', 'PF', 'PF', 'PJ', 'PJ', 'PJ']
Label cabecalho:  PF
['Empreendedores', 'Varejo', 'GC', 'Empreendedores', 'Varejo', 'GC']
Label coluna:  Empreendedores
Index(['São Paulo', 'Sudeste (Sem São Paulo)', 'Sul', 'Centro-Oeste', 'Norte',
       'Nordeste'],
      dtype='object')
Label Linha:  São Paulo
Sim - PF - Empreendedores - São Paulo
Label Linha:  Sudeste (Sem São Paulo)
Sim - PF - Empreendedores - Sudeste (Sem São Paulo)
Label Linha:  Sul
Sim - PF - Empreendedores - Sul
Label Linha:  Centro-Oeste
Sim - PF - Empreendedores - Centro-Oeste
Label Linha:  Norte
Sim - PF - Empreendedores - Norte
Label Linha:  Nordeste
Sim - PF - Empreendedores - Nordeste
Label coluna:  Varejo
Index(['São Paulo', 'Sudeste (Sem São Paulo)', 'Sul', 'Centro-Oeste', 'Norte',
       'Nordeste'],
      dtype='object')
Label Linha:  São Paulo
Sim - PF - Varejo - São Paulo
Label Linha:  Sudeste (Sem São Paulo)
Sim - PF - Varejo - Sudeste (Sem São Paulo)
Label Linha:  Sul
Sim - PF - Varejo - Sul
Label Linha:  Centro-Oeste
Sim - PF - Varejo - Centro-Oeste
Label Linha:  Norte
Sim - PF - Varejo - Norte
Label Linha:  Nordeste
Sim - PF - Varejo - Nordeste
Label coluna:  GC
Index(['São Paulo', 'Sudeste (Sem São Paulo)', 'Sul', 'Centro-Oeste', 'Norte',
       'Nordeste'],
      dtype='object')
Label Linha:  São Paulo
Sim - PF - GC - São Paulo
Label Linha:  Sudeste (Sem São Paulo)
Sim - PF - GC - Sudeste (Sem São Paulo)
Label Linha:  Sul
Sim - PF - GC - Sul
Label Linha:  Centro-Oeste
Sim - PF - GC - Centro-Oeste
Label Linha:  Norte
Sim - PF - GC - Norte
Label Linha:  Nordeste
Sim - PF - GC - Nordeste
Label cabecalho:  PJ
['Empreendedores', 'Varejo', 'GC', 'Empreendedores', 'Varejo', 'GC']
Label coluna:  Empreendedores
Index(['São Paulo', 'Sudeste (Sem São Paulo)', 'Sul', 'Centro-Oeste', 'Norte',
       'Nordeste'],
      dtype='object')
Label Linha:  São Paulo
Sim - PJ - Empreendedores - São Paulo
Label Linha:  Sudeste (Sem São Paulo)
Sim - PJ - Empreendedores - Sudeste (Sem São Paulo)
Label Linha:  Sul
Sim - PJ - Empreendedores - Sul
Label Linha:  Centro-Oeste
Sim - PJ - Empreendedores - Centro-Oeste
Label Linha:  Norte
Sim - PJ - Empreendedores - Norte
Label Linha:  Nordeste
Sim - PJ - Empreendedores - Nordeste
Label coluna:  Varejo
Index(['São Paulo', 'Sudeste (Sem São Paulo)', 'Sul', 'Centro-Oeste', 'Norte',
       'Nordeste'],
      dtype='object')
Label Linha:  São Paulo
Sim - PJ - Varejo - São Paulo
Label Linha:  Sudeste (Sem São Paulo)
Sim - PJ - Varejo - Sudeste (Sem São Paulo)
Label Linha:  Sul
Sim - PJ - Varejo - Sul
Label Linha:  Centro-Oeste
Sim - PJ - Varejo - Centro-Oeste
Label Linha:  Norte
Sim - PJ - Varejo - Norte
Label Linha:  Nordeste
Sim - PJ - Varejo - Nordeste
Label coluna:  GC
Index(['São Paulo', 'Sudeste (Sem São Paulo)', 'Sul', 'Centro-Oeste', 'Norte',
       'Nordeste'],
      dtype='object')
Label Linha:  São Paulo
Sim - PJ - GC - São Paulo
Label Linha:  Sudeste (Sem São Paulo)
Sim - PJ - GC - Sudeste (Sem São Paulo)
Label Linha:  Sul
Sim - PJ - GC - Sul
Label Linha:  Centro-Oeste
Sim - PJ - GC - Centro-Oeste
Label Linha:  Norte
Sim - PJ - GC - Norte
Label Linha:  Nordeste
Sim - PJ - GC - Nordeste
Label cabecalho_greater:  Não

In [202]:
df_pond.columns

MultiIndex([('Sim', 'PF', 'Empreendedores'),
            ('Sim', 'PF',         'Varejo'),
            ('Sim', 'PF',             'GC'),
            ('Sim', 'PJ', 'Empreendedores'),
            ('Sim', 'PJ',         'Varejo'),
            ('Sim', 'PJ',             'GC')],
           )

In [201]:
df_pond.columns
[col[1] for col in df_pond.columns]

['PF', 'PF', 'PF', 'PJ', 'PJ', 'PJ']

In [190]:
if "PF" in df_pond.columns:
    print("Ok")

In [176]:
data

,ID_EMP,ID_ONDA,ONDA,COLETA,NU_SO_EC,POND,CIELO_CAMPO,PF_PJ,VCID,VUF,...,BCOSS_3,NUM_F,NUM_FX,FATC,VRAMO,SETOR_BIGDATA,TEMP_EX,TEMP_AC,SEXO,POND_nova
0,3000230,1634,59,2,2.901174e+09,0.999119,2,2,NaN,2,...,NaN,1,1,2.0,20,20.0,1,1,1,NaN
1,3001659,5090,59,2,NaN,1.497418,4,2,NaN,7,...,NaN,1,2,2.0,13,13.0,4,4,1,NaN
2,3000383,1986,59,2,NaN,0.317763,2,2,NaN,6,...,NaN,1,3,1.0,21,21.0,2,2,2,NaN
3,3000455,2153,59,2,NaN,0.263658,4,2,NaN,6,...,NaN,1,2,1.0,21,21.0,6,5,1,NaN
4,3000985,3488,59,2,NaN,1.982729,4,1,NaN,2,...,NaN,1,2,2.0,8,8.0,5,5,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15381,3004081,102279,59,1,NaN,0.263658,3,2,80.0,8,...,NaN,1,3,1.0,21,21.0,4,3,1,NaN
15382,3004082,102294,59,1,NaN,1.982729,3,1,80.0,6,...,NaN,3,19,2.0,13,13.0,6,3,1,NaN
15383,3004083,102343,59,1,NaN,1.497418,3,2,4.0,1,...,NaN,2,7,2.0,4,4.0,5,5,1,NaN
15384,3004084,102609,59,1,NaN,1.497418,3,2,3.0,5,...,NaN,2,5,2.0,20,20.0,2,2,1,NaN
15385,3004085,102632,59,1,NaN,0.263658,3,2,80.0,1,...,NaN,1,2,90.0,13,13.0,5,5,2,NaN

# <font color="greenblue">Novo método de ponderação para verificar os inputs</font>

In [4]:
import pandas as pd
import numpy as np

# === Ponderação para o caso da CIELO === #
# CABECALHO_GREATER = "TRAB_C"
# CABECALHO = 'PF_PJ'
# COLUNA = 'SEG_NOVO_BU'
# LINHA = 'VREG'

path = r"C:\Users\rayner.santos\Downloads\Consistencia e Processamento\Cielo\POND_FINAL_Satisfacao_NOV25_v02.xlsx"
df_universo_d2 = pd.read_excel(path, sheet_name="FONTE_D2", 
                            # header=[0, 1, 2], # <- pega TRAB_C, PÚBLICO e SEGMENTO
                            index_col=0 # <- REGIÃO (VREG) vira índice (Dimensão 4)
                            )

# Lê as duas primeiras linhas como cabeçalho (ajuste para [1,2] se no seu arquivo começa uma linha abaixo)
df_coletado = pd.read_excel(path, sheet_name="COLETADO_D2", 
                            # header=[0, 1, 2], # <- pega SEXO, PÚBLICO e SEGMENTO
                            index_col=0 # <- REGIÃO (VREG) vira índice (Dimensão 4)
                            )

path = r"C:\Users\rayner.santos\Downloads\Consistencia e Processamento\Cielo\EMP_Cielo Satisfacao_3onda_NOV25_2025.12.26.xlsx"
data = pd.read_excel(path, sheet_name="BD_CODIGOS")

lista_labels = pd.read_excel(path, sheet_name="LISTA_LABELS", header=1)
lista_labels.columns = ['Coluna', 'Codigo', 'Label']
lista_labels["Coluna"] = lista_labels["Coluna"].ffill().str.strip()
df_universo_d2

           SEG_NOVO_BU: Empreendedores  SEG_NOVO_BU: Varejo  SEG_NOVO_BU: GC
PF_PJ: PF                     0.053113             0.058802         0.000000
PF_PJ: PJ                     0.091510             0.606461         0.190081

In [11]:
# Soma do universo
total = int(df_universo_d2.sum().sum().round())

if total > 1:
    # df_universo em percentual
    df_universo_perc = df_universo_d2.divide(total)
else:
    # df_universo em percentual
    df_universo_perc = df_universo_d2.copy()

# Calcular a quantidade total de entrevistas
qtd_total_entrevistas = int(df_coletado.sum().sum())

# Valor ideal que deve ter de entrevistas para cada categoria
df_ideal = df_universo_perc.multiply(qtd_total_entrevistas)

# DataFrame com a ponderação criada de acordo com a combinação de categorias
df_pond = pd.DataFrame(
    df_ideal.to_numpy() / df_coletado.astype(float).replace(0, 0.00001).to_numpy(),
    index=df_ideal.index,
    columns=df_ideal.columns
)
df_pond

           SEG_NOVO_BU: Empreendedores  SEG_NOVO_BU: Varejo  SEG_NOVO_BU: GC
PF_PJ: PF                     0.313164             1.982729          0.00000
PF_PJ: PJ                     0.263658             1.497418          4.10195

In [13]:
# Buscando os nomes das colunas e índices
print(df_universo.columns, "\n")
lista_de_colunas_indice = []
lista_de_labels_fonte = []
for col in df_universo.columns:
    for item in col:
        item_coluna = item.split(": ")[0]
        item_label = item.split(": ")[1]
        if item_coluna not in lista_de_colunas_indice:
            lista_de_colunas_indice.append(item_coluna)
        if item_label not in lista_de_labels_fonte:
            lista_de_labels_fonte.append(item_label)
for index in df_universo.index:
    print(index)
    index_linha = index.split(": ")[0]
    index_linha_label = index.split(": ")[1]
    if index_linha not in lista_de_colunas_indice:
        lista_de_colunas_indice.append(index_linha)
    if index_linha_label not in lista_de_labels_fonte:
        lista_de_labels_fonte.append(index_linha_label)
print("\n", lista_de_colunas_indice)
print("\n", lista_de_labels_fonte)

MultiIndex([('TRAB_C: Não', 'SEG_NOVO_BU: Empreendedores'),
            ('TRAB_C: Não',         'SEG_NOVO_BU: Varejo'),
            ('TRAB_C: Não',             'SEG_NOVO_BU: GC')],
           )

PF_PJ: PF
PF_PJ: PJ

 ['TRAB_C', 'SEG_NOVO_BU', 'PF_PJ']

 ['Não', 'Empreendedores', 'Varejo', 'GC', 'PF', 'PJ']

In [24]:
lista_de_colunas_indice = []
lista_de_labels_fonte = []
for item in df_universo_d2.columns:
    print(item)
    col = item.split(": ")[0]
    label = item.split(": ")[1]
    if col not in lista_de_colunas_indice:
        lista_de_colunas_indice.append(col)
    if label not in lista_de_labels_fonte:
        lista_de_labels_fonte.append(label)
for index in df_universo_d2.index:
    print(index)
    index_linha = index.split(": ")[0]
    index_linha_label = index.split(": ")[1]
    if index_linha not in lista_de_colunas_indice:
        lista_de_colunas_indice.append(index_linha)
    if index_linha_label not in lista_de_labels_fonte:
        lista_de_labels_fonte.append(index_linha_label)
print("\n",lista_de_colunas_indice)
print(lista_de_labels_fonte)

SEG_NOVO_BU: Empreendedores
SEG_NOVO_BU: Varejo
SEG_NOVO_BU: GC
PF_PJ: PF
PF_PJ: PJ

 ['SEG_NOVO_BU', 'PF_PJ']
['Empreendedores', 'Varejo', 'GC', 'PF', 'PJ']

In [18]:
isinstance(df_universo_d2.columns, pd.MultiIndex)

False

In [144]:
# Mapeando os códigos para os Labels de cada coluna e índice
mapping_lvls = {}
for i, col in enumerate(lista_de_colunas_indice):
    mapping_lvls[col] = dict(zip(lista_labels[lista_labels["Coluna"] == col]['Codigo'], lista_labels[lista_labels["Coluna"] == col]['Label']))
mapping_lvls

{'TRAB_C': {1: 'Sim', 2: 'Não'},
 'PF_PJ': {1: 'PF', 2: 'PJ'},
 'SEG_NOVO_BU': {1: 'Empreendedores', 2: 'Varejo', 3: 'GC'},
 'VREG': {1: 'São Paulo',
  2: 'Sudeste (Sem São Paulo)',
  3: 'Sul',
  4: 'Centro-Oeste',
  5: 'Norte',
  6: 'Nordeste'}}

In [39]:
mapping_lvls[lista_de_colunas_indice[0]]
lista_de_colunas_indice

['TRAB_C', 'PF_PJ', 'SEG_NOVO_BU', 'VREG']

In [46]:
[v[1].split(": ")[0] for v in df_pond.columns]
[ i.split(": ")[0] for i in df_pond.index]

['VREG', 'VREG', 'VREG', 'VREG', 'VREG', 'VREG']

In [56]:
pd.Series(sorted(df_atualizado[lista_de_colunas_indice[1]].astype(int).unique())).map(mapping_lvls[lista_de_colunas_indice[1]])
[v[1].split(": ")[1] for v in df_pond.columns]

['PF', 'PF', 'PF', 'PJ', 'PJ', 'PJ']

In [61]:
print(df_pond.columns)
lista_de_colunas_indice[0] + ": " + label_cabecalho_greater

MultiIndex([('TRAB_C: Sim', 'PF_PJ: PF', 'SEG_NOVO_BU: Empreendedores'),
            ('TRAB_C: Sim', 'PF_PJ: PF',         'SEG_NOVO_BU: Varejo'),
            ('TRAB_C: Sim', 'PF_PJ: PF',             'SEG_NOVO_BU: GC'),
            ('TRAB_C: Sim', 'PF_PJ: PJ', 'SEG_NOVO_BU: Empreendedores'),
            ('TRAB_C: Sim', 'PF_PJ: PJ',         'SEG_NOVO_BU: Varejo'),
            ('TRAB_C: Sim', 'PF_PJ: PJ',             'SEG_NOVO_BU: GC')],
           )

'TRAB_C: Sim'

In [156]:
# Criar a nova coluna de PONDERAÇÃO de acordo com o df_pond
df_atualizado = data.copy()
if "POND_nova" not in df_atualizado.columns:
    df_atualizado["POND_nova"] = np.nan
label_to_codigo = lista_labels.set_index("Label")["Codigo"].astype(int).to_dict()

qtd_cols_index = len(mapping_lvls)
if qtd_cols_index == 4:
    print("Entrou no if\n")
    for label_cabecalho_greater in pd.Series(sorted(df_atualizado[lista_de_colunas_indice[0]].astype(int).unique())).map(mapping_lvls[lista_de_colunas_indice[0]]):
        print(label_cabecalho_greater)
        if label_cabecalho_greater in [v[0].split(": ")[1] for v in df_pond.columns]:
            s = lista_labels.loc[lista_labels["Label"] == label_cabecalho_greater, "Codigo"]
            if s.empty:
                raise KeyError(f"Label não encontrado: {label_cabecalho_greater}")
            codigo_cabecalho_greater = label_to_codigo[label_cabecalho_greater]
            valor_label_cabecalho_greater = lista_de_colunas_indice[0] + ": " + label_cabecalho_greater

            for label_cabecalho in pd.Series(sorted(df_atualizado[lista_de_colunas_indice[1]].astype(int).unique())).map(mapping_lvls[lista_de_colunas_indice[1]]):
                print(label_cabecalho)
                if label_cabecalho in [v[1].split(": ")[1] for v in df_pond.columns]:
                    s = lista_labels.loc[lista_labels["Label"] == label_cabecalho, "Codigo"]
                    if s.empty:
                        raise KeyError(f"Label não encontrado: {label_cabecalho}")
                    codigo_cabecalho = label_to_codigo[label_cabecalho]
                    valor_label_cabecalho = lista_de_colunas_indice[1] + ": " + label_cabecalho

                    for label_coluna in pd.Series(sorted(df_atualizado[lista_de_colunas_indice[2]].astype(int).unique())).map(mapping_lvls[lista_de_colunas_indice[2]]):
                        print(label_coluna)
                        if label_coluna in [v[2].split(": ")[1] for v in df_pond.columns]:
                            s = lista_labels.loc[lista_labels["Label"] == label_coluna, "Codigo"]
                            if s.empty:
                                raise KeyError(f"Label não encontrado: {label_coluna}")
                            codigo_coluna = label_to_codigo[label_coluna]
                            valor_label_coluna = lista_de_colunas_indice[2] + ": " + label_coluna

                            for label_linha in pd.Series(sorted(df_atualizado[lista_de_colunas_indice[3]].astype(int).unique())).map(mapping_lvls[lista_de_colunas_indice[3]]):
                                print(label_linha)
                                if label_linha in [ i.split(": ")[1] for i in df_pond.index]:
                                    s = lista_labels.loc[lista_labels["Label"] == label_linha, "Codigo"]
                                    if s.empty:
                                        raise KeyError(f"Label não encontrado: {label_linha}")
                                    codigo_linha = label_to_codigo[label_linha]
                                    valor_label_linha = lista_de_colunas_indice[3] + ": " + label_linha

                                    pond = df_pond.loc[valor_label_linha, (valor_label_cabecalho_greater, valor_label_cabecalho, valor_label_coluna)]
                                    df_atualizado.loc[((df_atualizado[lista_de_colunas_indice[0]] == codigo_cabecalho_greater) & 
                                                       (df_atualizado[lista_de_colunas_indice[1]] == codigo_cabecalho) & 
                                                       (df_atualizado[lista_de_colunas_indice[2]] == codigo_coluna) & 
                                                       (df_atualizado[lista_de_colunas_indice[3]] == codigo_linha)), "POND_nova"] = pond
display(df_atualizado[["TRAB_C", "PF_PJ", "SEG_NOVO_BU", "VREG", "POND", "POND_nova"]])

Entrou no if

Sim
Não

       TRAB_C  PF_PJ  SEG_NOVO_BU  VREG      POND  POND_nova
0           1      2            2     2  0.999119        NaN
1           2      2            2     4  1.497418        NaN
2           1      2            1     2  0.317763        NaN
3           2      2            1     2  0.263658        NaN
4           2      1            2     2  1.982729        NaN
...       ...    ...          ...   ...       ...        ...
15381       2      2            1     4  0.263658        NaN
15382       2      1            2     2  1.982729        NaN
15383       2      2            2     1  1.497418        NaN
15384       2      2            2     3  1.497418        NaN
15385       2      2            1     1  0.263658        NaN

[15386 rows x 6 columns]

In [9]:
class Criar_Pond():
    """
        Classe para calcular a coluna de ponderação:
        1) Verificar se há inconsistência no nome do cabeçalho MultiIndex
        2) A partir do universo e o coletado é criado o valor da ponderação
        - Ponderação é o valor IDEAL - percentual do universo vezes o total coletado, divido pelo COLETADO em cada categoria
        3) Com o banco de dados e a lista de labels cria-se a coluna POND no banco de dados
        
    """
    
    def __init__(self, df_universo: pd.DataFrame, df_coletado: pd.DataFrame, bd_codigo: pd.DataFrame, lista_labels: pd.DataFrame):
        self.df_universo = df_universo
        self.df_coletado = df_coletado
        self.bd_codigo = bd_codigo
        self.lista_labels = lista_labels

    def n_niveis_colunas(self):
        cols = self.df_universo.columns
        cols_nlevels = cols.nlevels + 1
        self.cols_nlevels = cols_nlevels
        return cols_nlevels if isinstance(cols, pd.MultiIndex) else 2

    def verificar_cols_multiindex(self):
        # Buscando os nomes das colunas e índices
        lista_de_colunas_indice = []
        lista_de_labels_fonte = []
        if isinstance(self.df_universo.columns, pd.MultiIndex):
            for col in self.df_universo.columns:
                for item in col:
                    if ": " not in item:
                        return f"❌ Não há separação correta com **dois pontos e um espaço -> (: )** entre o nome da COLUNA e a LABEL correspondente. Verificar valor na tabela: **{item}**."
                    else:
                        item_coluna = item.split(": ")[0]
                        item_label = item.split(": ")[1]
                        if item_coluna not in lista_de_colunas_indice:
                            lista_de_colunas_indice.append(item_coluna)
                        if item_label not in lista_de_labels_fonte:
                            lista_de_labels_fonte.append(item_label)

            for index in self.df_universo.index:
                index_linha = index.split(": ")[0]
                index_linha_label = index.split(": ")[1]
                if index_linha not in lista_de_colunas_indice:
                    lista_de_colunas_indice.append(index_linha)
                if index_linha_label not in lista_de_labels_fonte:
                    lista_de_labels_fonte.append(index_linha_label)

            for col in lista_de_colunas_indice:
                if col not in self.lista_labels["Coluna"].unique():
                    return f"❌ Nome da Coluna '{col}' não se encontra na Lista de Labels."
                

                labels_validas = set(self.lista_labels.loc[self.lista_labels["Coluna"] == col, "Label"])
                labels_fonte_col = set()
                for c in self.df_universo.columns:
                    for item in c:
                        if item.split(": ")[0] == col:
                            labels_fonte_col.add(item.split(": ")[1])

                for idx in self.df_universo.index:
                    if idx.split(": ")[0] == col:
                        labels_fonte_col.add(idx.split(": ")[1])

                faltando = labels_fonte_col - labels_validas
                if faltando:
                    return f"❌ Label(s) {sorted(faltando)} não encontrada(s) na Lista de Labels para a coluna '{col}'."
        
        else:
            for item in self.df_universo.columns:
                if ": " not in item:
                    return f"❌ Não há separação correta com **dois pontos e um espaço -> (: )** entre o nome da COLUNA e a LABEL correspondente. Verificar valor na tabela: **{item}**."
                else:
                    item_coluna = item.split(": ")[0]
                    item_label = item.split(": ")[1]
                    if item_coluna not in lista_de_colunas_indice:
                        lista_de_colunas_indice.append(item_coluna)
                    if item_label not in lista_de_labels_fonte:
                        lista_de_labels_fonte.append(item_label)

            for index in self.df_universo.index:
                index_linha = index.split(": ")[0]
                index_linha_label = index.split(": ")[1]
                if index_linha not in lista_de_colunas_indice:
                    lista_de_colunas_indice.append(index_linha)
                if index_linha_label not in lista_de_labels_fonte:
                    lista_de_labels_fonte.append(index_linha_label)

            for col in lista_de_colunas_indice:
                if col not in self.lista_labels["Coluna"].unique():
                    return f"❌ Nome da Coluna '{col}' não se encontra na Lista de Labels."
                

                labels_validas = set(self.lista_labels.loc[self.lista_labels["Coluna"] == col, "Label"])
                labels_fonte_col = set()
                for item in self.df_universo.columns:
                    if item.split(": ")[0] == col:
                        labels_fonte_col.add(item.split(": ")[1])

                for idx in self.df_universo.index:
                    if idx.split(": ")[0] == col:
                        labels_fonte_col.add(idx.split(": ")[1])

                faltando = labels_fonte_col - labels_validas
                if faltando:
                    return f"❌ Label(s) {sorted(faltando)} não encontrada(s) na Lista de Labels para a coluna '{col}'."


        # Mapeando os códigos para os Labels de cada coluna e índice
        mapping_lvls = {}
        for col in lista_de_colunas_indice:
            mapping_lvls[col] = dict(zip(self.lista_labels[self.lista_labels["Coluna"] == col]['Codigo'], self.lista_labels[self.lista_labels["Coluna"] == col]['Label']))

        qtd_cols_index = len(mapping_lvls)
        
        self.qtd_cols_index = qtd_cols_index
        self.lista_de_colunas_indice = lista_de_colunas_indice
        self.mapping_lvls = mapping_lvls
                
        return qtd_cols_index


    def criar_pond(self):
        # Soma do universo
        total = int(self.df_universo.sum().sum().round())

        if total > 1:
            # df_universo em percentual
            df_universo_perc = self.df_universo.divide(total)
        else:
            # df_universo em percentual
            df_universo_perc = self.df_universo.copy()

        # Calcular a quantidade total de entrevistas
        qtd_total_entrevistas = int(self.df_coletado.sum().sum())

        # Valor ideal que deve ter de entrevistas para cada categoria
        df_ideal = df_universo_perc.multiply(qtd_total_entrevistas)

        # DataFrame com a ponderação criada de acordo com a combinação de categorias
        df_pond = pd.DataFrame(
            df_ideal.to_numpy() / self.df_coletado.astype(float).replace(0, 0.00001).to_numpy(),
            index=df_ideal.index,
            columns=df_ideal.columns
        )

        # Criar a nova coluna de PONDERAÇÃO de acordo com o df_pond
        if "POND_nova" not in self.bd_codigo.columns:
            self.bd_codigo["POND_nova"] = np.nan
        label_to_codigo = self.lista_labels.set_index("Label")["Codigo"].astype(int).to_dict()

        if self.cols_nlevels == 2:
            for label_coluna in pd.Series(sorted(self.bd_codigo[self.lista_de_colunas_indice[0]].astype(int).unique())).map(self.mapping_lvls[self.lista_de_colunas_indice[0]]):
                if label_coluna in [v.split(": ")[1] for v in df_pond.columns]:
                    s = self.lista_labels.loc[self.lista_labels["Label"] == label_coluna, "Codigo"]
                    if s.empty:
                        raise KeyError(f"Label não encontrado: {label_coluna}")
                    codigo_coluna = label_to_codigo[label_coluna]
                    valor_label_coluna = self.lista_de_colunas_indice[0] + ": " + label_coluna

                    for label_linha in pd.Series(sorted(self.bd_codigo[self.lista_de_colunas_indice[1]].astype(int).unique())).map(self.mapping_lvls[self.lista_de_colunas_indice[1]]):
                        if label_linha in [ i.split(": ")[1] for i in df_pond.index]:
                            s = self.lista_labels.loc[self.lista_labels["Label"] == label_linha, "Codigo"]
                            if s.empty:
                                raise KeyError(f"Label não encontrado: {label_linha}")
                            codigo_linha = label_to_codigo[label_linha]
                            valor_label_linha = self.lista_de_colunas_indice[1] + ": " + label_linha

                            pond = df_pond.loc[valor_label_linha, valor_label_coluna]
                            self.bd_codigo.loc[((self.bd_codigo[self.lista_de_colunas_indice[0]] == codigo_coluna) & 
                                            (self.bd_codigo[self.lista_de_colunas_indice[1]] == codigo_linha)), "POND_nova"] = pond
                            

        elif self.cols_nlevels == 3:
            for label_cabecalho in pd.Series(sorted(self.bd_codigo[self.lista_de_colunas_indice[0]].astype(int).unique())).map(self.mapping_lvls[self.lista_de_colunas_indice[0]]):
                if label_cabecalho in [v[0].split(": ")[1] for v in df_pond.columns]:
                    s = self.lista_labels.loc[self.lista_labels["Label"] == label_cabecalho, "Codigo"]
                    if s.empty:
                        raise KeyError(f"Label não encontrado: {label_cabecalho}")
                    codigo_cabecalho = label_to_codigo[label_cabecalho]
                    valor_label_cabecalho = self.lista_de_colunas_indice[0] + ": " + label_cabecalho

                    for label_coluna in pd.Series(sorted(self.bd_codigo[self.lista_de_colunas_indice[1]].astype(int).unique())).map(self.mapping_lvls[self.lista_de_colunas_indice[1]]):
                        if label_coluna in [v[1].split(": ")[1] for v in df_pond.columns]:
                            s = self.lista_labels.loc[self.lista_labels["Label"] == label_coluna, "Codigo"]
                            if s.empty:
                                raise KeyError(f"Label não encontrado: {label_coluna}")
                            codigo_coluna = label_to_codigo[label_coluna]
                            valor_label_coluna = self.lista_de_colunas_indice[1] + ": " + label_coluna

                            for label_linha in pd.Series(sorted(self.bd_codigo[self.lista_de_colunas_indice[2]].astype(int).unique())).map(self.mapping_lvls[self.lista_de_colunas_indice[2]]):
                                if label_linha in [ i.split(": ")[1] for i in df_pond.index]:
                                    s = self.lista_labels.loc[self.lista_labels["Label"] == label_linha, "Codigo"]
                                    if s.empty:
                                        raise KeyError(f"Label não encontrado: {label_linha}")
                                    codigo_linha = label_to_codigo[label_linha]
                                    valor_label_linha = self.lista_de_colunas_indice[2] + ": " + label_linha

                                    pond = df_pond.loc[valor_label_linha, (valor_label_cabecalho, valor_label_coluna)]
                                    self.bd_codigo.loc[((self.bd_codigo[self.lista_de_colunas_indice[0]] == codigo_cabecalho) & 
                                                    (self.bd_codigo[self.lista_de_colunas_indice[1]] == codigo_coluna) & 
                                                    (self.bd_codigo[self.lista_de_colunas_indice[2]] == codigo_linha)), "POND_nova"] = pond


        elif self.cols_nlevels == 4:
            for label_cabecalho_greater in pd.Series(sorted(self.bd_codigo[self.lista_de_colunas_indice[0]].astype(int).unique())).map(self.mapping_lvls[self.lista_de_colunas_indice[0]]):
                if label_cabecalho_greater in [v[0].split(": ")[1] for v in df_pond.columns]:
                    s = self.lista_labels.loc[self.lista_labels["Label"] == label_cabecalho_greater, "Codigo"]
                    if s.empty:
                        raise KeyError(f"Label não encontrado: {label_cabecalho_greater}")
                    codigo_cabecalho_greater = label_to_codigo[label_cabecalho_greater]
                    valor_label_cabecalho_greater = self.lista_de_colunas_indice[0] + ": " + label_cabecalho_greater

                    for label_cabecalho in pd.Series(sorted(self.bd_codigo[self.lista_de_colunas_indice[1]].astype(int).unique())).map(self.mapping_lvls[self.lista_de_colunas_indice[1]]):
                        if label_cabecalho in [v[1].split(": ")[1] for v in df_pond.columns]:
                            s = self.lista_labels.loc[self.lista_labels["Label"] == label_cabecalho, "Codigo"]
                            if s.empty:
                                raise KeyError(f"Label não encontrado: {label_cabecalho}")
                            codigo_cabecalho = label_to_codigo[label_cabecalho]
                            valor_label_cabecalho = self.lista_de_colunas_indice[1] + ": " + label_cabecalho

                            for label_coluna in pd.Series(sorted(self.bd_codigo[self.lista_de_colunas_indice[2]].astype(int).unique())).map(self.mapping_lvls[self.lista_de_colunas_indice[2]]):
                                if label_coluna in [v[2].split(": ")[1] for v in df_pond.columns]:
                                    s = self.lista_labels.loc[self.lista_labels["Label"] == label_coluna, "Codigo"]
                                    if s.empty:
                                        raise KeyError(f"Label não encontrado: {label_coluna}")
                                    codigo_coluna = label_to_codigo[label_coluna]
                                    valor_label_coluna = self.lista_de_colunas_indice[2] + ": " + label_coluna

                                    for label_linha in pd.Series(sorted(self.bd_codigo[self.lista_de_colunas_indice[3]].astype(int).unique())).map(self.mapping_lvls[self.lista_de_colunas_indice[3]]):
                                        if label_linha in [ i.split(": ")[1] for i in df_pond.index]:
                                            s = self.lista_labels.loc[self.lista_labels["Label"] == label_linha, "Codigo"]
                                            if s.empty:
                                                raise KeyError(f"Label não encontrado: {label_linha}")
                                            codigo_linha = label_to_codigo[label_linha]
                                            valor_label_linha = self.lista_de_colunas_indice[3] + ": " + label_linha

                                            pond = df_pond.loc[valor_label_linha, (valor_label_cabecalho_greater, valor_label_cabecalho, valor_label_coluna)]
                                            self.bd_codigo.loc[((self.bd_codigo[self.lista_de_colunas_indice[0]] == codigo_cabecalho_greater) & 
                                                            (self.bd_codigo[self.lista_de_colunas_indice[1]] == codigo_cabecalho) & 
                                                            (self.bd_codigo[self.lista_de_colunas_indice[2]] == codigo_coluna) & 
                                                            (self.bd_codigo[self.lista_de_colunas_indice[3]] == codigo_linha)), "POND_nova"] = pond
        
        return self.bd_codigo

In [2]:
import pandas as pd
import numpy as np

path = r"C:\Users\rayner.santos\Downloads\Consistencia e Processamento\Cielo\EMP_Cielo Satisfacao_3onda_NOV25_2025.12.26.xlsx"
data = pd.read_excel(path, sheet_name="BD_CODIGOS")

lista_labels = pd.read_excel(path, sheet_name="LISTA_LABELS", header=1)
lista_labels.columns = ['Coluna', 'Codigo', 'Label']
lista_labels["Coluna"] = lista_labels["Coluna"].ffill().str.strip()

In [11]:
path = r"C:\Users\rayner.santos\Downloads\Consistencia e Processamento\Cielo\POND_FINAL_Satisfacao_NOV25_v02.xlsx"
df_universo = pd.read_excel(path, sheet_name="FONTE_D2", 
                            # header=[0, 1], #  [0, 1, 2] <- pega TRAB_C, PÚBLICO e SEGMENTO
                            index_col=0 # <- REGIÃO (VREG) vira índice (Dimensão 4)
                            )

# Lê as duas primeiras linhas como cabeçalho (ajuste para [1,2] se no seu arquivo começa uma linha abaixo)
df_coletado = pd.read_excel(path, sheet_name="COLETADO_D2", 
                            # header=[0, 1], # [0, 1, 2] <- pega SEXO, PÚBLICO e SEGMENTO
                            index_col=0 # <- REGIÃO (VREG) vira índice (Dimensão 4)
                            )

Criar_ponderacao = Criar_Pond(df_universo=df_universo, df_coletado=df_coletado, bd_codigo=data, lista_labels=lista_labels)
Criar_ponderacao.n_niveis_colunas()
result = Criar_ponderacao.verificar_cols_multiindex()
if isinstance(result, str):
    print(result)
else:
    display(Criar_ponderacao.criar_pond())

,ID_EMP,ID_ONDA,ONDA,COLETA,NU_SO_EC,POND,CIELO_CAMPO,PF_PJ,VCID,VUF,...,BCOSS_3,NUM_F,NUM_FX,FATC,VRAMO,SETOR_BIGDATA,TEMP_EX,TEMP_AC,SEXO,POND_nova
0,3000230,1634,59,2,2.901174e+09,0.999119,2,2,NaN,2,...,NaN,1,1,2.0,20,20.0,1,1,1,1.497418
1,3001659,5090,59,2,NaN,1.497418,4,2,NaN,7,...,NaN,1,2,2.0,13,13.0,4,4,1,1.497418
2,3000383,1986,59,2,NaN,0.317763,2,2,NaN,6,...,NaN,1,3,1.0,21,21.0,2,2,2,0.263658
3,3000455,2153,59,2,NaN,0.263658,4,2,NaN,6,...,NaN,1,2,1.0,21,21.0,6,5,1,0.263658
4,3000985,3488,59,2,NaN,1.982729,4,1,NaN,2,...,NaN,1,2,2.0,8,8.0,5,5,1,1.982729
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15381,3004081,102279,59,1,NaN,0.263658,3,2,80.0,8,...,NaN,1,3,1.0,21,21.0,4,3,1,0.263658
15382,3004082,102294,59,1,NaN,1.982729,3,1,80.0,6,...,NaN,3,19,2.0,13,13.0,6,3,1,1.982729
15383,3004083,102343,59,1,NaN,1.497418,3,2,4.0,1,...,NaN,2,7,2.0,4,4.0,5,5,1,1.497418
15384,3004084,102609,59,1,NaN,1.497418,3,2,3.0,5,...,NaN,2,5,2.0,20,20.0,2,2,1,1.497418
15385,3004085,102632,59,1,NaN,0.263658,3,2,80.0,1,...,NaN,1,2,90.0,13,13.0,5,5,2,0.263658

In [5]:
path = r"C:\Users\rayner.santos\Downloads\Consistencia e Processamento\Cielo\POND_FINAL_Satisfacao_NOV25_v02.xlsx"
df_universo_d4 = pd.read_excel(path, sheet_name="FONTE", 
                            header=[0, 1, 2], #  [0, 1, 2] <- pega TRAB_C, PÚBLICO e SEGMENTO
                            index_col=0 # <- REGIÃO (VREG) vira índice (Dimensão 4)
                            )
df_universo_d4

                                              TRAB_C: Sim                      \
                                                PF_PJ: PF
                              SEG_NOVO_BU: Empreendedores SEG_NOVO_BU: Varejo
VREG: São Paulo                                  0.015883            0.017564
VREG: Sudeste (Sem São Paulo)                    0.012030            0.012581
VREG: Sul                                        0.008219            0.006860
VREG: Centro-Oeste                               0.005639            0.007841
VREG: Norte                                      0.002785            0.003590
VREG: Nordeste                                   0.008557            0.010366

                                                                           \
                                                                PF_PJ: PJ
                              SEG_NOVO_BU: GC SEG_NOVO_BU: Empreendedores
VREG: São Paulo                             0                    0.021737
VREG: Sudeste (Sem São Paulo)               0                    0.017580
VREG: Sul                                   0                    0.013722
VREG: Centro-Oeste                          0                    0.008959
VREG: Norte                                 0                    0.006209
VREG: Nordeste                              0                    0.023304



                              SEG_NOVO_BU: Varejo SEG_NOVO_BU: GC
VREG: São Paulo                          0.166460        0.054838
VREG: Sudeste (Sem São Paulo)            0.114200        0.038281
VREG: Sul                                0.095994        0.036574
VREG: Centro-Oeste                       0.069445        0.017371
VREG: Norte                              0.042107        0.009635
VREG: Nordeste                           0.118255        0.033382

In [7]:
df_universo_d3 = df_universo.copy()
print(df_universo_d2.columns, "\n")
print(df_universo_d3.columns, "\n")
print(df_universo_d4.columns)

Index(['SEG_NOVO_BU: Empreendedores', 'SEG_NOVO_BU: Varejo',
       'SEG_NOVO_BU: GC'],
      dtype='object')

MultiIndex([('TRAB_C: Não', 'SEG_NOVO_BU: Empreendedores'),
            ('TRAB_C: Não',         'SEG_NOVO_BU: Varejo'),
            ('TRAB_C: Não',             'SEG_NOVO_BU: GC')],
           )

MultiIndex([('TRAB_C: Sim', 'PF_PJ: PF', 'SEG_NOVO_BU: Empreendedores'),
            ('TRAB_C: Sim', 'PF_PJ: PF',         'SEG_NOVO_BU: Varejo'),
            ('TRAB_C: Sim', 'PF_PJ: PF',             'SEG_NOVO_BU: GC'),
            ('TRAB_C: Sim', 'PF_PJ: PJ', 'SEG_NOVO_BU: Empreendedores'),
            ('TRAB_C: Sim', 'PF_PJ: PJ',         'SEG_NOVO_BU: Varejo'),
            ('TRAB_C: Sim', 'PF_PJ: PJ',             'SEG_NOVO_BU: GC')],
           )

In [8]:
def n_niveis_colunas(df):
    cols = df.columns
    return cols.nlevels if isinstance(cols, pd.MultiIndex) else 1

print("df_universo_d2:", n_niveis_colunas(df_universo_d2))
print("df_universo_d3:", n_niveis_colunas(df_universo_d3))
print("df_universo_d4:", n_niveis_colunas(df_universo_d4))

df_universo_d2: 1
df_universo_d3: 2
df_universo_d4: 3